# Pancan data access demo

First, import the package.

In [1]:
import cptac.pancan as pc

Authentication through your Box account is required when you download files.

In [2]:
pc.pancan_download("pancanbrca")

Please login to Box on the webpage that was just opened and grant access for cptac to download files through your account. If you accidentally closed the browser window, press Ctrl+C and call the download function again.

In [3]:
pc.pancan_download("pancangbm")

Please login to Box on the webpage that was just opened and grant access for cptac to download files through your account. If you accidentally closed the browser window, press Ctrl+C and call the download function again.

## Load the BRCA dataset

In [4]:
br = pc.PancanBrca()

In [5]:
br.get_clinical(source="mssm")

,tumor_code,discovery_study,discovery_study/type_of_analyzed_samples,consent/age,consent/sex,consent/race,consent/ethnicity,consent/ethnicity_race_ancestry_identified,consent/collection_in_us,consent/participant_country,...,follow-up/additional_treatment_for_new_tumor_radiation,follow-up/additional_treatment_for_new_tumor_pharmaceutical,follow-up/additional_treatment_for_new_tumor_immunological,follow-up/days_from_date_of_initial_pathologic_diagnosis_to_date_of_additional_surgery_for_new_tumor,follow-up/cause_of_death,follow-up/days_from_date_of_initial_pathologic_diagnosis_to_date_of_death,Recurrence-free survival,Overall survial,"Recurrence status (1, yes; 0, no)","Survial status (1, dead; 0, alive)"
Patient_ID,,,,,,,,,,,,,,,,,,,,,
01BR001,BR,NaN,NaN,55,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,421.0,0,0.0
01BR015,BR,NaN,NaN,35,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347.0,0,0.0
01BR017,BR,NaN,NaN,45,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,413.0,0,0.0
01BR018,BR,NaN,NaN,66,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.0,0,0.0
01BR025,BR,NaN,NaN,62,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,601.0,0,0.0
01BR026,BR,NaN,NaN,48,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
01BR027,BR,NaN,NaN,80,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.0,0,0.0
01BR028,BR,NaN,NaN,64,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
01BR030,BR,NaN,NaN,84,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,Not Applicable,Not Applicable,NaN,NaN,NaN,NaN,NaN,389.0,0,0.0
01BR031,BR,NaN,NaN,61,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,363.0,0,0.0
01BR032,BR,NaN,NaN,46,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,363.0,0,0.0
01BR033,BR,NaN,NaN,40,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.0,0,0.0
01BR040,BR,NaN,NaN,40,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
01BR042,BR,NaN,NaN,58,Female,Black or African American,Unknown,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
01BR043,BR,NaN,NaN,59,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
03BR002,BR,NaN,NaN,60,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,365.0,0,0.0
03BR004,BR,NaN,NaN,88,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,358.0,0,0.0
03BR005,BR,NaN,NaN,61,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,304.0,0,0.0
03BR006,BR,NaN,NaN,42,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
03BR009,BR,NaN,NaN,54,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
03BR010,BR,NaN,NaN,78,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,357.0,0,0.0
03BR011,BR,NaN,NaN,71,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
03BR012,BR,NaN,NaN,46,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,390.0,0,0.0
03BR013,BR,NaN,NaN,52,Female,Unknown (Could not be determined or unsure),Unknown,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,355.0,0,0.0
05BR001,BR,NaN,NaN,70,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,363.0,0,0.0
05BR003,BR,NaN,NaN,37,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,406.0,0,0.0
05BR004,BR,NaN,NaN,46,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
05BR005,BR,NaN,NaN,50,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,528.0,0,0.0
05BR009,BR,NaN,NaN,64,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,323.0,0,0.0
05BR016,BR,NaN,NaN,78,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,308.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14BR005,BR,NaN,NaN,78,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,517.0,0,0.0
14BR007,BR,NaN,NaN,72,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
14BR008,BR,NaN,NaN,66,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,505.0,0,0.0
14BR014,BR,NaN,NaN,59,Female,White,Not Evaluated,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,448.0,0,0.0
14BR020,BR,NaN,NaN,54,Female,White,Not Evaluated,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
15BR003,BR,NaN,NaN,74,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,344.0,0,0.0
16BR012,BR,NaN,NaN,47,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,478.0,0,0.0
18BR002,BR,NaN,NaN,64,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,431.0,0,0.0
18BR003,BR,NaN,NaN,65,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,426.0,0,0.0
18BR004,BR,NaN,NaN,76,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,426.0,0,0.0
18BR006,BR,NaN,NaN,62,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,419.0,0,0.0
18BR007,BR,NaN,NaN,64,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,431.0,0,0.0
18BR009,BR,NaN,NaN,63,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,417.0,0,0.0
18BR010,BR,NaN,NaN,41,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,410.0,0,0.0
18BR016,BR,NaN,NaN,73,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,449.0,0,0.0
18BR017,BR,NaN,NaN,72,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,445.0,0,0.0
18BR019,BR,NaN,NaN,68,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,437.0,0,0.0
20BR001,BR,NaN,NaN,82,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,0,0.0
20BR002,BR,NaN,NaN,95,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,0,0.0
20BR005,BR,NaN,NaN,47,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,357.0,0,0.0
20BR006,BR,NaN,NaN,65,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327.0,0,0.0
20BR007,BR,NaN,NaN,55,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,357.0,0,0.0
20BR008,BR,NaN,NaN,71,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347.0,0,0.0
21BR001,BR,NaN,NaN,86,Female,White,Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
21BR002,BR,NaN,NaN,86,Female,White,Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
21BR003,BR,NaN,NaN,46,Female,White,Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
21BR010,BR,NaN,NaN,71,Female,White,Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327.0,0,0.0
22BR003,BR,NaN,NaN,30,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
22BR005,BR,NaN,NaN,46,Female,White,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,348.0,0,0.0
22BR006,BR,NaN,NaN,55,Female,Black or African American,Not Hispanic or Latino,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,282.0,NaN,282.0,0,1.0

In [6]:
br.get_somatic_mutation(source="washu")

               Gene           Mutation        Location      Database_ID
Patient_ID
01BR001      PIK3CD  Missense_Mutation         p.R785W  ENST00000377346
01BR001        CA14             Silent         p.E336E  ENST00000369111
01BR001      ADAM15             Silent         p.T105T  ENST00000356955
01BR001       DCAF6             Silent         p.R222R  ENST00000367840
01BR001     CACNA1E  Missense_Mutation         p.R924C  ENST00000367573
01BR001       HECW2  Missense_Mutation         p.E615K  ENST00000260983
01BR001        FZD7             Silent         p.L486L  ENST00000286201
01BR001      PHLDB2  Missense_Mutation         p.R449H  ENST00000431670
01BR001        BCHE  Missense_Mutation         p.Q379H  ENST00000264381
01BR001     TBC1D19             Silent         p.R442R  ENST00000264866
01BR001        AREG  Missense_Mutation          p.L15F  ENST00000395748
01BR001       SCLT1  Missense_Mutation          p.N48S  ENST00000281142
01BR001       FBXW7  Nonsense_Mutation         p.R393*  ENST00000281708
01BR001       TIGD4  Missense_Mutation         p.W162C  ENST00000304337
01BR001        CDH9  Missense_Mutation          p.A38T  ENST00000231021
01BR001       GCNT4    Frame_Shift_Del    p.D434Lfs*13  ENST00000322348
01BR001        GRM4  Missense_Mutation         p.I665T  ENST00000538487
01BR001       PTPRK  Missense_Mutation         p.A219T  ENST00000525459
01BR001     ALDH8A1  Missense_Mutation          p.R71W  ENST00000265605
01BR001      GPR146             Silent          p.S30S  ENST00000397095
01BR001       STAG3        Splice_Site  p.X1138_splice  ENST00000615138
01BR001       TRIP6  Missense_Mutation         p.A340D  ENST00000200457
01BR001      RNF148  Missense_Mutation         p.V210I  ENST00000434824
01BR001     CCDC136  Missense_Mutation        p.C1058Y  ENST00000297788
01BR001     SLC13A4  Missense_Mutation          p.V28I  ENST00000354042
01BR001       CSPP1        Splice_Site   p.X424_splice  ENST00000262210
01BR001      KLHL38  Missense_Mutation         p.A210T  ENST00000325995
01BR001        GLI4  Missense_Mutation         p.R231G  ENST00000340042
01BR001        PLEC  Missense_Mutation        p.L3732R  ENST00000322810
01BR001       MFSD3  Missense_Mutation         p.G292A  ENST00000301327
...             ...                ...             ...              ...
11BR027      ATP11C  Missense_Mutation         p.H190N  ENST00000327569
11BR027      MAGEC3             Silent         p.L320L  ENST00000298296
11BR027      MAGEC1  Missense_Mutation         p.S185R  ENST00000285879
11BR027      MAGEC1             Silent         p.Q187Q  ENST00000285879
11BR027      MAGEC1  Missense_Mutation         p.P189T  ENST00000285879
11BR027      MAGEC1  Missense_Mutation         p.T221S  ENST00000285879
11BR027      MAGEC1  Missense_Mutation         p.S223R  ENST00000285879
11BR027      MAGEC1  Missense_Mutation         p.S267P  ENST00000285879
11BR027      MAGEC1  Missense_Mutation         p.F276S  ENST00000285879
11BR027      MAGEC1  Missense_Mutation         p.H327Q  ENST00000285879
11BR027      MAGEC1  Missense_Mutation         p.T364A  ENST00000285879
11BR027        AFF2  Missense_Mutation          p.S89C  ENST00000370460
11BR027         IDS             Silent         p.T146T  ENST00000340855
11BR027     MAGEA11             Silent         p.L359L  ENST00000355220
11BR027       PASD1             Silent         p.L567L  ENST00000370357
11BR027      MAGEA4             Silent          p.A28A  ENST00000360243
11BR027      MAGEA4  Missense_Mutation         p.A173T  ENST00000360243
11BR027       GABRE             Silent         p.A193A  ENST00000370328
11BR027      ZNF185  Missense_Mutation           p.R9H  ENST00000535861
11BR027      MAGEA1             Silent         p.L271L  ENST00000356661
11BR027         BGN             Silent          p.S47S  ENST00000331595
11BR027       SRPK3             Silent          p.H44H  ENST00000489426
11BR027       SRPK3             Silent         p.P338P  ENST00000370101
11BR027     ARHGAP4             Silent         p.H612H  ENST00000370028
11BR027      OPN1LW  Missense_Mutation         p.M236V  ENST00000369951
11BR027      OPN1LW             Silent         p.G296G  ENST00000369951
11BR027        FLNA             Silent        p.A1950A  ENST00000369850
11BR027        GDI1             Silent          p.N73N  ENST00000447750
11BR027          F8  Missense_Mutation        p.D1260E  ENST00000360256
11BR027       SPRY3             Silent         p.Q249Q  ENST00000302805

[33689 rows x 4 columns]

In [7]:
br.get_proteomics(source="umich")

Proteins,ARF5-201,M6PR-201,ESRRA-201,FKBP4-201,NDUFAF7-201,FUCA2-201,DBNDD1-201,SEMA3F-201,CFTR-201,CYP51A1-201,...,DDHD1-211,WIZ-210,GBF1-204,APOA5-204,WIZ-212,LDB1-204,WIZ-211,RFX7-204,SWSAP1-202,SVIL-215
Database_ID,ENSG00000004059.11,ENSG00000003056.8,ENSG00000173153.16,ENSG00000004478.8,ENSG00000003509.16,ENSG00000001036.14,ENSG00000003249.14,ENSG00000001617.12,ENSG00000001626.16,ENSG00000001630.17,...,ENSG00000100523.16,ENSG00000011451.21,ENSG00000107862.5,ENSG00000110243.12,ENSG00000011451.21,ENSG00000198728.11,ENSG00000011451.21,ENSG00000181827.15,ENSG00000173928.4,ENSG00000197321.15
Patient_ID,,,,,,,,,,,,,,,,,,,,,
01BR001,0.012367,-0.945999,NaN,-0.478170,1.135840,-0.512706,0.750335,-0.274824,NaN,-0.278244,...,-0.649127,-0.580869,-0.226667,NaN,NaN,-0.676185,-0.068202,-0.078207,-0.328420,NaN
01BR008,-0.514386,0.462307,0.230124,-0.555968,0.491366,-0.656034,-1.220890,-0.369282,-1.036441,-0.059327,...,0.632221,NaN,0.032873,NaN,NaN,-0.015459,0.227424,0.325643,-0.606240,NaN
01BR009,-0.210782,-0.085055,0.380296,-0.389491,1.255391,-0.608007,-0.231318,0.092870,-1.505195,0.206595,...,0.450818,NaN,-0.341503,NaN,NaN,-0.220239,0.125092,0.365397,-0.167392,NaN
01BR010,0.105457,0.351335,-0.322798,-0.821610,0.241406,-0.500140,-0.137824,0.113791,NaN,0.498314,...,-0.423470,NaN,0.360900,NaN,NaN,-0.451556,-0.098897,0.208643,-0.729096,0.670307
01BR015,-0.509298,-0.874164,NaN,-0.113804,-0.131347,-0.412813,0.262210,0.042333,NaN,-0.657666,...,0.406016,-0.493869,-0.192847,NaN,NaN,0.083639,0.966976,-0.012664,0.081968,NaN
01BR017,-0.456085,-0.422949,NaN,-0.870269,0.474307,-0.830309,0.707741,0.292810,-1.162579,-0.519423,...,-0.068234,NaN,-0.200727,NaN,0.727338,0.077515,0.198699,0.159868,NaN,-0.947928
01BR018,-0.164307,-0.264419,1.121425,-0.922346,0.246722,0.186848,-0.039811,-0.060884,NaN,0.098582,...,-0.095946,NaN,-0.260182,NaN,NaN,-0.347339,0.575942,0.165428,NaN,-1.341536
01BR020,-0.078153,-0.388728,-0.268090,0.845224,0.495982,-0.086016,0.175296,0.075910,NaN,-0.571421,...,0.237432,NaN,-0.379198,NaN,NaN,0.175774,0.610044,0.526308,-0.256269,0.817896
01BR023,-0.303983,-0.114765,-0.765492,0.469224,0.333034,-0.328081,-0.472246,0.409787,NaN,-0.230430,...,-0.320561,NaN,-0.129917,NaN,NaN,0.082966,0.342258,0.183923,-0.727190,0.794657
01BR025,0.514449,-0.181170,-0.273682,0.526654,0.422711,0.675484,0.032640,-0.006112,-4.767301,-0.418856,...,-1.401882,NaN,0.237409,NaN,NaN,-0.359958,0.109089,0.039473,1.250211,NaN
01BR026,-0.254687,-0.433818,-0.288629,-0.699806,0.542856,-0.131624,-0.574163,-0.424069,-1.358085,-0.138682,...,0.224815,NaN,0.007638,NaN,NaN,0.195791,0.080742,0.809120,0.334153,NaN
01BR027,0.001688,-0.678567,NaN,0.178151,1.158204,-0.217641,1.298011,-0.804942,-1.400497,0.567364,...,0.480143,-0.446472,0.061206,1.187224,0.084968,-0.504212,-0.015898,0.237943,NaN,NaN
01BR030,-0.660061,-0.267991,-0.064126,0.106572,0.117843,0.798217,-0.538517,0.493432,NaN,-1.032940,...,0.342453,NaN,-0.043339,NaN,NaN,-0.308396,-0.138434,0.616382,NaN,0.229152
01BR031,0.676272,0.538053,NaN,-0.925324,0.222261,-0.347320,-0.025387,-0.151359,NaN,0.225171,...,-0.162146,NaN,-0.281211,NaN,NaN,0.715165,0.286918,0.923912,NaN,0.526520
01BR032,0.285014,-0.157532,NaN,-0.838040,-0.204057,1.169674,0.335796,1.176149,NaN,0.446563,...,-0.071796,0.235849,0.586530,NaN,NaN,0.187143,-0.427614,0.480722,0.393288,NaN
01BR033,-0.628838,-0.438908,0.050452,-0.132665,0.225770,-0.900486,-0.198822,0.205630,-0.877363,-0.800668,...,0.230273,NaN,-0.123489,NaN,NaN,0.660778,0.099057,0.718758,0.143262,NaN
01BR040,-0.153705,-0.385145,0.339370,-0.230261,0.930621,-0.497171,-0.124857,-0.830306,-2.741695,0.484061,...,0.373123,0.260692,-0.194774,NaN,NaN,-1.516998,0.017834,-1.863039,NaN,NaN
01BR042,-0.067531,-0.058101,0.054566,-0.044347,0.314930,-0.912153,-0.181635,0.166180,NaN,-0.458369,...,-1.282228,NaN,0.062189,NaN,NaN,-1.179154,0.500708,NaN,NaN,NaN
01BR043,-0.374128,-0.444391,-0.006215,-0.717370,0.394960,-0.571439,-0.073829,-1.300991,-2.872341,-1.153965,...,-1.264504,NaN,-0.279068,NaN,NaN,-1.163693,0.097440,-0.106246,0.447805,NaN
03BR002,0.021738,-0.791756,-0.042158,0.142145,0.135307,0.167130,0.144323,0.813034,-1.502186,-0.453388,...,-0.288471,NaN,-0.321458,NaN,NaN,-0.161860,-0.432187,-0.045841,0.297138,NaN
03BR004,-0.495665,-0.895888,NaN,-0.082540,0.222031,0.528423,-0.149893,-0.822764,-0.985691,-1.472672,...,0.107368,0.354105,-0.018735,NaN,-0.278563,-0.448186,-0.209642,-0.389937,NaN,NaN
03BR005,-1.045496,-1.036901,0.938419,-0.516023,0.173690,-0.478226,-0.236865,0.801878,NaN,-0.954885,...,0.235481,NaN,-0.668006,NaN,NaN,0.625210,-0.276358,0.466960,NaN,3.013091
03BR006,-0.824781,-0.232301,-0.032420,0.842370,0.401140,-0.866762,-0.724680,-0.143662,-1.460113,-0.165962,...,0.504267,NaN,-0.309271,NaN,NaN,0.188812,-0.009531,0.014429,-0.233323,NaN
03BR010,0.055939,-0.553110,-1.007687,0.620505,0.179022,0.926228,0.442762,1.011806,-1.537134,0.410367,...,-0.062069,NaN,0.452860,NaN,NaN,0.042901,-0.342214,0.022975,0.288063,NaN
03BR011,0.444015,-0.167521,-0.236952,0.128702,-0.105732,0.392317,-0.597837,0.258488,NaN,-0.561668,...,-0.774195,NaN,0.335743,NaN,NaN,-0.166668,-0.064058,0.130769,-0.425508,0.433405
03BR013,-0.000799,-0.750885,NaN,-0.524208,-0.416674,0.479892,0.608737,0.560135,-0.949086,-0.897739,...,0.229061,-0.522294,0.090283,NaN,-0.206176,0.252957,-0.024585,0.106733,NaN,NaN
05BR001,0.235065,-0.574439,NaN,-0.202276,-0.156920,-0.551960,0.282831,-0.762923,NaN,-0.699721,...,0.666705,NaN,-0.062854,NaN,NaN,-0.344965,-0.079027,0.199019,NaN,-1.200344
05BR003,-0.771361,-0.532881,-0.326465,0.212867,-0.001153,-0.606051,-0.012429,-0.727154,-2.034999,-0.428694,...,-0.103391,NaN,-0.102442,NaN,NaN,0.187046,-0.020788,-0.021146,0.296405,NaN
05BR004,-0.623944,-0.785872,-0.490778,-0.367815,-0.189208,-1.119399,-0.526620,0.783677,-0.249279,-1.038807,...,0.892801,NaN,-0.236824,NaN,NaN,0.626303,0.260427,0.107646,-0.294675,NaN
05BR005,-0.287194,-0.060242,0.544430,-0.107504,0.065197,-0.783915,-0.110527,0.002290,-1.117799,-0.347365,...,0.153631,NaN,-0.007896,NaN,NaN,0.181966,-0.093690,-0.075570,0.166073,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11BR076,0.088269,-0.037398,0.211992,-0.471725,0.253513,0.039560,0.363207,0.716435,1.312877,0.010232,...,0.329388,NaN,0.240846,NaN,NaN,-0.181492,-0.094372,0.348717,0.116377,NaN
11BR078,-0.169111,-0.257768,0.114564,0.056890,-0.121364,0.008110,-0.429379,-0.547549,1.568615,-0.100843,...,0.378131,NaN,-0.100996,NaN,NaN,-0.212327,-0.059605,0.148334,0.148599,NaN
11BR080,-0.216170,0.480249,-0.679568,-0.798585,0.071313,-0.417113,-0.271373,-0.039835,NaN,-0.448485,...,-0.835147,NaN,0.083796,NaN,NaN,0.261055,-0.144582,NaN,NaN,NaN
13BR009,-0.227957,0.349655,0.128153,0.024093,0.543990,0.719385,-0.243996,-0.428022,NaN,-0.336094,...,-0.300011,NaN,-0.044579,NaN,NaN,0.331595,-0.335101,NaN,NaN,NaN
14BR005,-0.082637,-0.043136,0.133290,0.627042,0.246434,0.127937,-0.611973,-0.242112,-2.185781,0.195861,...,-0.181813,NaN,0.207153,NaN,NaN,0.108918,0.090133,0.415871,0.173688,NaN
14BR008,-0.436208,-0.775582,NaN,-0.422359,-0.083417,-0.455337,1.675248,0.844355,-0.403832,-0.116142,...,0.382142,0.852857,-0.453832,NaN,0.345758,0.300577,-0.077996,0.322780,NaN,NaN
14BR014,-0.806347,-0.557897,-0.044127,-0.050073,0.242984,-0.542215,0.144548,0.729911,NaN,-0.222088,...,-0.149948,NaN,-0.387702,NaN,NaN,-0.022076,-0.009807,NaN,NaN,NaN
15BR003,-0.212571,0.128036,0.612254,-0.337731,0.226588,-0.682638,0.124460,0.361472,NaN,-0.940003,...,-0.769859,NaN,0.177275,NaN,NaN,-0.005753,-0.073446,NaN,NaN,NaN
16BR012,0.113567,-0.290335,0.321927,-0.000806,-0.072520,0.479237,-0.450844,0.500347,0.382912,-0.542897,...,0.278962,NaN,0.177109,NaN,NaN,0.497265,0.439316,-0.523950,0.156161,NaN
18BR002,0.061892,-0.503382,NaN,-0.689298,-0.102181,-0.556099,-0.562566,-1.231191,1.061432,-0.212114,...,0.406516,0.216511,0.013131,NaN,-0.145411,-0.307948,0.023808,-0.188650,NaN,NaN
18BR003,-0.668035,-0.186937,-0.539171,-0.987103,0.163090,-0.312829,-0.239112,-0.432026,NaN,0.278976,...,0.368125,NaN,0.132728,0.784058,NaN,0.155363,-0.488887,-0.007448,NaN,1.019027
18BR004,0.861870,-0.113748,1.184738,0.132507,0.454913,0.401912,0.826343,0.176891,-2.142509,-0.638793,...,0.080048,NaN,0.337514,NaN,NaN,0.604032,-0.618640,0.463813,1.275217,0.461210
18BR006,0.029729,0.438934,NaN,0.495185,-0.066783,0.086695,0.338549,0.580807,0.203903,0.613052,...,-0.019253,NaN,-0.026869,0.911466,NaN,-0.145908,-0.046077,0.070597,NaN,-0.449175
18BR007,-0.566614,-0.173107,NaN,0.159460,0.371538,-0.103173,-0.590250,-0.182351,NaN,-0.665919,...,-0.651470,NaN,-0.170059,NaN,NaN,-0.397298,0.002779,-0.444974,NaN,-2.313549
18BR009,-0.124798,-0.302788,NaN,-1.036511,-0.064786,-0.289362,0.317725,0.129267,0.384527,-0.658020,...,-0.074237,NaN,0.051388,0.738015,NaN,-0.128254,-0.182502,-0.158901,NaN,0.821900
18BR010,0.005868,-0.479787,NaN,-0.106832,-0.096298,-0.125842,0.069557,0.295125,-0.969607,-0.630231,...,-0.078162,NaN,-0.461357,NaN,0.441867,0.102127,-0.009252,0.102289,NaN,-0.616593
18BR016,0.072600,-0.168638,0.379680,-0.518223,-0.173312,0.034151,-0.373059,-0.373055,-0.251555,-0.513910,...,-0.317291,NaN,0.343448,NaN,NaN,0.236501,-0.322021,0.270538,-0.487404,NaN
18BR017,0.431638,-0.257658,NaN,0.256140,-0.382104,0.159356,0.891820,0.146538,0.299602,0.669755,...,-0.116827,NaN,0.380040,NaN,0.287355,0.001492,-0.094358,-0.020082,NaN,-0.540734
18BR019,0.046791,-0.233579,0.093193,0.137798,0.173341,-0.151921,0.865952,0.241363,0.553652,-0.844056,...,0.098277,NaN,0.023393,NaN,NaN,0.230553,-0.358904,0.221931,0.217940,0.436931
20BR001,0.293909,-0.261756,0.701077,0.316415,0.705052,0.685047,0.412604,0.156520,-2.151480,-0.394890,...,-0.134296,NaN,0.010722,NaN,NaN,0.169843,-0.291031,0.266331,1.691881,0.142649
20BR002,0.170434,-0.985218,-0.049868,-0.563133,0.592148,-0.474247,-0.270368,-0.347883,-3.459275,-0.813533,...,-0.183305,NaN,-0.541007,NaN,NaN,0.063076,0.099441,-1.276844,-0.316430,NaN
20BR005,0.436349,0.745378,-0.096487,-0.320108,0.279198,-0.617072,-0.394370,-0.807387,-0.102978,0.960069,...,0.351484,NaN,0.027446,NaN,NaN,0.390983,0.447442,-0.094529,0.017998,0.467755
20BR006,-0.403867,-0.212471,-0.306883,-0.051285,0.354692,-0.526174,0.312540,0.894973,NaN,-0.161261,...,-0.488112,NaN,0.201037,NaN,NaN,-0.142026,-0.151829,0.081527,-0.312957,0.223979
20BR007,-0.446777,-0.514069,-0.111667,-1.282843,0.278575,-0.456558,-0.607653,0.021664,0.533670,0.233788,...,0.346725,NaN,0.106522,0.535418,NaN,-0.939397,-0.345641,-0.136955,0.294785,NaN
20BR008,-0.047949,-0.297889,-0.053536,-0.586441,0.468878,0.413048,-0.112786,-0.928736,-2.445201,0.137235,...,-0.958581,NaN,-0.288799,0.159869,NaN,-0.346358,-0.271449,0.080186,-0.077565,NaN
21BR001,0.049138,0.019567,0.464289,-0.271759,-0.090762,0.213537,-0.585926,-0.392422,-0.181147,-0.099128,...,0.272472,NaN,0.667498,NaN,NaN,0.453971,0.168903,0.123395,-0.021897,NaN
21BR002,-0.123071,0.376322,0.090078,-0.456772,-0.162364,-0.522635,-1.081770,-0.408173,-0.060741,0.529680,...,0.532713,NaN,0.239499,NaN,NaN,-0.104097,-0.186308,-0.064656,-0.428425,NaN
21BR010,0.276639,-0.497826,-0.497360,-0.500425,0.162466,0.201618,0.151024,0.125401,0.516739,-0.028335,...,-0.053946,0.636608,0.059573,0.432132,-0.095070,-0.248483,-0.283688,-0.067717,-0.311446,0.602422
22BR005,-0.549542,0.134236,NaN,0.580773,-0.080663,-0.056509,-0.148632,0.260986,NaN,-0.348578,...,0.791937,NaN,0.171712,NaN,NaN,0.083980,-0.200083,0.155198,NaN,0.456801
22BR006,0.336092,0.125742,NaN,-0.360510,0.086199,0.470607,-0.515990,-0.162247,1.003075,0.342987,...,-0.080755,NaN,0.174904,-0.353412,NaN,-0.013793,-0.253829,-0.117960,NaN,1.094966

### PDC data

We can also access data from the PDC.

In [8]:
br.get_proteomics(source="pdc")

,A1BG,A2M,A2ML1,AAAS,AACS,AADAT,AAED1,AAGAB,AAK1,AAMDC,...,ZSWIM6,ZSWIM8,ZW10,ZWILCH,ZWINT,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
Patient_ID,,,,,,,,,,,,,,,,,,,,,
01BR001,0.9205,0.6200,-1.5461,0.2554,-0.3552,0.6674,-0.0670,-0.6254,0.0348,-0.0926,...,1.4294,0.3076,-0.0350,0.0526,-0.2611,NaN,0.0833,0.3494,-0.4951,-0.0277
01BR008,-0.3536,0.0777,0.6186,0.1901,-1.1722,NaN,-0.0570,-0.3568,-0.1714,-0.7457,...,-0.3064,0.1519,0.0751,0.3912,0.3039,0.8274,-0.2727,-0.0614,0.0221,0.2325
01BR009,0.2883,1.0262,1.0538,-0.0663,-0.5431,NaN,-0.0249,-0.2518,-0.1299,-0.3942,...,0.7016,-0.1318,0.0395,-0.1353,-0.2882,0.1155,0.0559,0.0483,-0.0525,-0.1099
01BR010,-0.3184,-0.4881,-2.1017,0.1253,1.1133,2.9714,0.4628,-0.4796,-0.0832,0.0437,...,NaN,-0.0165,0.6256,-0.6235,-0.4788,-0.0709,-0.2461,0.5954,0.0013,-0.0767
01BR015,0.3141,-0.2018,-1.7129,0.4972,0.1122,-0.3622,0.0160,-0.1703,-0.1707,0.1023,...,0.4717,-0.0607,-0.0760,-0.2731,0.3965,NaN,-0.1536,0.5973,-0.4811,0.5128
01BR017,0.5332,0.9145,0.1794,0.2714,-0.0139,NaN,NaN,0.0743,0.1176,-0.0783,...,NaN,0.0544,-0.0216,-0.1709,0.4388,-0.1386,0.0258,0.3417,-0.1216,0.0683
01BR018,0.7488,0.9163,0.6128,0.0266,-1.2230,0.9211,NaN,-0.1070,-0.4273,0.2394,...,NaN,-0.0388,-0.2463,0.2163,0.2484,-0.9878,0.1576,-0.1007,-0.0100,0.6081
01BR020,-0.1689,-0.4631,-1.8397,0.2066,-0.5330,0.1530,0.0291,-0.0143,-0.2138,0.5030,...,NaN,-0.2309,0.4213,0.3159,1.1114,0.1931,-0.3526,0.3618,-0.6312,0.1532
01BR023,-0.3675,-0.7980,-2.7244,0.3550,-0.9243,-1.2035,-0.4903,0.2965,0.1358,-0.2708,...,NaN,0.1809,-0.0949,-0.5968,-0.4550,0.3459,-0.0935,-0.5749,0.2780,0.5607
01BR025,-0.1107,-0.5642,-1.1304,0.5184,0.4934,NaN,0.5896,0.6201,-0.0904,1.0584,...,NaN,-0.1380,0.5805,0.6766,-0.1359,-1.2911,0.2289,-0.1789,-0.0396,-0.4692
01BR026,0.7218,1.1547,1.8365,0.1381,-0.9313,NaN,1.1202,0.1238,-0.1614,0.1027,...,0.7404,0.1185,0.0058,0.4090,-0.4953,0.2216,0.4262,0.5815,0.0226,0.3165
01BR027,-0.0756,0.5439,2.8934,0.5581,-0.8132,0.1108,0.6384,0.1959,-0.0871,-0.7512,...,0.1656,-0.1708,0.6559,0.3891,-0.0330,0.6280,0.1195,-0.1490,-0.2494,0.4027
01BR027,2.2483,2.9239,1.0764,0.6913,-0.2457,NaN,NaN,-0.0589,-0.1981,0.6348,...,NaN,-0.1027,0.0378,NaN,NaN,-1.0053,NaN,0.3563,-0.6210,NaN
01BR030,0.7404,0.6252,-1.0969,-0.0511,-0.5268,-0.3188,NaN,-0.0850,-0.1179,-0.3059,...,NaN,-0.0101,-0.1693,-0.1956,-0.2673,0.5666,0.1365,-0.2153,0.0127,0.1690
01BR031,0.0288,0.3430,-0.1887,0.2046,-0.4751,-0.0686,-0.6156,-0.5141,-0.0824,-0.2172,...,NaN,0.3057,0.1555,0.4169,-0.1762,0.2249,0.4222,0.3146,-0.1123,-0.1735
01BR032,-0.4948,-0.2783,-2.2871,0.0272,0.2722,-1.0084,-0.7767,0.2132,0.5713,1.0879,...,-1.6465,0.3621,-0.0445,0.0289,0.5855,NaN,0.2205,-0.3497,0.1550,0.3745
01BR033,0.3465,0.0791,-1.2820,0.2252,-0.4101,-1.1309,-0.3449,0.5164,0.0352,-0.2661,...,-0.0838,-0.4735,-0.4417,-0.0763,-0.1634,0.8475,-0.1628,0.6418,-0.0611,0.0636
01BR040,0.4068,0.3210,2.8655,0.6766,1.0376,1.1510,0.7730,0.5625,-0.7765,-1.3108,...,-0.1887,0.3423,0.5888,0.3243,0.7419,-0.8737,-0.2385,-0.2733,-0.1629,0.3493
01BR042,0.1911,0.0660,1.4921,0.2698,-0.4139,NaN,0.7602,-0.3577,0.4585,0.4267,...,-0.1055,-0.2421,0.5212,0.8596,0.8085,-0.7566,0.9230,-0.0722,-0.2847,-0.7336
01BR043,0.5015,0.2959,-0.7783,0.5622,-0.7029,NaN,0.7250,0.4532,0.0071,-0.3561,...,NaN,-0.2535,0.4332,0.7062,0.8386,-0.6029,0.3089,0.0728,0.0805,0.1571
01BR044,0.8683,0.6503,-0.8779,0.6190,-0.7699,NaN,1.2842,0.1520,0.4192,-0.8384,...,1.2047,-0.0467,0.4370,0.2844,0.1801,-0.2546,0.3313,1.4258,-0.2969,-0.4898
03BR002,0.8365,0.6834,-1.1327,-0.1064,-0.7477,NaN,0.4525,0.4876,0.0450,0.4744,...,0.2650,-0.2629,-0.1799,-0.1177,-0.4603,-0.4452,0.0058,0.2918,-0.2711,-0.4369
03BR004,-0.0115,0.2541,-1.9829,0.1418,-0.3408,-0.3281,0.6898,0.4569,-0.2568,0.1494,...,-1.0393,0.2469,0.0872,-0.6088,-0.0333,0.2385,0.1526,-0.0257,-0.0302,-0.3624
03BR005,1.0895,1.2464,-0.9549,-0.8062,-0.9793,0.6170,NaN,-0.4420,-0.2829,1.6168,...,NaN,0.0107,-0.3602,-0.5990,-0.8651,1.5635,-0.2392,0.2299,-0.3851,0.5644
03BR006,-0.9804,-0.7511,0.8833,0.5709,-0.5232,NaN,-0.0209,-0.9446,-0.1140,-1.1978,...,-0.8029,-0.0961,0.2245,0.4409,0.6818,0.3464,-0.0711,0.0467,-0.0865,-0.1362
03BR010,0.4712,-0.0449,-1.4350,0.0785,0.5326,0.4256,-0.7119,1.2272,0.1625,0.3944,...,0.1835,0.0701,0.0261,-0.7019,0.0179,0.1294,-0.3658,-0.5676,0.4108,-0.1088
03BR011,0.1578,-0.0671,-2.6639,-0.0396,-0.3583,-0.6364,-0.0844,0.3545,0.0868,3.6051,...,NaN,-0.0580,0.4637,0.2970,0.0853,0.0962,-0.3484,-0.0463,-0.0038,-0.2362
03BR013,0.6183,0.0210,-1.7295,-0.1048,-0.5589,-0.2368,0.1427,0.3162,0.0469,0.2785,...,-0.2778,0.0118,-0.0794,-0.4726,0.0712,-0.3359,-0.0559,0.4764,-0.3368,-0.0184
05BR001,-0.2042,-0.0302,-1.0685,-0.0667,-1.6236,0.3464,-0.5292,0.1633,0.3263,0.0572,...,NaN,0.1738,0.1389,0.1438,0.2855,-0.1752,0.2809,0.6309,-0.0300,-0.0531
05BR003,0.1338,0.0589,-0.8227,-0.0207,-0.3536,NaN,0.6450,0.2302,0.1437,0.8791,...,NaN,-0.0104,-0.1131,0.0430,-0.1013,0.0984,-0.1878,-0.0498,-0.3837,-0.0206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20BR002,0.9398,0.6622,2.2911,0.7455,0.4383,-0.0353,-0.1486,-0.4544,-0.2150,0.3008,...,-0.9525,-0.0635,0.1341,0.6710,-0.1221,-0.8141,0.7903,0.5159,-0.2995,0.4063
20BR005,-0.2445,-0.6762,1.5605,0.1736,0.0445,-0.0565,-0.4935,-0.3371,0.0282,-0.0645,...,NaN,0.2521,-0.0416,0.0271,-0.0957,0.5604,0.1518,0.6420,-0.0407,0.1669
20BR006,0.4323,0.4574,1.1523,-0.0613,-0.3652,-0.4308,-0.1725,-0.0681,0.6596,0.2385,...,NaN,0.0408,-0.2390,-0.1870,0.9360,0.4589,0.0305,-0.2064,0.1237,-0.1504
20BR007,1.8325,2.1889,-0.0431,0.3265,0.3449,NaN,NaN,-0.2653,-0.0417,0.7865,...,NaN,-0.0743,0.0167,NaN,NaN,-0.4128,NaN,0.5721,-0.4143,NaN
20BR007,-0.1864,0.4545,1.0640,0.1601,-0.2996,-1.1204,-0.7906,0.0212,0.0513,-0.1631,...,0.9285,-0.0582,0.3058,0.7243,0.1026,-0.1002,0.1386,0.3509,-0.0763,-0.0944
20BR008,1.3830,1.7031,2.3716,0.2318,-0.0492,NaN,NaN,-0.4976,-0.0192,0.3312,...,NaN,-1.4303,0.0123,NaN,NaN,NaN,NaN,0.3866,0.0363,NaN
20BR008,0.4311,0.4555,-1.1150,0.3405,0.8346,0.7072,0.5062,0.3785,-0.1339,-0.0985,...,0.3840,-0.0741,0.3780,-0.0803,-0.2094,0.3650,-0.1192,0.4976,0.0567,0.0334
21BR001,-0.3887,-0.3321,-1.5772,0.3615,-0.5789,NaN,-0.2758,-0.1014,0.0007,0.1394,...,-0.7752,0.3124,0.1216,0.1101,-0.2288,0.5830,0.1442,-0.2122,0.6049,0.4150
21BR002,-0.5366,0.0777,-1.6762,0.1583,-1.0564,NaN,0.2405,0.1917,0.2560,-0.4864,...,-0.3645,0.1491,0.4525,-0.2397,-0.5140,-0.2264,0.0962,0.1007,0.1769,-0.1991
21BR010,1.7121,1.7018,-0.0860,0.0189,-0.0622,NaN,NaN,-0.1173,-0.1968,1.4505,...,NaN,-0.3289,-0.1673,NaN,NaN,-0.2717,NaN,0.7884,-0.5194,NaN
22BR005,0.0333,-0.2818,-1.8557,0.0476,-0.1963,-0.6790,1.6521,0.4078,0.2451,0.0644,...,NaN,-0.0040,-0.1922,-0.0142,0.4026,0.4191,-0.0332,-0.0792,-0.0764,0.3712
22BR006,0.0283,-0.1448,-2.3651,0.1656,-0.2243,NaN,0.1727,0.6299,-0.2723,-0.1252,...,-0.2893,0.0932,0.3113,-0.5047,-0.8065,0.0346,-0.1302,0.8006,0.4016,0.0994
604,0.2266,0.1471,1.5572,1.0511,-0.2685,NaN,0.7318,-0.4866,0.0673,-0.6787,...,-0.2403,-0.1625,0.5381,0.8036,1.2009,-0.6733,0.9159,-0.2141,-0.2497,0.3163
NaN,-0.0734,-0.2707,-1.8129,0.3198,0.0160,-0.9752,-0.0611,0.1919,0.1232,0.2896,...,0.1536,0.4157,0.0437,-0.1440,-0.1581,-0.9888,0.0381,-0.7032,0.2738,0.3859
NaN,-0.1751,-0.3024,-1.5420,0.2963,0.0494,NaN,-0.0175,0.1065,-0.1136,0.0601,...,0.1836,0.3592,0.0686,0.1415,-0.0580,-0.7894,0.1794,-0.5863,0.2920,0.4410
NaN,-0.0170,-0.1905,-0.1389,0.2770,-0.1273,-0.4474,-0.3609,-0.1006,0.2999,0.7832,...,0.2149,0.0507,0.4844,0.2438,-0.4289,NaN,-0.2395,0.2881,0.0228,0.1523
NaN,0.1459,-0.2003,-0.1291,0.2324,-0.1644,-0.6254,0.5885,0.1498,0.1563,0.5940,...,-0.3389,0.0353,0.3865,0.1310,0.1113,-0.4614,-0.0882,0.1097,0.0469,0.1709
NaN,-0.1538,-0.2198,-2.0213,0.3634,0.8356,NaN,-0.0735,-0.4059,-0.5704,-0.2388,...,0.4500,0.0886,0.7586,0.7238,1.4863,0.8353,0.3079,-1.0404,0.3149,0.1376
NaN,-0.0309,-0.2782,-2.4248,0.1445,0.9305,NaN,0.1590,-0.6423,-0.5537,-0.0248,...,-0.1075,0.1176,0.6501,0.6726,1.1293,0.5515,0.2478,-0.8352,0.2772,0.1275
NaN,-0.2494,-0.2773,-2.0700,0.1965,0.7047,-0.1878,0.1211,-0.4773,-0.6193,-0.1667,...,NaN,-0.0095,0.7643,0.6779,0.8994,0.5833,0.3077,-0.7981,0.2416,-0.0017
NaN,0.3617,0.1531,-2.0796,-0.0821,-0.8902,-0.3194,0.6773,0.0699,0.3560,-0.2962,...,-0.2920,0.1885,0.3495,-1.1626,-0.0831,-0.5715,0.0889,0.2414,-0.0141,0.0321
NaN,0.3938,0.1218,-2.0980,-0.0572,-0.5588,-0.6998,-0.1611,0.1703,0.2615,0.3601,...,NaN,0.0374,0.2900,-0.6573,-0.5772,-0.6335,0.0649,0.4251,-0.0013,0.0828
NaN,0.1584,0.4425,-1.4190,0.1325,-0.1329,-0.4175,0.2121,0.0897,0.1530,0.0278,...,-0.0889,-0.1709,0.4379,0.0651,0.0567,0.3911,-0.0183,0.1544,0.2760,-0.0248
NaN,0.3878,0.5386,-1.2312,-0.0009,-0.1071,NaN,0.5777,0.3109,0.0754,0.1828,...,-0.3341,-0.1135,0.3448,0.2708,0.0530,-0.3500,0.1441,0.2282,0.2776,0.0288
NaN,0.1572,0.1278,-0.4444,-0.0342,-0.2273,0.3058,NaN,0.0678,-0.0237,0.3057,...,NaN,-0.0107,0.0496,0.1793,-0.0038,-0.3540,0.1588,0.1037,0.0123,-0.0890
NaN,0.0779,0.1014,-0.3605,0.1822,0.0203,NaN,-0.0296,0.1358,0.0059,0.0993,...,0.2477,-0.0839,0.0665,0.3095,0.3249,-0.4671,0.5608,0.0596,-0.0825,0.0321
NaN,-0.2079,-0.2041,-1.8864,-0.0883,0.1703,-0.7900,0.0016,0.6618,0.0964,0.2010,...,NaN,-0.0176,-0.0676,-0.1881,-0.6071,-0.4893,-0.1105,-0.0821,0.0562,-0.1859
NaN,-0.3582,-0.2731,-2.1628,-0.3046,0.0579,-0.6230,0.4483,0.3784,0.2693,0.2479,...,NaN,-0.2146,-0.0368,-0.3171,-0.2672,0.1498,-0.1925,-0.1025,0.0961,-0.3982
NaN,0.1894,0.0999,-1.3727,-0.7131,-0.1960,1.4673,0.3508,1.0792,-0.0617,0.9795,...,-0.1829,-0.1687,-0.1745,-0.4944,2.3549,0.0688,0.2378,0.8307,-0.1692,0.7123
NaN,0.1131,-0.1698,-1.7414,-0.4771,-0.5050,-0.4510,1.3335,0.4047,0.6702,0.9354,...,-0.7416,-0.3786,-0.1567,0.0338,0.8062,0.4910,0.0513,0.5816,-0.1929,-0.3971

In [9]:
br.get_clinical(source="pdc")

,age_at_diagnosis,ajcc_clinical_m,ajcc_clinical_n,ajcc_clinical_stage,ajcc_clinical_t,ajcc_pathologic_m,ajcc_pathologic_n,ajcc_pathologic_stage,ajcc_pathologic_t,ann_arbor_b_symptoms,...,synchronous_malignancy,tissue_or_organ_of_origin,tumor_cell_content,tumor_grade,tumor_stage,vascular_invasion_present,vital_status,year_of_birth,year_of_death,year_of_diagnosis
case_submitter_id,,,,,,,,,,,,,,,,,,,,,
01BR001,20074.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
01BR008,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR009,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR010,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR015,12774.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
01BR017,16424.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage III,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage III,Not Reported,Not Reported,NaN,NaN,NaN
01BR018,24089.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
01BR020,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR023,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR025,22629.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
01BR026,0.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR027,29199.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
01BR030,30659.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
01BR031,22264.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage III,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage III,Not Reported,Not Reported,NaN,NaN,NaN
01BR032,15329.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIB,Not Reported,Not Reported,NaN,NaN,NaN
01BR033,14599.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage III,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage III,Not Reported,Not Reported,NaN,NaN,NaN
01BR040,14599.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
01BR042,21139.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage II,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage II,Not Reported,Not Reported,NaN,NaN,NaN
01BR043,21747.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage II,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage II,Not Reported,Not Reported,NaN,NaN,NaN
01BR044,30994.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage III,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage III,Not Reported,Not Reported,NaN,NaN,NaN
03BR002,22112.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
03BR004,32363.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
03BR005,22417.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
03BR006,15512.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
03BR010,28652.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
03BR011,25945.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
03BR013,19010.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
05BR001,25549.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
05BR003,13717.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
05BR004,0.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13BR009,27374.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIB,Not Reported,Not Reported,NaN,NaN,NaN
14BR005,28530.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
14BR008,24089.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
14BR014,21565.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
15BR003,0.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
16BR012,14599.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIC,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIC,Not Reported,Not Reported,NaN,NaN,NaN
18BR002,23390.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR003,24029.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR004,28013.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR006,22721.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR007,23359.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR009,23177.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR010,14934.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR016,26918.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IA,Not Reported,Not Reported,NaN,NaN,NaN
18BR017,26492.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IA,Not Reported,Not Reported,NaN,NaN,NaN
18BR019,24819.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
20BR001,29929.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
20BR002,32872.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
20BR005,17276.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
20BR006,23877.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
20BR007,19679.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
20BR008,26249.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIB,Not Reported,Not Reported,NaN,NaN,NaN
21BR001,0.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
21BR002,0.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
21BR010,25914.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
22BR005,16759.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
22BR006,19922.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
604,14964.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
Internal Reference - Pooled Sample,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,NaN,Not Reported,Not Reported,...,NaN,Not Reported,NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
RetroIR,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,NaN,Not Reported,Not Reported,...,NaN,Not Reported,NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN

## Load the GBM dataset

In [10]:
gb = pc.PancanGbm()

In [11]:
gb.get_clinical(source="mssm")

,tumor_code,discovery_study,discovery_study/type_of_analyzed_samples,consent/age,consent/sex,consent/race,consent/ethnicity,consent/ethnicity_race_ancestry_identified,consent/collection_in_us,consent/participant_country,...,follow-up/additional_treatment_for_new_tumor_radiation,follow-up/additional_treatment_for_new_tumor_pharmaceutical,follow-up/additional_treatment_for_new_tumor_immunological,follow-up/days_from_date_of_initial_pathologic_diagnosis_to_date_of_additional_surgery_for_new_tumor,follow-up/cause_of_death,follow-up/days_from_date_of_initial_pathologic_diagnosis_to_date_of_death,Recurrence-free survival,Overall survial,"Recurrence status (1, yes; 0, no)","Survial status (1, dead; 0, alive)"
Patient_ID,,,,,,,,,,,,,,,,,,,,,
C3L-00016,GBM,No,NaN,60,Male,White,Not-Hispanic or Latino,Caucasian,Yes,Other: TSS did not collect this information,...,NaN,NaN,NaN,NaN,Main malignancy,77.0,NaN,77.0,0,1.0
C3L-00019,GBM,No,NaN,49,Female,White,Not-Hispanic or Latino,Caucasian,Yes,Other: TSS did not collect this information,...,Unknown,Unknown,Unknown,NaN,Main malignancy,958.0,631.0,958.0,1,1.0
C3L-00104,GBM,Yes,Tumor,58,Male,White,Not-Hispanic or Latino,Caucasian,Yes,United States,...,NaN,NaN,NaN,NaN,Unknown,129.0,101.0,129.0,1,1.0
C3L-00265,GBM,No,NaN,68,Male,White,Not-Hispanic or Latino,Caucasian,Yes,Other: TSS did not collect this information,...,Unknown,Unknown,Unknown,NaN,Main malignancy,329.0,286.0,329.0,1,1.0
C3L-00278,GBM,No,NaN,62,Male,White,Not-Hispanic or Latino,Caucasian,Yes,Other: Information not collected at time of co...,...,Unknown,Unknown,Unknown,NaN,Main malignancy,444.0,104.0,444.0,1,1.0
C3L-00349,GBM,No,NaN,57,Female,White,Not-Hispanic or Latino,Caucasian,Yes,United States,...,NaN,NaN,NaN,NaN,Main malignancy,386.0,95.0,386.0,1,1.0
C3L-00365,GBM,Yes,Tumor,59,Female,White,Not-Hispanic or Latino,Caucasian,Yes,United States,...,NaN,NaN,NaN,NaN,Main malignancy,322.0,NaN,322.0,0,1.0
C3L-00424,GBM,No,NaN,74,Female,White,Not-Hispanic or Latino,Caucasian,Yes,United States,...,Unknown,Unknown,Unknown,NaN,Main malignancy,865.0,609.0,865.0,1,1.0
C3L-00429,GBM,No,NaN,82,Male,White,Not-Hispanic or Latino,Caucasian,Yes,United States,...,NaN,NaN,NaN,NaN,Main malignancy,895.0,NaN,895.0,0,1.0
C3L-00506,GBM,No,NaN,61,Male,White,Not-Hispanic or Latino,Caucasian,Yes,Other: TSS did not collect this information.,...,NaN,NaN,NaN,NaN,Main malignancy,212.0,NaN,212.0,0,1.0
C3L-00528,GBM,No,NaN,51,Male,White,Not-Hispanic or Latino,Caucasian,Yes,Other: TSS did not collect this information.,...,Unknown,Unknown,Unknown,NaN,Main malignancy,361.0,258.0,361.0,1,1.0
C3L-00591,GBM,No,NaN,61,Male,White,Not-Hispanic or Latino,Caucasian,Yes,Other: TSS did not collect this information.,...,NaN,NaN,NaN,NaN,Main malignancy,94.0,NaN,94.0,0,1.0
C3L-00631,GBM,No,NaN,65,Male,White,Not-Hispanic or Latino,Caucasian,Yes,Other: TSS did not collect this information.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.0,0,0.0
C3L-00671,GBM,No,NaN,77,Male,White,Not-Hispanic or Latino,Caucasian,Yes,Other: TSS did not collect this information.,...,NaN,NaN,NaN,NaN,Main malignancy,90.0,NaN,90.0,0,1.0
C3L-00674,GBM,Yes,Tumor,45,Male,White,Not-Hispanic or Latino,Caucasian,Yes,Other: TSS did not collect this information.,...,Unknown,Unknown,Unknown,279.0,Main malignancy,478.0,194.0,478.0,1,1.0
C3L-00677,GBM,Yes,Tumor,69,Female,White,Not-Hispanic or Latino,Caucasian,Yes,Other: TSS did not collect this information.,...,NaN,NaN,NaN,NaN,Main malignancy,155.0,NaN,155.0,0,1.0
C3L-01040,GBM,Yes,Tumor,77,Male,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,NaN,NaN,559.0,608.0,1,0.0
C3L-01043,GBM,Yes,Tumor,59,Male,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,Main malignancy,79.0,NaN,79.0,0,1.0
C3L-01045,GBM,Yes,Tumor,73,Female,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,Unknown,66.0,NaN,66.0,0,1.0
C3L-01046,GBM,Yes,Tumor,50,Male,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,Main malignancy,349.0,195.0,349.0,1,1.0
C3L-01048,GBM,Yes,Tumor,60,Male,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,NaN,NaN,216.0,806.0,1,0.0
C3L-01049,GBM,Yes,Tumor,46,Male,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,Main malignancy,191.0,NaN,191.0,0,1.0
C3L-01061,GBM,Yes,Tumor,66,Male,NaN,NaN,Caucasian,No,Russia,...,No,Yes,No,NaN,NaN,NaN,343.0,840.0,1,0.0
C3L-01142,GBM,Yes,Tumor,42,Female,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0.0
C3L-01146,GBM,Yes,Tumor,59,Male,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,Main malignancy,509.0,336.0,509.0,1,1.0
C3L-01149,GBM,Yes,Tumor,48,Male,NaN,NaN,Caucasian,No,Russia,...,Yes,Yes,No,NaN,NaN,NaN,584.0,666.0,1,0.0
C3L-01154,GBM,Yes,Tumor,51,Female,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,Main malignancy,496.0,230.0,496.0,1,1.0
C3L-01155,GBM,Yes,Tumor,66,Male,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,362.0,0,0.0
C3L-01156,GBM,Yes,Tumor,57,Male,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,Main malignancy,291.0,178.0,291.0,1,1.0
C3L-01157,GBM,Yes,Tumor,66,Female,NaN,NaN,Caucasian,No,Russia,...,NaN,NaN,NaN,NaN,Main malignancy,984.0,NaN,984.0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C3N-03755,GBM,No,NaN,68,Male,NaN,NaN,Caucasian,No,Poland,...,Unknown,Unknown,Unknown,NaN,Main malignancy,453.0,133.0,453.0,1,1.0
C3N-03756,GBM,No,NaN,66,Male,NaN,NaN,Caucasian,No,Poland,...,Unknown,Unknown,Unknown,NaN,Main malignancy,290.0,119.0,290.0,1,1.0
C3N-03757,GBM,No,NaN,72,Male,NaN,NaN,Caucasian,No,Poland,...,NaN,NaN,NaN,NaN,Unknown,5.0,NaN,5.0,0,1.0
C3N-03789,GBM,No,NaN,80,Male,NaN,NaN,Caucasian,No,Poland,...,NaN,NaN,NaN,NaN,Main malignancy,310.0,NaN,310.0,0,1.0
C3N-03791,GBM,No,NaN,63,Female,NaN,NaN,Caucasian,No,Poland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
C3N-03792,GBM,No,NaN,38,Male,NaN,NaN,Caucasian,No,Poland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
C3N-03796,GBM,No,NaN,55,Male,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
C3N-03797,GBM,No,NaN,71,Male,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,Main malignancy,231.0,NaN,231.0,0,1.0
C3N-03800,GBM,No,NaN,35,Male,NaN,NaN,Han nationality,No,China,...,No,No,No,NaN,NaN,NaN,NaN,NaN,1,0.0
C3N-03802,GBM,No,NaN,65,Male,NaN,NaN,Han nationality,No,China,...,Unknown,Unknown,Unknown,NaN,NaN,NaN,158.0,364.0,1,0.0
C3N-03810,GBM,No,NaN,78,Male,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,Unknown,24.0,NaN,24.0,0,1.0
C3N-03935,GBM,No,NaN,29,Female,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,Main malignancy,206.0,NaN,206.0,0,1.0
C3N-03939,GBM,No,NaN,48,Female,NaN,NaN,Han nationality,No,China,...,Unknown,Unknown,Unknown,NaN,NaN,NaN,307.0,689.0,1,0.0
C3N-04092,GBM,No,NaN,62,Male,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,712.0,0,0.0
C3N-04094,GBM,No,NaN,39,Male,NaN,NaN,Han nationality,No,China,...,Yes,Yes,No,NaN,Main malignancy,639.0,266.0,639.0,1,1.0
C3N-04097,GBM,No,NaN,71,Male,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,716.0,0,0.0
C3N-04098,GBM,No,NaN,63,Female,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,Main malignancy,440.0,167.0,440.0,1,1.0
C3N-04100,GBM,No,NaN,44,Male,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,719.0,0,0.0
C3N-04113,GBM,No,NaN,31,Male,NaN,NaN,Han nationality,No,China,...,No,Yes,No,NaN,Main malignancy,402.0,277.0,402.0,1,1.0
C3N-04312,GBM,No,NaN,51,Female,NaN,NaN,Han nationality,No,China,...,Unknown,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,1,0.0
C3N-04683,GBM,No,NaN,60,Male,NaN,NaN,Caucasian,No,Poland,...,NaN,NaN,NaN,NaN,NaN,NaN,263.0,336.0,1,0.0
C3N-04686,GBM,No,NaN,58,Male,NaN,NaN,Caucasian,No,Poland,...,Unknown,Unknown,Unknown,NaN,Main malignancy,385.0,149.0,385.0,1,1.0
C3N-04687,GBM,No,NaN,62,Male,NaN,NaN,Caucasian,No,Poland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
C3N-04691,GBM,No,NaN,61,Male,NaN,NaN,Caucasian,No,Poland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
C3N-04693,GBM,No,NaN,54,Female,NaN,NaN,Caucasian,No,Poland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
C3N-04695,GBM,No,NaN,67,Male,NaN,NaN,Caucasian,No,Poland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
C3N-05039,GBM,No,NaN,74,Male,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
C3N-05114,GBM,No,NaN,66,Female,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
C3N-05135,GBM,No,NaN,32,Male,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
C3N-05991,GBM,No,NaN,28,Male,NaN,NaN,Han nationality,No,China,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

In [12]:
gb.get_somatic_mutation(source="washu")

                Gene           Mutation      Location      Database_ID
Patient_ID
C3L-00104       GJB4             Silent        p.R98R  ENST00000339480
C3L-00104     CYP4B1  Missense_Mutation        p.T64M  ENST00000371923
C3L-00104       HFM1  Missense_Mutation       p.L531F  ENST00000370425
C3L-00104      INTS3  Missense_Mutation        p.H86Y  ENST00000318967
C3L-00104     CFAP45  Missense_Mutation       p.R393H  ENST00000368099
C3L-00104      IGFN1  Missense_Mutation      p.A1536T  ENST00000335211
C3L-00104    ZC3H11A  Missense_Mutation        p.D91H  ENST00000545588
C3L-00104       MYCN  Missense_Mutation        p.P44L  ENST00000281043
C3L-00104    C2orf16  Missense_Mutation      p.P1187R  ENST00000408964
C3L-00104    TMEM247  Missense_Mutation       p.Q153R  ENST00000434431
C3L-00104        TTN  Missense_Mutation     p.R12289H  ENST00000589042
C3L-00104      STAT4  Missense_Mutation       p.G618R  ENST00000392320
C3L-00104    C2orf47             Silent       p.T206T  ENST00000295079
C3L-00104       CHPF             Silent       p.F150F  ENST00000243776
C3L-00104     INPP5D  Missense_Mutation       p.S714T  ENST00000445964
C3L-00104        TRH             Silent       p.R134R  ENST00000302649
C3L-00104      TRPC1  Missense_Mutation       p.R512H  ENST00000476941
C3L-00104     LRRIQ4  Missense_Mutation       p.V113I  ENST00000340806
C3L-00104       TFRC  Nonsense_Mutation       p.R698*  ENST00000360110
C3L-00104      CDH18  Missense_Mutation       p.A195T  ENST00000507958
C3L-00104       ESM1  Missense_Mutation       p.V176I  ENST00000381405
C3L-00104    ZFYVE16  Missense_Mutation       p.Q757E  ENST00000338008
C3L-00104   ADAMTS19  Missense_Mutation       p.D610G  ENST00000274487
C3L-00104      KIF4B  Missense_Mutation       p.R652H  ENST00000435029
C3L-00104    C1QTNF2  Missense_Mutation       p.R149W  ENST00000393975
C3L-00104      RAB24       In_Frame_Del      p.Y78del  ENST00000303251
C3L-00104      FOXF2       In_Frame_Del      p.A41del  ENST00000259806
C3L-00104   C6orf132             Silent       p.D923D  ENST00000341865
C3L-00104     NKAIN2  Missense_Mutation        p.V47I  ENST00000368417
C3L-00104     UNC93A  Missense_Mutation       p.S156L  ENST00000230256
...              ...                ...           ...              ...
C3N-03473     OR51I1  Nonsense_Mutation       p.R167*  ENST00000380211
C3N-03473      FANCF             Silent        p.A57A  ENST00000327470
C3N-03473     CLECL1  Missense_Mutation        p.Y50N  ENST00000621400
C3N-03473    TAS2R31             Silent       p.S220S  ENST00000390675
C3N-03473    TAS2R31             Silent       p.G213G  ENST00000390675
C3N-03473       GLI1  Missense_Mutation       p.P147L  ENST00000228682
C3N-03473      PTPRQ  Missense_Mutation      p.P1644L  ENST00000614701
C3N-03473    GOLGA8K  Missense_Mutation       p.K328N  ENST00000512626
C3N-03473        AQR  Missense_Mutation       p.M677L  ENST00000156471
C3N-03473     RNF111  Missense_Mutation       p.E333G  ENST00000559209
C3N-03473      MYO1E  Missense_Mutation       p.S912G  ENST00000288235
C3N-03473      MYO9A  Missense_Mutation      p.V1875M  ENST00000356056
C3N-03473    GOLGA6B  Missense_Mutation       p.D563E  ENST00000421285
C3N-03473       TP53       In_Frame_Ins     p.A161dup  ENST00000269305
C3N-03473        NF1    Frame_Shift_Del  p.P1712Lfs*8  ENST00000358273
C3N-03473   KRTAP2-2  Missense_Mutation       p.S122P  ENST00000398477
C3N-03473      DHX40  Nonsense_Mutation       p.Q745*  ENST00000251241
C3N-03473       WDR7  Missense_Mutation        p.G89R  ENST00000254442
C3N-03473      PLIN3  Missense_Mutation       p.T154I  ENST00000221957
C3N-03473     PNPLA6  Missense_Mutation       p.L940V  ENST00000414982
C3N-03473   KIAA1683             Silent      p.Q1323Q  ENST00000392413
C3N-03473     SUPT5H  Missense_Mutation      p.M1067V  ENST00000599117
C3N-03473     ZNF135             Silent        p.D30D  ENST00000401053
C3N-03473     ZNF837  Missense_Mutation       p.Y347C  ENST00000427624
C3N-03473       RALY             Silent       p.G235G  ENST00000246194
C3N-03473       OGFR             Silent       p.S637S  ENST00000290291
C3N-03473       CBR1  Missense_Mutation       p.S158N  ENST00000399191
C3N-03473       SUN2             Silent       p.Q389Q  ENST00000405018
C3N-03473    DCAF8L2             Silent       p.E129E  ENST00000451261
C3N-03473     DOCK11             Silent       p.D292D  ENST00000276202

[6859 rows x 4 columns]

In [13]:
gb.get_proteomics(source="umich")

Proteins,ARF5-201,M6PR-201,ESRRA-201,FKBP4-201,NDUFAF7-201,FUCA2-201,DBNDD1-201,HS3ST1-201,CYP51A1-201,USP28-201,...,ETNK1-207,AP1S2-209,EED-213,DDHD1-211,WIZ-210,ZBTB3-204,CTNND1-240,WIZ-212,WIZ-211,MSANTD2-209
Database_ID,ENSG00000004059.11,ENSG00000003056.8,ENSG00000173153.16,ENSG00000004478.8,ENSG00000003509.16,ENSG00000001036.14,ENSG00000003249.14,ENSG00000002587.10,ENSG00000001630.17,ENSG00000048028.11,...,ENSG00000139163.16,ENSG00000182287.15,ENSG00000074266.21,ENSG00000100523.16,ENSG00000011451.21,ENSG00000185670.9,ENSG00000198561.15,ENSG00000011451.21,ENSG00000011451.21,ENSG00000120458.12
Patient_ID,,,,,,,,,,,,,,,,,,,,,
C3L-00104,-0.254733,-0.138938,0.662227,-0.074868,0.213529,0.123398,2.105458,NaN,-0.660264,NaN,...,-0.047874,-0.446007,0.070101,0.160090,0.129282,-0.166678,NaN,-0.073448,-0.029020,-0.009463
C3L-00365,-0.138512,-0.824520,0.494419,0.043783,-0.001394,0.101477,-0.287232,NaN,-0.402679,0.059975,...,0.350165,-0.844985,-0.234406,-0.448783,0.078407,NaN,-0.174780,1.806950,0.033808,0.180578
C3L-00674,-0.351464,-0.120197,-0.084371,-0.260275,0.096193,-0.360274,0.227499,1.217058,-0.165751,0.010124,...,-0.167319,-0.096328,-0.118506,-0.107690,0.177530,NaN,-1.513869,0.065973,-0.126149,0.465241
C3L-00677,-0.062869,0.094198,0.391070,-0.030638,0.742258,-0.417291,-0.013377,NaN,-0.176649,0.535304,...,0.179200,0.320945,-0.027522,0.104278,0.049948,-0.590267,0.162686,1.964570,0.161229,0.283810
C3L-01040,-0.365351,0.070523,-0.472543,-0.255288,0.096844,0.356271,1.182940,NaN,-0.307430,NaN,...,0.098253,-0.298907,-0.201144,0.440215,0.110757,0.119013,NaN,0.030719,0.066426,0.189187
C3L-01043,-0.296915,-0.121120,0.349955,-0.201174,-0.301029,0.272775,-0.254472,0.498575,-0.058460,0.086761,...,-0.146274,-0.354115,0.191354,-0.151167,0.438022,NaN,0.675351,-0.179301,0.155335,-0.760272
C3L-01045,0.037365,-0.652065,-0.248141,0.145521,-0.073741,-0.162454,-1.333221,NaN,-0.374376,0.015935,...,0.261996,0.051746,0.150032,-0.312733,0.299914,-0.400663,-0.094606,-0.390488,0.379908,0.008441
C3L-01046,0.075397,0.932390,-0.110516,0.125232,-0.342554,0.701215,-0.495910,NaN,-0.550261,-0.405572,...,0.309600,-0.007910,0.285477,-0.187945,-0.072374,0.111980,-0.438993,-0.455245,-0.164979,-0.387779
C3L-01048,-0.809921,-0.132927,0.403992,0.138070,0.187086,-0.263908,-0.112388,NaN,-0.077567,0.612077,...,-0.072298,-0.288726,0.376594,-0.673635,0.818728,NaN,0.232682,NaN,0.651938,-0.191747
C3L-01049,-0.073592,0.154447,0.385628,-0.374305,-0.241636,-0.265848,0.033910,NaN,-0.321705,0.346103,...,-0.359241,0.068796,0.238774,-0.217781,0.150427,NaN,0.160344,0.001668,-0.043049,-0.023743
C3L-01061,0.195500,-0.093353,-0.076683,0.222654,-0.286970,0.247622,-0.667056,NaN,-0.156916,0.495731,...,-0.103860,-0.022540,0.523047,-0.148672,0.324514,0.420138,-0.154209,1.001468,0.461304,0.713793
C3L-01142,0.039818,0.848821,0.376597,-0.329539,-0.253951,0.729904,-0.316134,-0.280422,-0.548638,-0.336841,...,0.157190,-0.158725,0.297600,-0.277240,-0.387274,NaN,NaN,NaN,-0.079697,-0.445445
C3L-01146,0.058449,0.375033,0.036588,-0.155265,0.115347,0.484253,-0.646302,NaN,0.063165,0.055944,...,0.370384,-0.582026,-0.186043,0.188773,-0.354163,NaN,0.163083,1.155492,0.018329,-0.513017
C3L-01149,0.467881,-1.033795,0.164904,0.460692,-0.599365,-0.628689,-0.432942,NaN,0.787325,0.537804,...,-0.192741,0.529849,1.453963,0.584889,0.824042,NaN,-0.515116,NaN,0.949597,1.555530
C3L-01154,-0.424295,-0.335194,0.635142,0.147765,0.300076,-0.194094,-0.228594,0.011131,0.871137,0.152322,...,0.367889,-0.520772,0.314114,-0.026901,0.489185,NaN,-0.001332,-0.185902,0.419211,-0.429364
C3L-01155,-0.306358,-0.001856,-0.210825,-0.050743,-0.251650,0.004916,-0.640702,NaN,0.434821,-0.245204,...,0.197593,-0.119304,-0.081883,-0.247221,0.278940,-0.406632,-0.123104,-0.590180,0.069879,-0.425754
C3L-01156,0.017820,-0.175184,0.448434,-0.039553,0.067837,0.261851,0.027918,0.271985,0.131603,-0.109775,...,0.334958,-0.198398,0.174635,0.155041,0.604966,NaN,0.160413,-0.474287,0.324242,-0.497908
C3L-01157,0.116051,0.194086,NaN,0.092211,0.490424,0.091329,NaN,NaN,-0.235308,-0.166935,...,0.729013,0.096771,-0.640891,0.209138,-0.040612,-0.517089,-0.015771,NaN,-0.176485,-0.411197
C3L-01327,-0.088488,-0.259715,-1.568652,-0.280720,-0.422410,0.430665,0.051991,NaN,0.729728,NaN,...,-0.199711,0.172573,0.111401,0.330391,0.612934,-0.244005,NaN,0.303869,0.498298,0.339925
C3L-01834,-0.071885,0.382744,0.074689,-0.198975,-0.011925,0.207927,-0.008193,-0.230498,0.005737,-0.479846,...,0.133363,0.178145,-0.385880,0.301103,-0.125794,NaN,NaN,NaN,-0.615722,1.011381
C3L-01887,0.226508,-0.301702,-0.332930,0.077876,-0.218744,-0.359847,-0.854939,NaN,0.107656,0.100704,...,0.151363,-0.387502,0.111161,0.387771,0.298271,0.102184,-0.156283,0.328777,0.307452,0.068919
C3L-02041,0.118651,0.135916,-0.060936,-0.247142,0.200839,-0.779658,-0.604690,NaN,0.219757,-0.537532,...,0.269065,-0.135222,-0.030324,-0.290140,0.249499,-0.245850,-0.283335,-1.578704,-0.033233,-0.430901
C3L-02465,-0.328672,0.111913,0.517635,-0.579118,0.201872,0.114817,1.757479,NaN,0.096507,0.354253,...,-0.234399,0.346629,0.256416,-0.117552,0.233708,NaN,0.360525,2.270704,-0.057725,-0.193419
C3L-02504,-0.072128,0.102169,NaN,-0.143781,0.257018,0.181408,NaN,NaN,0.921222,-0.042350,...,0.364012,-0.031721,-0.040483,-0.043329,0.145034,-0.310105,0.163795,NaN,0.054795,-0.242727
C3L-02542,0.226266,-0.233895,0.248783,0.255449,-0.287202,-0.283780,-0.324609,-0.123232,0.088920,0.909821,...,0.564724,0.157823,0.828590,0.145015,0.366048,NaN,NaN,NaN,1.196000,-0.160228
C3L-02642,0.218517,0.047269,0.038258,0.152076,-0.011150,0.113180,1.500001,NaN,-0.182353,0.005948,...,0.217283,-0.539332,-0.132773,-0.037885,0.108123,NaN,-0.037155,-0.285280,-0.228893,-0.210767
C3L-02704,-0.158347,0.054803,-0.246850,-0.412166,0.307915,-0.127380,1.842530,NaN,0.405042,-0.154385,...,-0.120770,0.237707,0.151404,-0.392590,-0.312354,0.219740,0.461932,-0.635756,-0.338009,0.157698
C3L-02705,-0.099136,-0.098765,NaN,-0.224959,0.049156,0.568741,NaN,NaN,-0.287233,0.160394,...,-0.119680,0.186758,-0.118977,0.233310,-0.101840,0.444416,-0.605758,NaN,-0.108076,1.064252
C3L-02707,-0.197955,0.307897,-0.362173,-0.069830,-0.204913,-0.158539,0.308918,NaN,0.708532,0.274853,...,0.276380,0.025022,0.278910,0.081037,0.385542,NaN,0.076155,NaN,0.483812,0.206541
C3L-02708,-0.711202,0.256755,0.160964,0.344593,-0.292894,-0.529228,-0.889686,NaN,0.440707,0.490824,...,0.115810,-0.859148,0.238630,0.048074,0.305612,NaN,0.644263,1.235773,0.357002,-0.314114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C3N-02190,-0.204737,0.031836,-0.378435,-0.004006,-0.197042,0.586210,0.883769,NaN,0.012009,NaN,...,-0.014197,-0.249205,0.064008,-0.204739,0.075912,-0.525817,NaN,-0.393086,-0.146220,-0.130251
C3N-02255,-0.014327,-0.094733,-0.349561,0.041856,-0.128255,-0.562981,0.098591,NaN,-0.266051,0.618477,...,-0.323677,0.160792,0.303077,-0.040812,0.554372,-0.021867,0.044699,-0.095654,0.415426,-0.280775
C3N-02256,0.254615,0.086528,-0.253850,0.055832,-0.165004,0.217262,-0.560240,0.215375,0.528205,0.472208,...,-0.136804,0.361955,0.075944,0.112640,-0.434942,NaN,NaN,NaN,0.124421,0.087817
C3N-02769,-0.092131,0.269468,0.624829,0.617111,-0.066061,0.637723,0.859363,NaN,0.017118,NaN,...,0.040998,-0.266950,0.285162,-0.673656,-0.330238,-0.628220,NaN,0.024512,-0.215318,0.006963
C3N-02770,0.008565,0.058057,0.215223,-0.057971,-0.290736,0.334405,-0.102434,NaN,-0.023254,0.024053,...,0.128707,-0.132366,0.228712,0.084642,0.009960,NaN,0.368780,1.059733,0.180486,-0.605426
C3N-02782,0.068108,-0.130065,0.046787,-0.261749,0.193390,0.635310,0.177402,NaN,-0.669642,0.403675,...,-0.314032,-0.509500,0.268924,-0.292713,-0.057830,NaN,0.016174,NaN,0.045271,0.032373
C3N-02783,-0.202526,-0.058455,0.137057,-0.136958,-0.111224,0.159641,-0.055572,NaN,-0.404692,-0.143945,...,-0.157400,-0.401099,0.023957,-0.065925,-0.365450,NaN,0.604738,-0.261794,-0.244611,-0.664694
C3N-02784,0.319160,1.043916,0.547246,0.383208,-0.293071,0.391145,0.729985,NaN,-0.239193,0.349129,...,0.247480,-0.375627,0.018981,-0.027585,-0.071303,NaN,0.280948,NaN,-0.287881,-0.388208
C3N-02785,0.251502,-0.721134,0.312589,-0.347553,-0.103641,0.391114,1.253767,NaN,-0.138662,NaN,...,-0.034031,0.174119,0.043091,0.493288,0.453680,-1.221920,NaN,-0.804280,0.148429,0.312440
C3N-02786,-0.259304,0.118967,-0.060580,-0.290382,-0.070291,0.601931,1.976235,NaN,-0.624648,NaN,...,0.036471,0.409508,0.171008,-0.469099,0.332007,0.935777,NaN,0.385656,0.173467,-0.230561
C3N-02788,-0.001656,0.435131,NaN,0.078457,-0.256089,0.062334,NaN,NaN,-0.197630,0.163148,...,0.510302,-0.001186,-0.489737,0.292660,-0.017434,-0.630744,-0.274256,NaN,-0.329260,-0.459188
C3N-03070,-0.160401,0.026234,-0.057032,0.087701,0.167558,-0.196184,-0.121520,NaN,0.603406,0.952899,...,0.006647,-0.302369,0.461222,-0.067969,0.569395,0.241440,0.331152,0.658551,0.578626,0.056973
C3N-03088,-0.107743,0.199141,-0.561571,0.286415,-0.393140,0.030594,-0.496270,NaN,-0.148824,-0.362965,...,0.275977,0.041051,-0.223532,0.068185,-0.390092,-0.111504,-0.126027,-0.749545,-0.397753,-0.428512
C3N-03180,-0.130936,0.064589,NaN,-0.141754,0.064870,0.390338,0.240088,NaN,-0.479353,NaN,...,0.380485,0.192508,-0.057043,0.323123,0.250108,-0.162129,-0.225863,NaN,-0.408853,NaN
C3N-03182,0.139063,1.957716,0.913632,-0.235950,0.079570,0.731875,0.378458,NaN,-0.248442,-0.029566,...,0.650516,-0.059490,0.709414,0.070472,-0.329072,NaN,-0.644034,NaN,0.001174,0.015695
C3N-03183,-0.154099,0.377664,0.230259,-0.160996,-0.345147,0.098204,-0.307796,0.540155,0.365869,0.093833,...,-0.053077,-0.744983,0.661918,-0.397211,-0.136850,NaN,NaN,NaN,0.565946,-0.232044
C3N-03184,0.189578,-0.307571,NaN,0.223307,-0.245702,0.015862,-0.014366,NaN,0.366511,NaN,...,0.141587,0.198692,0.379313,0.257048,0.669888,0.134818,-0.042240,NaN,0.841351,NaN
C3N-03186,0.216536,0.206218,-0.002028,-0.027721,0.022376,0.116589,0.412767,NaN,-0.088390,0.131931,...,0.095028,-0.032430,-0.350445,-0.037268,-0.609430,NaN,-0.274836,NaN,-0.345816,0.383632
C3N-03188,0.020677,0.004811,-0.041030,-0.099233,-0.063813,-0.250591,-0.145725,-0.562148,0.194367,-0.406621,...,0.062744,-0.007752,-0.219871,0.271077,-0.312438,NaN,NaN,NaN,-0.199850,0.252781
C3N-03473,-0.133481,0.127108,-0.305324,-0.466174,0.131691,0.606351,0.279502,NaN,1.232326,0.290813,...,0.155784,0.214643,0.543383,-0.248307,0.943688,NaN,0.599462,0.270782,0.901456,0.641179
PT-NPJ7.N,0.853669,0.096660,0.331398,0.644892,0.794698,-0.473205,0.288278,NaN,-0.805937,NaN,...,0.438269,-0.021498,-1.156977,0.019995,-1.319338,-0.708249,NaN,-1.096315,-0.802929,0.107154
PT-P44H.N,0.608744,0.339780,-0.866016,0.386414,0.682696,-0.478468,1.280812,NaN,-0.550694,-0.344151,...,0.331727,-0.736672,-1.275744,1.180474,-1.052908,NaN,-0.880557,NaN,-0.995743,-0.150876
PT-Q2AG.N,0.835498,0.308499,NaN,0.492248,0.839400,-0.740021,1.099211,NaN,-0.647795,NaN,...,0.272638,-0.300019,-0.729070,-0.217652,-0.382997,0.484012,0.241854,NaN,-0.874509,NaN
PT-QVJO.N,0.678082,0.123010,0.405192,0.438089,0.913204,-1.102735,1.275032,-0.683650,-0.482490,-0.488447,...,0.397129,-0.374862,-0.653561,1.132336,-1.298568,NaN,-0.252852,-0.261842,-0.873189,-0.441830
PT-R55F.N,0.994064,0.224522,0.013390,0.549045,0.784263,-0.831754,0.868204,NaN,-0.729177,-0.178067,...,0.060445,0.750589,-0.665833,1.201341,-0.882499,NaN,-0.650111,NaN,-1.231861,0.387622
PT-RN5K.N,0.582456,-0.356730,0.236333,0.658617,0.719931,-0.760723,1.562912,NaN,-1.158580,-0.247034,...,-0.183210,-0.723977,-0.339088,0.973199,-0.753209,0.211861,-0.539658,NaN,-0.530017,0.614323
PT-RU72.N,0.522376,0.226891,-1.059051,0.558740,0.893739,-0.383723,1.652233,NaN,-0.649935,-0.504037,...,0.237765,-0.559902,-0.849461,1.305892,-0.706170,NaN,-0.597932,-1.889779,-0.492358,-0.534980
PT-UTHO.N,0.595553,0.194616,-0.045162,0.546508,0.810285,-0.868148,0.721085,NaN,-0.840286,-0.267181,...,0.018208,0.813018,-0.029398,1.355047,-0.600093,NaN,0.066284,-0.095237,-0.286616,-0.090284
PT-WVLH.N,0.958226,-0.057340,NaN,0.635282,1.143518,-1.243729,NaN,NaN,-0.185783,-0.402786,...,0.151603,0.380411,-0.758021,0.753353,-0.712901,-0.899465,-0.510523,NaN,-1.241097,0.191439
PT-Y8DK.N,0.614902,0.031155,0.201446,0.488837,0.963876,-1.368573,0.002088,-0.020131,-0.719916,-0.509412,...,0.081186,0.901674,-0.681082,1.120526,-0.660408,NaN,NaN,NaN,-1.415793,1.562810

### PDC data

Again, we can also access data from the PDC.

In [14]:
gb.get_proteomics(source="pdc")

,A1BG,A2M,AAAS,AACS,AADAT,AAGAB,AAK1,AAMDC,AAMP,AAR2,...,ZSCAN30,ZSWIM8,ZSWIM9,ZW10,ZWILCH,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
Patient_ID,,,,,,,,,,,,,,,,,,,,,
C3L-00104,-0.0412,0.2351,0.0018,-0.0782,0.6141,-0.5695,-0.2805,-0.0976,0.4308,-0.1302,...,-0.0777,0.0708,NaN,0.0331,-0.1518,0.2459,0.1174,-0.5401,-0.3311,0.0216
C3L-00365,0.1100,0.4324,0.2045,-0.6951,NaN,0.1336,-0.5245,0.2489,-0.0067,0.4826,...,-0.7589,0.0291,0.0221,-0.0563,-0.0431,0.1388,0.0138,0.2734,-0.0970,0.6415
C3L-00674,0.4574,0.7025,0.0951,-0.2422,0.0728,0.1744,-0.0725,-0.4614,-0.3170,0.7040,...,-1.8613,-0.1603,NaN,-0.0329,0.5709,1.0894,-0.1988,-0.0169,0.0546,-0.7543
C3L-00677,0.0359,-0.0541,0.1592,-0.1692,-0.0839,0.1231,-0.3932,-0.0069,-0.1932,0.3875,...,-0.7534,0.0013,-0.5398,0.7096,0.5303,-0.2298,-0.0150,-0.3959,0.0213,0.0031
C3L-01040,-0.4924,-0.7171,0.0256,-0.4839,0.3248,-0.1811,-0.0003,-0.2387,0.4863,0.1916,...,0.3235,0.3242,NaN,0.0855,0.0022,0.2235,0.1236,0.5120,-0.1241,0.0955
C3L-01043,0.5746,0.4742,0.0008,-0.2919,-0.5499,-0.0724,-0.6506,-0.4407,0.1085,0.0791,...,-0.1640,0.0271,NaN,0.1854,0.0169,0.9953,-0.2001,0.1446,-0.0489,0.1199
C3L-01045,-0.1602,-0.7021,0.1348,-0.4426,-0.4586,0.3336,-0.4428,-0.6044,0.3000,0.7785,...,0.0620,0.0259,-0.5831,0.3949,0.1252,-0.0414,-0.2385,0.5104,-0.1324,0.4366
C3L-01046,-0.2839,-0.2529,0.2834,-0.0450,-0.7014,-0.0970,-0.5152,-0.0763,0.2069,-0.0784,...,-0.0450,0.0601,-0.9499,0.2647,0.5852,-0.3080,-0.0703,0.4721,0.2618,0.1319
C3L-01048,-0.4551,-0.5562,0.1733,0.0855,-0.3963,-0.1499,-0.9422,0.3944,0.9240,0.1669,...,0.9799,-0.0099,0.5277,0.2164,-0.0449,0.2460,-0.1248,-0.3690,0.0820,0.5333
C3L-01049,-0.1281,-0.3739,0.1697,-0.2256,NaN,0.1728,-0.6502,-0.2878,-0.0492,0.2939,...,0.1417,0.0425,NaN,0.1614,0.6269,0.0973,-0.4103,0.0244,-0.0753,0.3873
C3L-01061,-0.1379,-0.0096,0.2052,-0.1722,-0.1227,-0.1052,-0.6248,0.4693,0.4139,0.4174,...,0.3480,0.1788,-0.1096,0.5525,0.3001,0.5103,-0.5195,0.8202,0.1787,0.2945
C3L-01142,-0.0526,-0.8938,0.3095,-0.5168,-0.3486,0.1989,-0.2933,0.3603,0.0948,0.2474,...,-0.0818,0.3050,2.5108,0.1917,-0.1415,-1.0270,-0.7281,0.9966,0.1754,0.1914
C3L-01146,-0.0615,-0.4338,0.2698,0.0787,NaN,0.0634,0.1162,-0.7679,0.0655,0.0461,...,-0.2535,0.1003,0.2784,0.1564,-0.2409,-0.2242,0.0773,0.3071,-0.0870,0.1390
C3L-01149,-0.7420,-0.8158,0.1645,-0.1851,1.6591,0.3563,-0.1308,-1.3417,-0.3408,0.6284,...,1.2331,-0.1250,0.8960,0.5396,2.8849,0.4764,0.9423,-0.5604,0.0140,0.7510
C3L-01154,-0.7343,-0.4650,0.4220,-0.4125,-0.6538,-0.2877,-0.9590,0.6112,0.2816,0.0680,...,0.3502,-0.0577,NaN,-0.0517,-0.6890,-0.1211,0.1150,-0.0023,-0.1155,-0.0086
C3L-01155,-0.4686,-0.8221,0.0463,-0.4123,-0.2380,-0.1426,-0.2197,-0.0386,0.3990,0.2305,...,0.2094,0.0425,-0.5921,0.3731,-0.8430,0.0058,-0.0724,0.0606,0.0161,0.1696
C3L-01156,-0.8463,-0.8980,0.2636,0.1236,-0.4918,0.0201,-0.1554,0.2909,0.0799,-0.3646,...,0.1904,-0.1201,NaN,0.2146,-0.1535,-0.6048,-0.0347,0.2315,0.0389,0.0087
C3L-01157,-0.1141,0.3860,-0.0523,0.0063,-0.0437,0.1769,0.7515,0.2583,-0.1165,-0.2475,...,-0.2949,0.1202,NaN,0.2457,-0.2365,0.1112,0.3355,0.1987,0.2210,NaN
C3L-01327,0.0469,-0.0326,0.3581,-0.1217,0.1058,-0.2207,-0.4261,-0.0196,-0.1240,0.3969,...,-0.1476,0.0647,NaN,-0.0526,0.5885,0.1921,0.0757,0.2751,-0.0480,0.1725
C3L-01834,0.9550,1.1241,-0.3338,-0.0169,0.2077,0.3503,0.2841,0.5882,-0.1865,-0.1031,...,-0.6983,-0.0192,0.4946,0.2076,-0.8702,0.2520,-0.1865,-0.4363,0.2723,0.1597
C3L-01887,-0.2726,-0.2069,0.0464,0.3115,-0.0369,-0.0419,0.3921,-0.7712,0.1357,0.1583,...,-0.1043,0.0617,0.3495,-0.0751,0.0566,-1.1425,0.1760,0.0203,-0.5837,0.3110
C3L-02041,-0.1047,-0.1720,-0.0822,-0.4056,-0.1498,-0.3407,-0.1419,0.5144,-0.2502,0.0572,...,0.1570,0.2216,-0.4179,0.0058,-0.5834,-0.0539,-0.3712,-0.0447,0.1074,0.1954
C3L-02465,0.5118,0.1699,-0.0742,0.1943,NaN,0.3802,-0.3197,0.0279,-0.0515,0.2645,...,-2.1685,0.0209,NaN,-0.0245,0.2042,0.0715,0.0074,0.1778,-0.0329,0.4510
C3L-02504,0.5992,0.0167,0.1825,-0.3069,-0.0656,-0.0418,-0.7170,-0.2335,-0.0210,0.1170,...,-0.3604,0.1675,NaN,0.2628,0.0294,-0.0781,0.0362,0.1174,0.2417,NaN
C3L-02542,-0.0135,-0.2289,0.4893,0.0388,0.3966,0.6464,-0.5881,0.5927,0.2482,0.1941,...,0.7220,0.0205,0.9898,0.1847,1.2491,-0.8437,0.3230,0.0780,-0.3601,0.5814
C3L-02642,-0.3390,-0.3237,0.1536,0.1603,NaN,0.3237,0.1876,0.0703,0.6579,0.0956,...,-0.0089,-0.0959,NaN,0.0558,-0.4051,-0.1675,0.3205,-0.8414,-0.1089,0.2184
C3L-02704,-0.2394,-0.1946,0.0192,0.0751,0.2332,0.0890,-0.2393,0.8936,0.1708,0.0735,...,-0.1247,0.2644,-0.0758,0.3048,-0.4640,-0.9948,0.1337,0.1440,0.1137,-0.4938
C3L-02705,0.9919,0.6309,-0.0326,0.2481,-0.2630,0.1484,-0.2983,0.0571,0.0677,0.2468,...,-4.5381,0.3695,NaN,0.2866,0.0153,-0.4585,0.0928,0.1507,0.1324,NaN
C3L-02707,-0.1976,-0.2548,0.2516,-0.4166,-0.0795,-0.0918,-0.3218,-0.3794,0.1800,0.3702,...,-0.2284,0.0749,NaN,0.0096,-0.0365,-0.4237,0.4763,-0.0269,-0.1150,0.0323
C3L-02708,0.1464,0.1917,0.3837,-0.4943,NaN,0.2590,-0.4994,0.1070,0.3650,0.5510,...,-0.3771,0.2091,0.2370,0.2964,0.0656,0.4540,-0.0646,-0.1653,0.2202,0.0651
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C3N-02190,0.5042,0.5533,0.2113,0.0536,-0.1004,0.0557,-0.4002,0.0252,0.1904,0.2473,...,-0.2940,0.0603,NaN,0.0399,0.7259,0.2478,0.0023,0.3555,0.1140,-0.1585
C3N-02255,-0.3272,-0.2908,0.1271,-0.2790,-0.0887,0.1005,0.1659,0.2684,0.5293,0.2146,...,0.2094,0.1899,-0.3400,0.0017,0.7439,0.3803,-0.1483,-0.7747,0.0597,0.0824
C3N-02256,-0.5855,-0.1721,0.1684,0.0905,0.1539,0.0788,0.0236,0.4020,-0.3676,0.0160,...,0.3408,-0.0860,0.7860,0.0901,0.0872,-0.3163,0.1972,-0.2962,0.2669,0.3248
C3N-02769,0.7625,0.4452,0.0821,0.1397,0.2253,0.1864,-0.3720,0.0880,0.1605,0.1867,...,-0.2004,0.0237,NaN,0.4569,0.5795,0.2662,-0.1292,-0.1434,0.0770,-0.1704
C3N-02770,0.3220,0.3048,0.1876,0.3615,NaN,0.0704,0.1623,0.0371,0.2318,0.2176,...,-0.0358,0.3986,0.0813,0.0266,0.2847,0.2424,-0.1322,-0.0064,0.0470,0.2703
C3N-02782,0.1014,-0.2307,0.4867,-0.0623,-0.6618,-0.6365,-0.8098,0.7115,0.1074,0.1950,...,0.1123,-0.0219,0.2918,0.2826,-0.0903,-0.0484,0.0496,0.5615,0.0793,0.4773
C3N-02783,0.7358,0.9328,-0.1366,-0.1814,NaN,-0.4480,-0.0388,0.5143,-0.0828,0.0460,...,-0.4096,0.2247,-0.1625,-0.2465,-0.6866,0.2580,-0.3131,0.0725,0.0963,0.0296
C3N-02784,-0.1859,0.0824,0.1417,0.1647,-0.3762,0.0688,-0.5036,0.9275,-0.2581,0.0182,...,-0.3803,0.4541,NaN,0.2913,0.5565,0.1336,-0.3212,0.3815,0.4424,-0.2639
C3N-02785,0.7971,0.7627,0.1086,0.1516,0.0999,0.1644,0.0135,-0.0927,-0.9553,0.0871,...,-2.4175,0.2232,NaN,0.1745,0.9259,-1.3575,-0.0445,-0.0183,-0.0596,-0.2976
C3N-02786,0.7312,0.9127,0.4048,0.1626,-0.1560,-0.0831,-0.6397,0.2172,-0.3169,0.2752,...,-0.0466,0.4488,NaN,-0.1641,1.1340,0.0794,-0.2992,-0.2033,-0.3392,0.1255
C3N-02788,-0.3108,-0.3831,-0.3228,0.3334,0.2342,-0.1599,0.5640,0.4110,-0.1321,-0.4900,...,-0.2918,0.2474,NaN,0.0189,-0.7551,0.0154,-0.0876,-0.6301,0.1574,NaN
C3N-03070,1.0726,1.0800,0.1013,-0.6950,0.4130,-0.2849,-0.2551,-0.0783,0.1704,-0.0640,...,0.4169,0.1140,0.0028,-0.0068,0.1525,-0.0677,-0.1515,-0.4425,-0.0069,0.2713
C3N-03088,0.0826,0.4443,-0.2594,0.1212,-0.1155,-0.1482,0.3582,0.2736,-0.0554,-0.0406,...,-0.1910,0.0334,-0.1580,-0.0397,-0.7405,-0.1575,-0.2216,0.0676,0.1158,0.0473
C3N-03180,0.8862,1.0666,0.1494,-0.0631,0.0919,-0.1063,0.1367,-0.0709,-0.1153,0.1580,...,-0.8806,0.1915,-0.3065,-0.0544,NaN,-2.4101,-0.0776,-0.0022,0.1128,-0.4017
C3N-03182,-0.1262,-0.5988,0.3122,0.4887,0.2111,0.5089,-0.5833,-0.5140,-0.0688,-0.1418,...,0.0161,0.2751,NaN,0.1284,0.8629,-0.0904,-0.1758,-0.0043,0.2238,0.0894
C3N-03183,0.0253,0.1561,0.4718,0.2856,-0.4973,0.3126,-0.6225,0.2698,0.2854,0.1190,...,0.3632,0.0129,1.0918,0.0178,-0.0916,-0.4574,0.1104,-0.4377,-0.1030,0.4357
C3N-03184,-0.2970,-0.4310,0.6517,-0.0205,-0.5190,-0.0652,-0.8227,0.3744,0.2898,0.8560,...,-0.0216,0.1134,0.9259,0.2268,NaN,1.2752,0.3130,0.5066,-0.0869,0.0531
C3N-03186,0.6154,0.7272,-0.2371,0.0269,0.1185,0.1833,0.1886,0.0761,0.1390,-0.0704,...,-1.0173,-0.1462,NaN,-0.0409,-0.2750,-1.3919,0.0725,-0.0144,0.2242,-0.4665
C3N-03188,-0.2067,-0.6024,-0.1256,-0.1833,-0.1748,0.2138,0.1122,-0.4706,-0.3974,-0.3183,...,-0.1757,0.1094,0.8442,-0.0737,-0.4489,-0.4663,0.6034,0.0316,-0.1261,-0.1364
C3N-03473,-0.6613,-0.4512,0.5611,-0.6204,NaN,0.4215,-0.0912,0.6745,0.3417,0.3006,...,1.1626,0.2426,NaN,0.1201,0.6896,0.2060,-0.4113,-0.0173,-0.1678,0.4016
GTEX-NPJ7-0011-R10A-SM-HAKXW,-0.8167,-0.8034,-0.2781,0.2885,1.2131,0.0666,1.2521,-0.6212,0.3271,-0.6085,...,-0.5842,0.3661,NaN,-0.0079,-1.4455,-1.7444,0.4844,-0.7691,0.3277,-0.0538
GTEX-P44H-0011-R10A-SM-HAKXX,-0.8302,-0.6031,-0.4098,0.5447,1.3426,0.1170,1.3148,-0.2345,0.1696,-0.5431,...,-1.7869,0.4884,NaN,-0.0245,-1.0024,0.3862,0.6409,-0.6243,0.2459,-0.1921
GTEX-Q2AG-0011-R10A-SM-HAKXT,-0.9277,-1.2591,-0.8341,0.8390,1.0885,0.1581,1.6963,-0.4204,0.2580,-0.4686,...,-2.0587,0.2939,0.5175,0.0414,NaN,NaN,0.7135,-0.6987,0.1604,-0.4159
GTEX-QVJO-0011-R10A-SM-HAKXV,-0.9955,-1.1662,-0.6575,0.9911,1.5267,0.3757,1.6649,-0.1661,0.2167,-1.2674,...,-1.1108,0.4116,NaN,-0.0566,-0.8513,-1.9144,0.6768,-0.7589,0.5011,-0.8849
GTEX-R55F-0011-R10A-SM-HAKXY,-1.0791,-1.4838,-0.6528,0.8299,1.5410,0.1628,1.6511,-0.3299,0.1712,-1.2006,...,-1.7655,0.3344,0.0539,-0.1155,-0.8962,0.2103,0.6879,-0.7979,0.2982,-0.1087
GTEX-RN5K-0011-R10A-SM-HAKXU,-0.9587,-0.7611,-0.4379,0.5353,0.5673,0.2507,1.3618,0.1173,0.4544,-0.5759,...,-0.2575,0.3295,-0.3002,-0.2672,-0.7662,0.5055,0.6198,-0.6233,0.2716,0.4841
GTEX-RU72-0011-R10A-SM-HAKXS,-0.8939,-1.2389,-0.2327,0.6869,NaN,0.2397,1.7016,0.0177,0.3420,-0.6706,...,-0.4290,0.3264,NaN,-0.0228,-0.4763,0.1232,0.5818,-0.9205,0.4480,0.0427
GTEX-UTHO-0011-R10A-SM-HAKY2,-0.9099,-0.8944,-0.3690,0.6246,NaN,0.0249,1.6525,0.0052,0.4240,-0.8376,...,-0.7996,0.3834,-0.2616,-0.0172,-0.8114,1.2875,0.6307,-0.6117,0.3250,-0.6692
GTEX-WVLH-0011-R10A-SM-HAKXZ,-1.0700,-1.4596,-0.6068,0.9326,1.0757,0.2082,1.6651,-0.3067,0.1235,-0.5732,...,-1.6180,0.1814,NaN,-0.0297,-1.2247,-0.4613,0.6461,-0.8790,0.4103,NaN
GTEX-Y8DK-0011-R10A-SM-HAKY1,-0.8782,-1.1712,-0.4063,0.9263,1.3172,0.2146,1.6297,-0.1211,0.0139,-0.8453,...,-0.7707,0.3931,0.8383,0.0159,-1.1338,-0.5434,0.6363,-0.7667,0.3615,-0.2860

In [15]:
gb.get_clinical(source="pdc")

,age_at_diagnosis,ajcc_clinical_m,ajcc_clinical_n,ajcc_clinical_stage,ajcc_clinical_t,ajcc_pathologic_m,ajcc_pathologic_n,ajcc_pathologic_stage,ajcc_pathologic_t,ann_arbor_b_symptoms,...,synchronous_malignancy,tissue_or_organ_of_origin,tumor_cell_content,tumor_grade,tumor_stage,vascular_invasion_present,vital_status,year_of_birth,year_of_death,year_of_diagnosis
case_submitter_id,,,,,,,,,,,,,,,,,,,,,
C3L-00104,21170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Frontal lobe,NaN,Not Reported,Not Reported,NaN,Dead,1958.0,2016.0,NaN
C3L-00365,21535.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1957.0,2017.0,NaN
C3L-00674,16425.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Frontal lobe,NaN,Not Reported,Not Reported,NaN,Dead,1971.0,2018.0,NaN
C3L-00677,25185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Frontal lobe,NaN,Not Reported,Not Reported,NaN,Dead,1946.0,2017.0,NaN
C3L-01040,28105.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Frontal lobe,NaN,Not Reported,Not Reported,NaN,Alive,1939.0,NaN,NaN
C3L-01043,21535.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1958.0,2017.0,NaN
C3L-01045,26645.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1943.0,2017.0,NaN
C3L-01046,18250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1966.0,2018.0,NaN
C3L-01048,21900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1957.0,NaN,NaN
C3L-01049,16790.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1971.0,2018.0,NaN
C3L-01061,24090.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1951.0,NaN,NaN
C3L-01142,15330.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1975.0,NaN,NaN
C3L-01146,21535.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1958.0,NaN,NaN
C3L-01149,17520.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1969.0,NaN,NaN
C3L-01154,18615.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1965.0,NaN,NaN
C3L-01155,24090.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1950.0,NaN,NaN
C3L-01156,20805.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1960.0,2018.0,NaN
C3L-01157,24090.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1951.0,NaN,NaN
C3L-01327,27010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Frontal lobe,NaN,Not Reported,Not Reported,NaN,Dead,1942.0,2018.0,NaN
C3L-01834,24820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1949.0,2018.0,NaN
C3L-01887,17520.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1968.0,NaN,NaN
C3L-02041,18615.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Temporal lobe,NaN,Not Reported,Not Reported,NaN,Alive,1965.0,NaN,NaN
C3L-02465,18250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Frontal lobe,NaN,Not Reported,Not Reported,NaN,Dead,1966.0,2019.0,NaN
C3L-02504,25915.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Occipital lobe,NaN,Not Reported,Not Reported,NaN,Alive,1945.0,NaN,NaN
C3L-02542,21170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Temporal lobe,NaN,Not Reported,Not Reported,NaN,Dead,1958.0,2018.0,NaN
C3L-02642,28105.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Frontal lobe,NaN,Not Reported,Not Reported,NaN,Alive,1940.0,NaN,NaN
C3L-02704,19710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Frontal lobe,NaN,Not Reported,Not Reported,NaN,Alive,1963.0,NaN,NaN
C3L-02705,21900.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Frontal lobe,NaN,Not Reported,Not Reported,NaN,Dead,1957.0,2017.0,NaN
C3L-02707,21170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Temporal lobe,NaN,Not Reported,Not Reported,NaN,Alive,1959.0,NaN,NaN
C3L-02708,15695.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Parietal lobe,NaN,Not Reported,Not Reported,NaN,Alive,1973.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C3N-02255,32120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Occipital lobe,NaN,Not Reported,Not Reported,NaN,Dead,1928.0,2018.0,NaN
C3N-02256,23725.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Temporal lobe,NaN,Not Reported,Not Reported,NaN,Dead,1952.0,2018.0,NaN
C3N-02769,19345.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1963.0,NaN,NaN
C3N-02770,25550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1947.0,2019.0,NaN
C3N-02782,17155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1969.0,NaN,NaN
C3N-02783,8760.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1993.0,NaN,NaN
C3N-02784,13505.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1980.0,2018.0,NaN
C3N-02785,25185.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1948.0,2019.0,NaN
C3N-02786,14235.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1977.0,NaN,NaN
C3N-02788,23360.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Temporal lobe,NaN,Not Reported,Not Reported,NaN,Not Reported,1953.0,NaN,NaN
C3N-03070,23725.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1952.0,NaN,NaN
C3N-03088,11315.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Occipital lobe,NaN,Not Reported,Not Reported,NaN,Dead,1986.0,2018.0,NaN
C3N-03180,19345.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Not Reported,1964.0,NaN,NaN
C3N-03182,17155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1970.0,NaN,NaN
C3N-03183,19345.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Dead,1964.0,2018.0,NaN
C3N-03184,12775.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Not Reported,1982.0,NaN,NaN
C3N-03186,19710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1963.0,NaN,NaN
C3N-03188,19710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Alive,1963.0,NaN,NaN
C3N-03473,10950.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Brain, NOS",NaN,Not Reported,Not Reported,NaN,Not Reported,1987.0,NaN,NaN
GTEX-NPJ7-0011-R10A-SM-HAKXW,24820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Dead,NaN,NaN,NaN
GTEX-P44H-0011-R10A-SM-HAKXX,15695.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Dead,NaN,NaN,NaN
GTEX-Q2AG-0011-R10A-SM-HAKXT,15330.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Dead,NaN,NaN,NaN
GTEX-QVJO-0011-R10A-SM-HAKXV,23360.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Dead,NaN,NaN,NaN
GTEX-R55F-0011-R10A-SM-HAKXY,20075.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Dead,NaN,NaN,NaN
GTEX-RN5K-0011-R10A-SM-HAKXU,20440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Dead,NaN,NaN,NaN
GTEX-RU72-0011-R10A-SM-HAKXS,21535.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Dead,NaN,NaN,NaN
GTEX-UTHO-0011-R10A-SM-HAKY2,24820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Dead,NaN,NaN,NaN
GTEX-WVLH-0011-R10A-SM-HAKXZ,21170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Dead,NaN,NaN,NaN
GTEX-Y8DK-0011-R10A-SM-HAKY1,22630.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Dead,NaN,NaN,NaN
ref,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Not Reported,NaN,Not Reported,Not Reported,NaN,Not Reported,NaN,NaN,NaN