# PDC data demo

This notebooks demonstrates using the `cptac.pancan` module to stream data tables from the PDC.

First, import the module.

In [1]:
import cptac.pancan as pancan

### Available data

The `list_pdc_datasets` function lists the PDC study IDs for all datasets available through `cptac.pancan`. The module groups data by cancer type into classes; thus loading the `PdcBrca` class will provide you the BRCA acetylome, proteome, and phosphoproteome data tables, which come from the listed PDC study IDs.

The quantitative tables each come from a quantDataMatrix query of the PDC database. For each cancer type, we also provide the clinical table from a clinicalPerStudy query.

In [2]:
pancan.list_pdc_datasets()

PdcBrca:
	acetylome: PDC000239
	phosphoproteome: PDC000121
	proteome: PDC000120
PdcCcrcc:
	phosphoproteome: PDC000128
	proteome: PDC000127
PdcCoad:
	phosphoproteome: PDC000117
	proteome: PDC000116
PdcGbm:
	acetylome: PDC000245
	phosphoproteome: PDC000205
	proteome: PDC000204
PdcHnscc:
	phosphoproteome: PDC000222
	proteome: PDC000221
PdcLscc:
	acetylome: PDC000233
	phosphoproteome: PDC000232
	proteome: PDC000234
	ubiquitylome: PDC000237
PdcLuad:
	acetylome: PDC000224
	phosphoproteome: PDC000149
	proteome: PDC000153
PdcOv:
	phosphoproteome: PDC000119
	proteome: PDC000118
PdcPda:
	proteome: PDC000270
	phosphoproteome: PDC000271
PdcUcec:
	acetylome: PDC000226
	phosphoproteome: PDC000126
	proteome: PDC000125

### Loading datasets

To load a dataset, we first download it.

In [3]:
pancan.download("PdcBrca")

The pdcbrca dataset has been downloaded previously. If you wish to erase the existing download and re-download it, pass 'redownload=True'.

Then, load the corresponding class.

In [4]:
br = pancan.PdcBrca()

To access individual tables, call the class's corresponding "get" method:

In [5]:
br.get_clinical()

,age_at_diagnosis,ajcc_clinical_m,ajcc_clinical_n,ajcc_clinical_stage,ajcc_clinical_t,ajcc_pathologic_m,ajcc_pathologic_n,ajcc_pathologic_stage,ajcc_pathologic_t,ann_arbor_b_symptoms,...,synchronous_malignancy,tissue_or_organ_of_origin,tumor_cell_content,tumor_grade,tumor_stage,vascular_invasion_present,vital_status,year_of_birth,year_of_death,year_of_diagnosis
case_submitter_id,,,,,,,,,,,,,,,,,,,,,
604,14964.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
01BR001,20074.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
01BR008,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR009,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR010,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR015,12774.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
01BR017,16424.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage III,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage III,Not Reported,Not Reported,NaN,NaN,NaN
01BR018,24089.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
01BR020,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR023,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR025,22629.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
01BR026,0.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
01BR027,29199.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
01BR030,30659.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
01BR031,22264.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage III,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage III,Not Reported,Not Reported,NaN,NaN,NaN
01BR032,15329.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIB,Not Reported,Not Reported,NaN,NaN,NaN
01BR033,14599.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage III,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage III,Not Reported,Not Reported,NaN,NaN,NaN
01BR040,14599.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
01BR042,21139.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage II,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage II,Not Reported,Not Reported,NaN,NaN,NaN
01BR043,21747.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage II,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage II,Not Reported,Not Reported,NaN,NaN,NaN
01BR044,30994.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage III,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage III,Not Reported,Not Reported,NaN,NaN,NaN
03BR002,22112.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
03BR004,32363.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
03BR005,22417.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
03BR006,15512.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
03BR010,28652.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
03BR011,25945.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
03BR013,19010.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
05BR001,25549.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
05BR003,13717.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11BR080,24941.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
13BR009,27374.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIB,Not Reported,Not Reported,NaN,NaN,NaN
14BR005,28530.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
14BR008,24089.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
14BR014,21565.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
15BR003,0.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
16BR012,14599.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIC,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIC,Not Reported,Not Reported,NaN,NaN,NaN
18BR002,23390.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR003,24029.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR004,28013.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR006,22721.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR007,23359.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR009,23177.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR010,14934.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
18BR016,26918.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IA,Not Reported,Not Reported,NaN,NaN,NaN
18BR017,26492.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IA,Not Reported,Not Reported,NaN,NaN,NaN
18BR019,24819.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
20BR001,29929.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
20BR002,32872.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
20BR005,17276.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
20BR006,23877.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
20BR007,19679.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
20BR008,26249.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIB,Not Reported,Not Reported,NaN,NaN,NaN
21BR001,0.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
21BR002,0.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
21BR010,25914.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIA,Not Reported,Not Reported,NaN,NaN,NaN
22BR005,16759.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIB,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIB,Not Reported,Not Reported,NaN,NaN,NaN
22BR006,19922.0,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Stage IIIA,Not Reported,Not Reported,...,NaN,"Breast, NOS",NaN,Not Reported,Stage IIIA,Not Reported,Not Reported,NaN,NaN,NaN
Internal Reference - Pooled Sample,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,NaN,Not Reported,Not Reported,...,NaN,Not Reported,NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN
RetroIR,NaN,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,Not Reported,NaN,Not Reported,Not Reported,...,NaN,Not Reported,NaN,Not Reported,Not Reported,Not Reported,Not Reported,NaN,NaN,NaN

In [6]:
br.get_proteomics()

                                                         A1BG     A2M   A2ML1  \
case_submitter_id aliquot_submitter_id
03BR013           01f203fd-e664-4d78-bea0-7c40cf_D2    0.6183  0.0210 -1.7295
03BR006           071be0fb-b7fd-4165-b3c5-348352      -0.9804 -0.7511  0.8833
11BR023           079b5600-6afc-4785-bb22-48cfab_D2   -0.3880 -0.4169 -0.8210
01BR017           09659708-7747-4d59-a3b9-e221e0_D2    0.5332  0.9145  0.1794
11BR023           0a80d3c4-0758-447a-958c-ea868c       1.6098  1.7210  2.4154
18BR010           0bb9d596-774e-452b-9c89-a6643c_D2    0.2386  0.4597 -1.0179
01BR009           0ecabbfa-8095-4875-acdb-051582_D1    0.2883  1.0262  1.0538
18BR019           0edcba67-0714-4b04-b433-77834e_D2    0.5052  0.1750 -2.1420
22BR005           12110cb8-8da4-4461-ac1a-1af490_D2    0.0333 -0.2818 -1.8557
11BR074           12ce8313-6c54-4bee-a996-1aa7f8_D2    0.5639 -0.0999 -1.1685
09BR005           150c2086-1815-40d2-bc5d-8eeb48_D2   -0.2474 -1.2508 -1.9274
11BR073           1664b920-5e60-4e3b-9aab-fe121c       2.0745  2.3750 -0.0737
11BR025           1740224c-32d1-4c9f-98c6-653363       1.2843  1.6602  2.3754
01BR001           17d55745-4ab3-4a80-a182-af938b_D2    0.9205  0.6200 -1.5461
01BR027           1990853a-0e82-40b3-a025-91cdc1_D2   -0.0756  0.5439  2.8934
18BR007           1ae5772a-ba49-4c00-b890-7513d0_D2    0.6101  0.3865 -1.1283
01BR030           1f5a9aad-61a1-4a64-a9b0-38cd2b_D2    0.7404  0.6252 -1.0969
21BR001           1fb9fca2-cf63-41f2-9381-d9108c      -0.3887 -0.3321 -1.5772
09BR001           20506075-36a7-4754-8e5e-628918      -0.1509 -0.5641 -2.0061
NaN               2386c36d-8d5d-4fd4-bbfa-39cc8d_D2.1 -0.0734 -0.2707 -1.8129
                  2386c36d-8d5d-4fd4-bbfa-39cc8d_D2.2 -0.1751 -0.3024 -1.5420
11BR017           241c8dec-b317-4794-8cc2-07c14c_D2    0.0426 -0.2862 -0.0874
                  241ecd0e-89bd-4d3a-81b3-55a250       2.2309  2.5265  0.5189
06BR005           25db2586-55b0-4456-9bba-c24e06_D2   -0.1713 -0.3285 -1.7274
01BR010           26ecef2d-fcf3-4b85-9647-5e5d29_D1   -0.3184 -0.4881 -2.1017
11BR003           2dc74c29-2e89-4600-80bf-1e3637_D2   -0.1576 -0.2162 -0.7973
11BR049           2e700669-85b0-43fa-a9c7-3eaf5a_D2    0.1259  0.5133 -1.6888
20BR005           2f398497-d53e-4838-8006-d60f3e_D2   -0.2445 -0.6762  1.5605
11BR032           314de592-f356-4801-8ace-278173_D2    0.2692 -0.3419 -1.7405
06BR003           31b13596-554e-452f-91a4-7e67a8_D2    0.0732 -0.2972 -0.8986
...                                                       ...     ...     ...
01BR043           c4015b28-269b-4dc4-8b2e-1b83f7_D2    0.5015  0.2959 -0.7783
01BR033           c646b902-e1e0-4e3e-a4c5-daca71_D2    0.3465  0.0791 -1.2820
01BR023           c875a9a4-035f-425a-9348-26129c_D1   -0.3675 -0.7980 -2.7244
14BR008           ca14c6dd-2069-4bc5-b1f2-6f2297_D2    1.6476  1.1898 -0.8477
03BR002           ca576d30-be91-4bf5-a31d-80f7eb_D2    0.8365  0.6834 -1.1327
11BR015           cab796c6-0129-43cf-bd27-7da395_D2    0.0797 -0.1001 -1.5083
01BR008           cfa2809f-5468-4457-870c-467c39_D1   -0.3536  0.0777  0.6186
09BR004           cfc121b5-9562-4a6d-b792-3cd6d5_D2   -0.1604  0.0006 -0.8965
05BR044           d01714eb-22bf-4ad7-95d9-f95bdf_D2   -0.1771 -0.3385  1.2057
05BR029           d0ce3c06-9c4c-41bd-b583-9254b0_D2    0.2893 -0.0304  3.5936
14BR014           d1034660-11ce-4e38-9ad0-8b9b72_D2    0.7836  1.0605 -0.5348
01BR018           d154d194-2b08-46d4-a199-84cfb8_D8    0.7488  0.9163  0.6128
05BR026           d1e36453-8d78-4247-8c3c-3b2a6f_D2    0.4246  0.0672 -2.0104
01BR025           d6d42051-ad8e-4fb2-8cfc-829353_D2   -0.1107 -0.5642 -1.1304
11BR040           d7b05dce-4362-4e8f-a77a-07dd74_D2    0.6159  0.2739 -1.4006
11BR050           d8a5467b-549b-48ed-9ae5-c9c39d_D2    1.4444  1.1731 -1.4674
11BR044           d92a2942-dba6-4fff-b0d0-0566fb_D2   -0.4244 -0.1798 -1.4943
11BR022           da3d7876-ca79-4f21-a00e-27e6b6_D2    0.4224  0.4174 -1.3347
11BR014           ddc680ad-63cf-4807-b535-9ccc88_D2    0.1597 -0.1306 -1.8734
11BR080           e2c7113f-957f-4088-b57d-55d2f2_D2    0.3683  0.9649  1.2503
18BR003           e3d45dc6-66ef-4e0b-9d96-1b5db5       1.8100  2.4710  0.3333
11BR056           e45c73a8-da96-4269-a039-d43942_D2   -0.2456 -0.0556 -1.8880
01BR032           e5e1306b-719e-4c3e-b85b-fd1231_D2   -0.4948 -0.2783 -2.2871
11BR047           ef52c640-13a9-4855-9ce2-0be77a_D2    0.1099 -0.4779 -1.4739
11BR013           faadb553-9437-42cb-b469-498d67_D2    0.1645 -0.2933 -1.4903
NaN               fb526979-ee2d-4edf-b41d-01074f_D2.1  0.1894  0.0999 -1.3727
                  fb526979-ee2d-4edf-b41d-01074f_D2.2  0.1131 -0.1698 -1.7414
11BR059           fc0aa1e4-c1d8-43ed-a5cd-038f61_D2    0.0081  0.1783 -1.3611
18BR002           fe591474-99d7-44d3-be73-c3b8ed_D2    1.2394  1.2919 -1.4054
05BR003           ffc76bfb-61f6-4492-a782-c23321_D2    0.1338  0.0589 -0.8227

                                                         AAAS    AACS   AADAT  \
case_submitter_id aliquot_submitter_id
03BR013           01f203fd-e664-4d78-bea0-7c40cf_D2   -0.1048 -0.5589 -0.2368
03BR006           071be0fb-b7fd-4165-b3c5-348352       0.5709 -0.5232     NaN
11BR023           079b5600-6afc-4785-bb22-48cfab_D2    0.4011 -0.5305     NaN
01BR017           09659708-7747-4d59-a3b9-e221e0_D2    0.2714 -0.0139     NaN
11BR023           0a80d3c4-0758-447a-958c-ea868c       0.3461 -0.4682     NaN
18BR010           0bb9d596-774e-452b-9c89-a6643c_D2    0.2347 -0.2409     NaN
01BR009           0ecabbfa-8095-4875-acdb-051582_D1   -0.0663 -0.5431     NaN
18BR019           0edcba67-0714-4b04-b433-77834e_D2   -0.5392 -0.0166 -0.3233
22BR005           12110cb8-8da4-4461-ac1a-1af490_D2    0.0476 -0.1963 -0.6790
11BR074           12ce8313-6c54-4bee-a996-1aa7f8_D2    0.0242 -0.8363     NaN
09BR005           150c2086-1815-40d2-bc5d-8eeb48_D2    0.2506  0.2543 -0.1287
11BR073           1664b920-5e60-4e3b-9aab-fe121c       0.1803 -0.4966     NaN
11BR025           1740224c-32d1-4c9f-98c6-653363       0.4646 -0.3137     NaN
01BR001           17d55745-4ab3-4a80-a182-af938b_D2    0.2554 -0.3552  0.6674
01BR027           1990853a-0e82-40b3-a025-91cdc1_D2    0.5581 -0.8132  0.1108
18BR007           1ae5772a-ba49-4c00-b890-7513d0_D2    0.0737 -0.0573  0.0364
01BR030           1f5a9aad-61a1-4a64-a9b0-38cd2b_D2   -0.0511 -0.5268 -0.3188
21BR001           1fb9fca2-cf63-41f2-9381-d9108c       0.3615 -0.5789     NaN
09BR001           20506075-36a7-4754-8e5e-628918       0.2669 -0.2973 -0.3762
NaN               2386c36d-8d5d-4fd4-bbfa-39cc8d_D2.1  0.3198  0.0160 -0.9752
                  2386c36d-8d5d-4fd4-bbfa-39cc8d_D2.2  0.2963  0.0494     NaN
11BR017           241c8dec-b317-4794-8cc2-07c14c_D2    0.1977  0.5109  0.4267
                  241ecd0e-89bd-4d3a-81b3-55a250       0.5473 -0.0564     NaN
06BR005           25db2586-55b0-4456-9bba-c24e06_D2    0.0653  0.0585 -0.6810
01BR010           26ecef2d-fcf3-4b85-9647-5e5d29_D1    0.1253  1.1133  2.9714
11BR003           2dc74c29-2e89-4600-80bf-1e3637_D2    0.4609 -0.9352 -0.2051
11BR049           2e700669-85b0-43fa-a9c7-3eaf5a_D2    0.0211  0.2175     NaN
20BR005           2f398497-d53e-4838-8006-d60f3e_D2    0.1736  0.0445 -0.0565
11BR032           314de592-f356-4801-8ace-278173_D2   -0.0510 -0.1001  0.0236
06BR003           31b13596-554e-452f-91a4-7e67a8_D2    0.4322 -0.8179     NaN
...                                                       ...     ...     ...
01BR043           c4015b28-269b-4dc4-8b2e-1b83f7_D2    0.5622 -0.7029     NaN
01BR033           c646b902-e1e0-4e3e-a4c5-daca71_D2    0.2252 -0.4101 -1.1309
01BR023           c875a9a4-035f-425a-9348-26129c_D1    0.3550 -0.9243 -1.2035
14BR008           ca14c6dd-2069-4bc5-b1f2-6f2297_D2   -0.0573 -0.9096  0.7691
03BR002           ca576d30-be91-4bf5-a31d-80f7eb_D2   -0.1064 -0.7477     NaN
11BR015           cab796c6-0129-43cf-bd27-7da395_D2    0.3430  0.2958     NaN
01BR008           cfa2809f-5468-4457-870c-467c39_D1    0.1901 -1.1722     NaN
09BR004           cfc121b5-9562-4a6d-b792-3cd6d5_D2    0.0996 -0.1078 -0.0746
05BR044           d01714eb-22bf-4ad7-95d9-f95bdf_D2    0.0090  2.9515  3.4039
05BR029           d0ce3c06-9c4c-41bd-b583-9254b0_D2    0.2064 -0.8812     NaN
14BR014           d1034660-11ce-4e38-9ad0-8b9b72_D2    0.0478 -0.4191     NaN
01BR018           d154d194-2b08-46d4-a199-84cfb8_D8    0.0266 -1.2230  0.9211
05BR026           d1e36453-8d78-4247-8c3c-3b2a6f_D2   -0.0740 -0.6026     NaN
01BR025           d6d42051-ad8e-4fb2-8cfc-829353_D2    0.5184  0.4934     NaN
11BR040           d7b05dce-4362-4e8f-a77a-07dd74_D2    0.0593  0.0006     NaN
11BR050           d8a5467b-549b-48ed-9ae5-c9c39d_D2   -0.2972 -0.5608 -0.2973
11BR044           d92a2942-dba6-4fff-b0d0-0566fb_D2    0.1741 -0.4731 -0.8694
11BR022           da3d7876-ca79-4f21-a00e-27e6b6_D2    0.0187  0.0675 -0.9309
11BR014           ddc680ad-63cf-4807-b535-9ccc88_D2   -0.3103 -0.7123 -0.7758
11BR080           e2c7113f-957f-4088-b57d-55d2f2_D2    0.0808 -0.2819     NaN
18BR003           e3d45dc6-66ef-4e0b-9d96-1b5db5      -0.2966 -0.4565     NaN
11BR056           e45c73a8-da96-4269-a039-d43942_D2    0.0979 -0.2875     NaN
01BR032           e5e1306b-719e-4c3e-b85b-fd1231_D2    0.0272  0.2722 -1.0084
11BR047           ef52c640-13a9-4855-9ce2-0be77a_D2    0.0974  0.4111     NaN
11BR013           faadb553-9437-42cb-b469-498d67_D2    0.4424 -0.6502 -1.0989
NaN               fb526979-ee2d-4edf-b41d-01074f_D2.1 -0.7131 -0.1960  1.4673
                  fb526979-ee2d-4edf-b41d-01074f_D2.2 -0.4771 -0.5050 -0.4510
11BR059           fc0aa1e4-c1d8-43ed-a5cd-038f61_D2    0.0430 -0.2512  0.4583
18BR002           fe591474-99d7-44d3-be73-c3b8ed_D2   -0.1819 -0.8141  0.3147
05BR003           ffc76bfb-61f6-4492-a782-c23321_D2   -0.0207 -0.3536     NaN

                                                        AAED1   AAGAB    AAK1  \
case_submitter_id aliquot_submitter_id
03BR013           01f203fd-e664-4d78-bea0-7c40cf_D2    0.1427  0.3162  0.0469
03BR006           071be0fb-b7fd-4165-b3c5-348352      -0.0209 -0.9446 -0.1140
11BR023           079b5600-6afc-4785-bb22-48cfab_D2       NaN -0.2938  0.6456
01BR017           09659708-7747-4d59-a3b9-e221e0_D2       NaN  0.0743  0.1176
11BR023           0a80d3c4-0758-447a-958c-ea868c          NaN -0.4092 -0.0162
18BR010           0bb9d596-774e-452b-9c89-a6643c_D2       NaN  0.3265  0.0000
01BR009           0ecabbfa-8095-4875-acdb-051582_D1   -0.0249 -0.2518 -0.1299
18BR019           0edcba67-0714-4b04-b433-77834e_D2    0.2615  0.0399 -0.3070
22BR005           12110cb8-8da4-4461-ac1a-1af490_D2    1.6521  0.4078  0.2451
11BR074           12ce8313-6c54-4bee-a996-1aa7f8_D2       NaN  0.0461  0.2479
09BR005           150c2086-1815-40d2-bc5d-8eeb48_D2   -0.5900 -0.3460  0.1326
11BR073           1664b920-5e60-4e3b-9aab-fe121c          NaN -0.3695 -0.3759
11BR025           1740224c-32d1-4c9f-98c6-653363          NaN -0.2695 -0.1970
01BR001           17d55745-4ab3-4a80-a182-af938b_D2   -0.0670 -0.6254  0.0348
01BR027           1990853a-0e82-40b3-a025-91cdc1_D2    0.6384  0.1959 -0.0871
18BR007           1ae5772a-ba49-4c00-b890-7513d0_D2    0.8421  0.2391  0.3563
01BR030           1f5a9aad-61a1-4a64-a9b0-38cd2b_D2       NaN -0.0850 -0.1179
21BR001           1fb9fca2-cf63-41f2-9381-d9108c      -0.2758 -0.1014  0.0007
09BR001           20506075-36a7-4754-8e5e-628918      -0.0563  0.0547 -0.2533
NaN               2386c36d-8d5d-4fd4-bbfa-39cc8d_D2.1 -0.0611  0.1919  0.1232
                  2386c36d-8d5d-4fd4-bbfa-39cc8d_D2.2 -0.0175  0.1065 -0.1136
11BR017           241c8dec-b317-4794-8cc2-07c14c_D2   -0.0388  0.0470  0.5260
                  241ecd0e-89bd-4d3a-81b3-55a250          NaN -0.3552 -0.2642
06BR005           25db2586-55b0-4456-9bba-c24e06_D2   -0.2324  0.6843  0.3275
01BR010           26ecef2d-fcf3-4b85-9647-5e5d29_D1    0.4628 -0.4796 -0.0832
11BR003           2dc74c29-2e89-4600-80bf-1e3637_D2    1.7848 -0.5291 -0.1948
11BR049           2e700669-85b0-43fa-a9c7-3eaf5a_D2       NaN  0.1279 -0.0351
20BR005           2f398497-d53e-4838-8006-d60f3e_D2   -0.4935 -0.3371  0.0282
11BR032           314de592-f356-4801-8ace-278173_D2    0.8459  0.7003  0.2671
06BR003           31b13596-554e-452f-91a4-7e67a8_D2       NaN  0.5668 -0.2514
...                                                       ...     ...     ...
01BR043           c4015b28-269b-4dc4-8b2e-1b83f7_D2    0.7250  0.4532  0.0071
01BR033           c646b902-e1e0-4e3e-a4c5-daca71_D2   -0.3449  0.5164  0.0352
01BR023           c875a9a4-035f-425a-9348-26129c_D1   -0.4903  0.2965  0.1358
14BR008           ca14c6dd-2069-4bc5-b1f2-6f2297_D2    0.8796 -0.4627 -0.2052
03BR002           ca576d30-be91-4bf5-a31d-80f7eb_D2    0.4525  0.4876  0.0450
11BR015           cab796c6-0129-43cf-bd27-7da395_D2   -0.2073 -0.1957 -0.4613
01BR008           cfa2809f-5468-4457-870c-467c39_D1   -0.0570 -0.3568 -0.1714
09BR004           cfc121b5-9562-4a6d-b792-3cd6d5_D2    0.0378  0.0483 -0.0376
05BR044           d01714eb-22bf-4ad7-95d9-f95bdf_D2    0.4734  0.0417  0.0172
05BR029           d0ce3c06-9c4c-41bd-b583-9254b0_D2    0.8226  0.3731  0.1761
14BR014           d1034660-11ce-4e38-9ad0-8b9b72_D2    0.8022  0.2115 -0.0875
01BR018           d154d194-2b08-46d4-a199-84cfb8_D8       NaN -0.1070 -0.4273
05BR026           d1e36453-8d78-4247-8c3c-3b2a6f_D2   -0.0423  0.1345 -0.0910
01BR025           d6d42051-ad8e-4fb2-8cfc-829353_D2    0.5896  0.6201 -0.0904
11BR040           d7b05dce-4362-4e8f-a77a-07dd74_D2    0.2008  0.0760 -0.0913
11BR050           d8a5467b-549b-48ed-9ae5-c9c39d_D2    0.4359 -0.1879 -0.0174
11BR044           d92a2942-dba6-4fff-b0d0-0566fb_D2   -0.1462 -0.2770 -0.1687
11BR022           da3d7876-ca79-4f21-a00e-27e6b6_D2    0.3666  0.4926 -0.0363
11BR014           ddc680ad-63cf-4807-b535-9ccc88_D2   -0.7411 -0.1189  0.1393
11BR080           e2c7113f-957f-4088-b57d-55d2f2_D2    0.1222 -0.1949  0.1564
18BR003           e3d45dc6-66ef-4e0b-9d96-1b5db5          NaN -0.6796 -0.1163
11BR056           e45c73a8-da96-4269-a039-d43942_D2   -0.0615 -0.0369  0.1355
01BR032           e5e1306b-719e-4c3e-b85b-fd1231_D2   -0.7767  0.2132  0.5713
11BR047           ef52c640-13a9-4855-9ce2-0be77a_D2       NaN  0.4101  0.3536
11BR013           faadb553-9437-42cb-b469-498d67_D2    0.0587  0.0714 -0.3501
NaN               fb526979-ee2d-4edf-b41d-01074f_D2.1  0.3508  1.0792 -0.0617
                  fb526979-ee2d-4edf-b41d-01074f_D2.2  1.3335  0.4047  0.6702
11BR059           fc0aa1e4-c1d8-43ed-a5cd-038f61_D2    0.3481  0.3433  0.2632
18BR002           fe591474-99d7-44d3-be73-c3b8ed_D2    0.7803 -0.1285  0.3651
05BR003           ffc76bfb-61f6-4492-a782-c23321_D2    0.6450  0.2302  0.1437

                                                        AAMDC  ...  ZSWIM6  \
case_submitter_id aliquot_submitter_id                         ...
03BR013           01f203fd-e664-4d78-bea0-7c40cf_D2    0.2785  ... -0.2778
03BR006           071be0fb-b7fd-4165-b3c5-348352      -1.1978  ... -0.8029
11BR023           079b5600-6afc-4785-bb22-48cfab_D2   -0.3412  ...     NaN
01BR017           09659708-7747-4d59-a3b9-e221e0_D2   -0.0783  ...     NaN
11BR023           0a80d3c4-0758-447a-958c-ea868c       1.2231  ...     NaN
18BR010           0bb9d596-774e-452b-9c89-a6643c_D2    0.2115  ...     NaN
01BR009           0ecabbfa-8095-4875-acdb-051582_D1   -0.3942  ...  0.7016
18BR019           0edcba67-0714-4b04-b433-77834e_D2    0.1692  ...     NaN
22BR005           12110cb8-8da4-4461-ac1a-1af490_D2    0.0644  ...     NaN
11BR074           12ce8313-6c54-4bee-a996-1aa7f8_D2    0.2427  ...     NaN
09BR005           150c2086-1815-40d2-bc5d-8eeb48_D2    0.0282  ... -0.9649
11BR073           1664b920-5e60-4e3b-9aab-fe121c       1.7666  ...     NaN
11BR025           1740224c-32d1-4c9f-98c6-653363       1.0863  ...     NaN
01BR001           17d55745-4ab3-4a80-a182-af938b_D2   -0.0926  ...  1.4294
01BR027           1990853a-0e82-40b3-a025-91cdc1_D2   -0.7512  ...  0.1656
18BR007           1ae5772a-ba49-4c00-b890-7513d0_D2   -0.0573  ...     NaN
01BR030           1f5a9aad-61a1-4a64-a9b0-38cd2b_D2   -0.3059  ...     NaN
21BR001           1fb9fca2-cf63-41f2-9381-d9108c       0.1394  ... -0.7752
09BR001           20506075-36a7-4754-8e5e-628918       1.3892  ...     NaN
NaN               2386c36d-8d5d-4fd4-bbfa-39cc8d_D2.1  0.2896  ...  0.1536
                  2386c36d-8d5d-4fd4-bbfa-39cc8d_D2.2  0.0601  ...  0.1836
11BR017           241c8dec-b317-4794-8cc2-07c14c_D2    0.4493  ...  0.5547
                  241ecd0e-89bd-4d3a-81b3-55a250       1.7365  ...     NaN
06BR005           25db2586-55b0-4456-9bba-c24e06_D2   -0.6672  ...  0.3064
01BR010           26ecef2d-fcf3-4b85-9647-5e5d29_D1    0.0437  ...     NaN
11BR003           2dc74c29-2e89-4600-80bf-1e3637_D2   -1.1258  ...  0.0807
11BR049           2e700669-85b0-43fa-a9c7-3eaf5a_D2   -0.4441  ...     NaN
20BR005           2f398497-d53e-4838-8006-d60f3e_D2   -0.0645  ...     NaN
11BR032           314de592-f356-4801-8ace-278173_D2    0.0005  ... -0.2251
06BR003           31b13596-554e-452f-91a4-7e67a8_D2    0.4349  ...     NaN
...                                                       ...  ...     ...
01BR043           c4015b28-269b-4dc4-8b2e-1b83f7_D2   -0.3561  ...     NaN
01BR033           c646b902-e1e0-4e3e-a4c5-daca71_D2   -0.2661  ... -0.0838
01BR023           c875a9a4-035f-425a-9348-26129c_D1   -0.2708  ...     NaN
14BR008           ca14c6dd-2069-4bc5-b1f2-6f2297_D2    0.1941  ...  1.5931
03BR002           ca576d30-be91-4bf5-a31d-80f7eb_D2    0.4744  ...  0.2650
11BR015           cab796c6-0129-43cf-bd27-7da395_D2    0.5925  ...     NaN
01BR008           cfa2809f-5468-4457-870c-467c39_D1   -0.7457  ... -0.3064
09BR004           cfc121b5-9562-4a6d-b792-3cd6d5_D2   -1.0473  ...  0.1104
05BR044           d01714eb-22bf-4ad7-95d9-f95bdf_D2   -0.4253  ...  1.4771
05BR029           d0ce3c06-9c4c-41bd-b583-9254b0_D2    1.0705  ...     NaN
14BR014           d1034660-11ce-4e38-9ad0-8b9b72_D2    0.4757  ...  0.3138
01BR018           d154d194-2b08-46d4-a199-84cfb8_D8    0.2394  ...     NaN
05BR026           d1e36453-8d78-4247-8c3c-3b2a6f_D2    3.8506  ... -0.0798
01BR025           d6d42051-ad8e-4fb2-8cfc-829353_D2    1.0584  ...     NaN
11BR040           d7b05dce-4362-4e8f-a77a-07dd74_D2   -0.1737  ...     NaN
11BR050           d8a5467b-549b-48ed-9ae5-c9c39d_D2   -0.3062  ...     NaN
11BR044           d92a2942-dba6-4fff-b0d0-0566fb_D2    0.5904  ... -0.5243
11BR022           da3d7876-ca79-4f21-a00e-27e6b6_D2    0.2536  ... -0.1212
11BR014           ddc680ad-63cf-4807-b535-9ccc88_D2    0.6657  ...     NaN
11BR080           e2c7113f-957f-4088-b57d-55d2f2_D2    0.2881  ...  0.1486
18BR003           e3d45dc6-66ef-4e0b-9d96-1b5db5       1.6998  ...     NaN
11BR056           e45c73a8-da96-4269-a039-d43942_D2   -0.0008  ...  0.0460
01BR032           e5e1306b-719e-4c3e-b85b-fd1231_D2    1.0879  ... -1.6465
11BR047           ef52c640-13a9-4855-9ce2-0be77a_D2    0.0489  ...     NaN
11BR013           faadb553-9437-42cb-b469-498d67_D2    1.5344  ...  0.3897
NaN               fb526979-ee2d-4edf-b41d-01074f_D2.1  0.9795  ... -0.1829
                  fb526979-ee2d-4edf-b41d-01074f_D2.2  0.9354  ... -0.7416
11BR059           fc0aa1e4-c1d8-43ed-a5cd-038f61_D2    0.0224  ... -0.3332
18BR002           fe591474-99d7-44d3-be73-c3b8ed_D2    0.5250  ...  1.3096
05BR003           ffc76bfb-61f6-4492-a782-c23321_D2    0.8791  ...     NaN

                                                       ZSWIM8    ZW10  ZWILCH  \
case_submitter_id aliquot_submitter_id
03BR013           01f203fd-e664-4d78-bea0-7c40cf_D2    0.0118 -0.0794 -0.4726
03BR006           071be0fb-b7fd-4165-b3c5-348352      -0.0961  0.2245  0.4409
11BR023           079b5600-6afc-4785-bb22-48cfab_D2    0.1106  0.2180  0.5331
01BR017           09659708-7747-4d59-a3b9-e221e0_D2    0.0544 -0.0216 -0.1709
11BR023           0a80d3c4-0758-447a-958c-ea868c      -0.4748 -0.1420     NaN
18BR010           0bb9d596-774e-452b-9c89-a6643c_D2   -0.0187 -0.0095  0.2412

In [7]:
br.get_phosphoproteomics()

                                                     NP_000005.2:s710  \
case_submitter_id aliquot_submitter_id
03BR013           01f203fd-e664-4d78-bea0-7c40cf_D2           -0.2450
03BR006           071be0fb-b7fd-4165-b3c5-348352                  NaN
11BR023           079b5600-6afc-4785-bb22-48cfab_D2               NaN
01BR017           09659708-7747-4d59-a3b9-e221e0_D2               NaN
11BR023           0a80d3c4-0758-447a-958c-ea868c              -0.2125
18BR010           0bb9d596-774e-452b-9c89-a6643c_D2               NaN
01BR009           0ecabbfa-8095-4875-acdb-051582_D1               NaN
18BR019           0edcba67-0714-4b04-b433-77834e_D2               NaN
22BR005           12110cb8-8da4-4461-ac1a-1af490_D2           -0.4337
11BR074           12ce8313-6c54-4bee-a996-1aa7f8_D2               NaN
09BR005           150c2086-1815-40d2-bc5d-8eeb48_D2               NaN
11BR073           1664b920-5e60-4e3b-9aab-fe121c              -1.6326
11BR025           1740224c-32d1-4c9f-98c6-653363               0.5288
01BR001           17d55745-4ab3-4a80-a182-af938b_D2               NaN
01BR027           1990853a-0e82-40b3-a025-91cdc1_D2            2.3791
18BR007           1ae5772a-ba49-4c00-b890-7513d0_D2           -0.2921
01BR030           1f5a9aad-61a1-4a64-a9b0-38cd2b_D2               NaN
21BR001           1fb9fca2-cf63-41f2-9381-d9108c                  NaN
09BR001           20506075-36a7-4754-8e5e-628918              -1.5076
14BR005           2386c36d-8d5d-4fd4-bbfa-39cc8d_D2               NaN
                  2386c36d-8d5d-4fd4-bbfa-39cc8d_D2               NaN
11BR017           241c8dec-b317-4794-8cc2-07c14c_D2               NaN
                  241ecd0e-89bd-4d3a-81b3-55a250              -0.9137
06BR005           25db2586-55b0-4456-9bba-c24e06_D2               NaN
01BR010           26ecef2d-fcf3-4b85-9647-5e5d29_D1            0.5822
11BR003           2dc74c29-2e89-4600-80bf-1e3637_D2           -0.6885
11BR049           2e700669-85b0-43fa-a9c7-3eaf5a_D2               NaN
20BR005           2f398497-d53e-4838-8006-d60f3e_D2               NaN
11BR032           314de592-f356-4801-8ace-278173_D2           -0.4164
06BR003           31b13596-554e-452f-91a4-7e67a8_D2               NaN
...                                                               ...
01BR043           c4015b28-269b-4dc4-8b2e-1b83f7_D2               NaN
01BR033           c646b902-e1e0-4e3e-a4c5-daca71_D2               NaN
01BR023           c875a9a4-035f-425a-9348-26129c_D1           -0.3964
14BR008           ca14c6dd-2069-4bc5-b1f2-6f2297_D2           -0.7913
03BR002           ca576d30-be91-4bf5-a31d-80f7eb_D2               NaN
11BR015           cab796c6-0129-43cf-bd27-7da395_D2               NaN
01BR008           cfa2809f-5468-4457-870c-467c39_D1               NaN
09BR004           cfc121b5-9562-4a6d-b792-3cd6d5_D2               NaN
05BR044           d01714eb-22bf-4ad7-95d9-f95bdf_D2               NaN
05BR029           d0ce3c06-9c4c-41bd-b583-9254b0_D2               NaN
14BR014           d1034660-11ce-4e38-9ad0-8b9b72_D2               NaN
01BR018           d154d194-2b08-46d4-a199-84cfb8_D8               NaN
05BR026           d1e36453-8d78-4247-8c3c-3b2a6f_D2               NaN
01BR025           d6d42051-ad8e-4fb2-8cfc-829353_D2               NaN
11BR040           d7b05dce-4362-4e8f-a77a-07dd74_D2               NaN
11BR050           d8a5467b-549b-48ed-9ae5-c9c39d_D2           -0.4841
11BR044           d92a2942-dba6-4fff-b0d0-0566fb_D2               NaN
11BR022           da3d7876-ca79-4f21-a00e-27e6b6_D2               NaN
11BR014           ddc680ad-63cf-4807-b535-9ccc88_D2           -0.7116
11BR080           e2c7113f-957f-4088-b57d-55d2f2_D2               NaN
18BR003           e3d45dc6-66ef-4e0b-9d96-1b5db5              -0.1802
11BR056           e45c73a8-da96-4269-a039-d43942_D2               NaN
01BR032           e5e1306b-719e-4c3e-b85b-fd1231_D2               NaN
11BR047           ef52c640-13a9-4855-9ce2-0be77a_D2               NaN
11BR013           faadb553-9437-42cb-b469-498d67_D2               NaN
11BR053           fb526979-ee2d-4edf-b41d-01074f_D2               NaN
                  fb526979-ee2d-4edf-b41d-01074f_D2           -0.4845
11BR059           fc0aa1e4-c1d8-43ed-a5cd-038f61_D2               NaN
18BR002           fe591474-99d7-44d3-be73-c3b8ed_D2           -0.8183
05BR003           ffc76bfb-61f6-4492-a782-c23321_D2               NaN

                                                     NP_000005.2:s879t885s889  \
case_submitter_id aliquot_submitter_id
03BR013           01f203fd-e664-4d78-bea0-7c40cf_D2                       NaN
03BR006           071be0fb-b7fd-4165-b3c5-348352                          NaN
11BR023           079b5600-6afc-4785-bb22-48cfab_D2                       NaN
01BR017           09659708-7747-4d59-a3b9-e221e0_D2                       NaN
11BR023           0a80d3c4-0758-447a-958c-ea868c                      -1.2766
18BR010           0bb9d596-774e-452b-9c89-a6643c_D2                       NaN
01BR009           0ecabbfa-8095-4875-acdb-051582_D1                       NaN
18BR019           0edcba67-0714-4b04-b433-77834e_D2                       NaN
22BR005           12110cb8-8da4-4461-ac1a-1af490_D2                       NaN
11BR074           12ce8313-6c54-4bee-a996-1aa7f8_D2                       NaN
09BR005           150c2086-1815-40d2-bc5d-8eeb48_D2                       NaN
11BR073           1664b920-5e60-4e3b-9aab-fe121c                          NaN
11BR025           1740224c-32d1-4c9f-98c6-653363                       1.7469
01BR001           17d55745-4ab3-4a80-a182-af938b_D2                       NaN
01BR027           1990853a-0e82-40b3-a025-91cdc1_D2                       NaN
18BR007           1ae5772a-ba49-4c00-b890-7513d0_D2                       NaN
01BR030           1f5a9aad-61a1-4a64-a9b0-38cd2b_D2                       NaN
21BR001           1fb9fca2-cf63-41f2-9381-d9108c                          NaN
09BR001           20506075-36a7-4754-8e5e-628918                          NaN
14BR005           2386c36d-8d5d-4fd4-bbfa-39cc8d_D2                       NaN
                  2386c36d-8d5d-4fd4-bbfa-39cc8d_D2                       NaN
11BR017           241c8dec-b317-4794-8cc2-07c14c_D2                       NaN
                  241ecd0e-89bd-4d3a-81b3-55a250                          NaN
06BR005           25db2586-55b0-4456-9bba-c24e06_D2                       NaN
01BR010           26ecef2d-fcf3-4b85-9647-5e5d29_D1                       NaN
11BR003           2dc74c29-2e89-4600-80bf-1e3637_D2                       NaN
11BR049           2e700669-85b0-43fa-a9c7-3eaf5a_D2                       NaN
20BR005           2f398497-d53e-4838-8006-d60f3e_D2                       NaN
11BR032           314de592-f356-4801-8ace-278173_D2                       NaN
06BR003           31b13596-554e-452f-91a4-7e67a8_D2                       NaN
...                                                                       ...
01BR043           c4015b28-269b-4dc4-8b2e-1b83f7_D2                       NaN
01BR033           c646b902-e1e0-4e3e-a4c5-daca71_D2                       NaN
01BR023           c875a9a4-035f-425a-9348-26129c_D1                       NaN
14BR008           ca14c6dd-2069-4bc5-b1f2-6f2297_D2                       NaN
03BR002           ca576d30-be91-4bf5-a31d-80f7eb_D2                       NaN
11BR015           cab796c6-0129-43cf-bd27-7da395_D2                       NaN
01BR008           cfa2809f-5468-4457-870c-467c39_D1                       NaN
09BR004           cfc121b5-9562-4a6d-b792-3cd6d5_D2                       NaN
05BR044           d01714eb-22bf-4ad7-95d9-f95bdf_D2                       NaN
05BR029           d0ce3c06-9c4c-41bd-b583-9254b0_D2                       NaN
14BR014           d1034660-11ce-4e38-9ad0-8b9b72_D2                       NaN
01BR018           d154d194-2b08-46d4-a199-84cfb8_D8                       NaN
05BR026           d1e36453-8d78-4247-8c3c-3b2a6f_D2                       NaN
01BR025           d6d42051-ad8e-4fb2-8cfc-829353_D2                       NaN
11BR040           d7b05dce-4362-4e8f-a77a-07dd74_D2                       NaN
11BR050           d8a5467b-549b-48ed-9ae5-c9c39d_D2                       NaN
11BR044           d92a2942-dba6-4fff-b0d0-0566fb_D2                       NaN
11BR022           da3d7876-ca79-4f21-a00e-27e6b6_D2                       NaN
11BR014           ddc680ad-63cf-4807-b535-9ccc88_D2                       NaN
11BR080           e2c7113f-957f-4088-b57d-55d2f2_D2                       NaN
18BR003           e3d45dc6-66ef-4e0b-9d96-1b5db5                          NaN
11BR056           e45c73a8-da96-4269-a039-d43942_D2                       NaN
01BR032           e5e1306b-719e-4c3e-b85b-fd1231_D2                       NaN
11BR047           ef52c640-13a9-4855-9ce2-0be77a_D2                       NaN
11BR013           faadb553-9437-42cb-b469-498d67_D2                       NaN
11BR053           fb526979-ee2d-4edf-b41d-01074f_D2                       NaN
                  fb526979-ee2d-4edf-b41d-01074f_D2                       NaN
11BR059           fc0aa1e4-c1d8-43ed-a5cd-038f61_D2                       NaN
18BR002           fe591474-99d7-44d3-be73-c3b8ed_D2                       NaN
05BR003           ffc76bfb-61f6-4492-a782-c23321_D2                       NaN

                                                     NP_000009.1:s522  \
case_submitter_id aliquot_submitter_id
03BR013           01f203fd-e664-4d78-bea0-7c40cf_D2               NaN
03BR006           071be0fb-b7fd-4165-b3c5-348352                  NaN
11BR023           079b5600-6afc-4785-bb22-48cfab_D2               NaN
01BR017           09659708-7747-4d59-a3b9-e221e0_D2               NaN
11BR023           0a80d3c4-0758-447a-958c-ea868c                  NaN
18BR010           0bb9d596-774e-452b-9c89-a6643c_D2               NaN
01BR009           0ecabbfa-8095-4875-acdb-051582_D1               NaN
18BR019           0edcba67-0714-4b04-b433-77834e_D2               NaN
22BR005           12110cb8-8da4-4461-ac1a-1af490_D2               NaN
11BR074           12ce8313-6c54-4bee-a996-1aa7f8_D2               NaN
09BR005           150c2086-1815-40d2-bc5d-8eeb48_D2               NaN
11BR073           1664b920-5e60-4e3b-9aab-fe121c                  NaN
11BR025           1740224c-32d1-4c9f-98c6-653363                  NaN
01BR001           17d55745-4ab3-4a80-a182-af938b_D2               NaN
01BR027           1990853a-0e82-40b3-a025-91cdc1_D2               NaN
18BR007           1ae5772a-ba49-4c00-b890-7513d0_D2               NaN
01BR030           1f5a9aad-61a1-4a64-a9b0-38cd2b_D2               NaN
21BR001           1fb9fca2-cf63-41f2-9381-d9108c                  NaN
09BR001           20506075-36a7-4754-8e5e-628918               0.0027
14BR005           2386c36d-8d5d-4fd4-bbfa-39cc8d_D2               NaN
                  2386c36d-8d5d-4fd4-bbfa-39cc8d_D2               NaN
11BR017           241c8dec-b317-4794-8cc2-07c14c_D2               NaN
                  241ecd0e-89bd-4d3a-81b3-55a250                  NaN
06BR005           25db2586-55b0-4456-9bba-c24e06_D2               NaN
01BR010           26ecef2d-fcf3-4b85-9647-5e5d29_D1            0.3052
11BR003           2dc74c29-2e89-4600-80bf-1e3637_D2               NaN
11BR049           2e700669-85b0-43fa-a9c7-3eaf5a_D2               NaN
20BR005           2f398497-d53e-4838-8006-d60f3e_D2               NaN
11BR032           314de592-f356-4801-8ace-278173_D2               NaN
06BR003           31b13596-554e-452f-91a4-7e67a8_D2               NaN
...                                                               ...
01BR043           c4015b28-269b-4dc4-8b2e-1b83f7_D2               NaN
01BR033           c646b902-e1e0-4e3e-a4c5-daca71_D2               NaN
01BR023           c875a9a4-035f-425a-9348-26129c_D1            0.0325
14BR008           ca14c6dd-2069-4bc5-b1f2-6f2297_D2               NaN
03BR002           ca576d30-be91-4bf5-a31d-80f7eb_D2               NaN
11BR015           cab796c6-0129-43cf-bd27-7da395_D2               NaN
01BR008           cfa2809f-5468-4457-870c-467c39_D1               NaN
09BR004           cfc121b5-9562-4a6d-b792-3cd6d5_D2               NaN
05BR044           d01714eb-22bf-4ad7-95d9-f95bdf_D2               NaN
05BR029           d0ce3c06-9c4c-41bd-b583-9254b0_D2               NaN
14BR014           d1034660-11ce-4e38-9ad0-8b9b72_D2           -1.0054
01BR018           d154d194-2b08-46d4-a199-84cfb8_D8               NaN
05BR026           d1e36453-8d78-4247-8c3c-3b2a6f_D2               NaN
01BR025           d6d42051-ad8e-4fb2-8cfc-829353_D2               NaN
11BR040           d7b05dce-4362-4e8f-a77a-07dd74_D2               NaN
11BR050           d8a5467b-549b-48ed-9ae5-c9c39d_D2               NaN
11BR044           d92a2942-dba6-4fff-b0d0-0566fb_D2               NaN
11BR022           da3d7876-ca79-4f21-a00e-27e6b6_D2               NaN
11BR014           ddc680ad-63cf-4807-b535-9ccc88_D2               NaN
11BR080           e2c7113f-957f-4088-b57d-55d2f2_D2            0.1055
18BR003           e3d45dc6-66ef-4e0b-9d96-1b5db5                  NaN
11BR056           e45c73a8-da96-4269-a039-d43942_D2               NaN
01BR032           e5e1306b-719e-4c3e-b85b-fd1231_D2               NaN
11BR047           ef52c640-13a9-4855-9ce2-0be77a_D2               NaN
11BR013           faadb553-9437-42cb-b469-498d67_D2               NaN
11BR053           fb526979-ee2d-4edf-b41d-01074f_D2               NaN
                  fb526979-ee2d-4edf-b41d-01074f_D2               NaN
11BR059           fc0aa1e4-c1d8-43ed-a5cd-038f61_D2               NaN
18BR002           fe591474-99d7-44d3-be73-c3b8ed_D2               NaN
05BR003           ffc76bfb-61f6-4492-a782-c23321_D2               NaN

                                                     NP_000012.1:s324  \
case_submitter_id aliquot_submitter_id
03BR013           01f203fd-e664-4d78-bea0-7c40cf_D2               NaN
03BR006           071be0fb-b7fd-4165-b3c5-348352                  NaN
11BR023           079b5600-6afc-4785-bb22-48cfab_D2               NaN
01BR017           09659708-7747-4d59-a3b9-e221e0_D2               NaN
11BR023           0a80d3c4-0758-447a-958c-ea868c                  NaN
18BR010           0bb9d596-774e-452b-9c89-a6643c_D2               NaN
01BR009           0ecabbfa-8095-4875-acdb-051582_D1               NaN
18BR019           0edcba67-0714-4b04-b433-77834e_D2               NaN
22BR005           12110cb8-8da4-4461-ac1a-1af490_D2            0.2170
11BR074           12ce8313-6c54-4bee-a996-1aa7f8_D2               NaN
09BR005           150c2086-1815-40d2-bc5d-8eeb48_D2               NaN
11BR073           1664b920-5e60-4e3b-9aab-fe121c                  NaN
11BR025           1740224c-32d1-4c9f-98c6-653363                  NaN
01BR001           17d55745-4ab3-4a80-a182-af938b_D2               NaN
01BR027           1990853a-0e82-40b3-a025-91cdc1_D2               NaN
18BR007           1ae5772a-ba49-4c00-b890-7513d0_D2           -0.6365
01BR030           1f5a9aad-61a1-4a64-a9b0-38cd2b_D2               NaN
21BR001           1fb9fca2-cf63-41f2-9381-d9108c                  NaN
09BR001           20506075-36a7-4754-8e5e-628918                  NaN
14BR005           2386c36d-8d5d-4fd4-bbfa-39cc8d_D2               NaN
                  2386c36d-8d5d-4fd4-bbfa-39cc8d_D2               NaN
11BR017           241c8dec-b317-4794-8cc2-07c14c_D2               NaN
                  241ecd0e-89bd-4d3a-81b3-55a250                  NaN
06BR005           25db2586-55b0-4456-9bba-c24e06_D2               NaN
01BR010           26ecef2d-fcf3-4b85-9647-5e5d29_D1               NaN
11BR003           2dc74c29-2e89-4600-80bf-1e3637_D2               NaN
11BR049           2e700669-85b0-43fa-a9c7-3eaf5a_D2               NaN
20BR005           2f398497-d53e-4838-8006-d60f3e_D2               NaN
11BR032           314de592-f356-4801-8ace-278173_D2               NaN
06BR003           31b13596-554e-452f-91a4-7e67a8_D2               NaN
...                                                               ...
01BR043           c4015b28-269b-4dc4-8b2e-1b83f7_D2               NaN
01BR033           c646b902-e1e0-4e3e-a4c5-daca71_D2               NaN
01BR023           c875a9a4-035f-425a-9348-26129c_D1               NaN
14BR008           ca14c6dd-2069-4bc5-b1f2-6f2297_D2               NaN
03BR002           ca576d30-be91-4bf5-a31d-80f7eb_D2               NaN
11BR015           cab796c6-0129-43cf-bd27-7da395_D2               NaN
01BR008           cfa2809f-5468-4457-870c-467c39_D1               NaN
09BR004           cfc121b5-9562-4a6d-b792-3cd6d5_D2               NaN
05BR044           d01714eb-22bf-4ad7-95d9-f95bdf_D2               NaN
05BR029           d0ce3c06-9c4c-41bd-b583-9254b0_D2               NaN
14BR014           d1034660-11ce-4e38-9ad0-8b9b72_D2               NaN
01BR018           d154d194-2b08-46d4-a199-84cfb8_D8               NaN
05BR026           d1e36453-8d78-4247-8c3c-3b2a6f_D2               NaN
01BR025           d6d42051-ad8e-4fb2-8cfc-829353_D2               NaN
11BR040           d7b05dce-4362-4e8f-a77a-07dd74_D2               NaN
11BR050           d8a5467b-549b-48ed-9ae5-c9c39d_D2           -0.5165
11BR044           d92a2942-dba6-4fff-b0d0-0566fb_D2               NaN
11BR022           da3d7876-ca79-4f21-a00e-27e6b6_D2               NaN
11BR014           ddc680ad-63cf-4807-b535-9ccc88_D2           -0.9265
11BR080           e2c7113f-957f-4088-b57d-55d2f2_D2               NaN
18BR003           e3d45dc6-66ef-4e0b-9d96-1b5db5                  NaN
11BR056           e45c73a8-da96-4269-a039-d43942_D2               NaN
01BR032           e5e1306b-719e-4c3e-b85b-fd1231_D2               NaN
11BR047           ef52c640-13a9-4855-9ce2-0be77a_D2               NaN
11BR013           faadb553-9437-42cb-b469-498d67_D2               NaN
11BR053           fb526979-ee2d-4edf-b41d-01074f_D2               NaN
                  fb526979-ee2d-4edf-b41d-01074f_D2               NaN
11BR059           fc0aa1e4-c1d8-43ed-a5cd-038f61_D2               NaN
18BR002           fe591474-99d7-44d3-be73-c3b8ed_D2               NaN
05BR003           ffc76bfb-61f6-4492-a782-c23321_D2               NaN

                                                     NP_000012.1:s324s337  \
case_submitter_id aliquot_submitter_id
03BR013           01f203fd-e664-4d78-bea0-7c40cf_D2                   NaN
03BR006           071be0fb-b7fd-4165-b3c5-348352                      NaN
11BR023           079b5600-6afc-4785-bb22-48cfab_D2                   NaN
01BR017           09659708-7747-4d59-a3b9-e221e0_D2                   NaN
11BR023           0a80d3c4-0758-447a-958c-ea868c                      NaN
18BR010           0bb9d596-774e-452b-9c89-a6643c_D2                   NaN
01BR009           0ecabbfa-8095-4875-acdb-051582_D1                   NaN
18BR019           0edcba67-0714-4b04-b433-77834e_D2                   NaN
22BR005           12110cb8-8da4-4461-ac1a-1af490_D2                   NaN
11BR074           12ce8313-6c54-4bee-a996-1aa7f8_D2                   NaN
09BR005           150c2086-1815-40d2-bc5d-8eeb48_D2                   NaN
11BR073           1664b920-5e60-4e3b-9aab-fe121c                      NaN
11BR025           1740224c-32d1-4c9f-98c6-653363                      NaN
01BR001           17d55745-4ab3-4a80-a182-af938b_D2                   NaN
01BR027           1990853a-0e82-40b3-a025-91cdc1_D2                   NaN
18BR007           1ae5772a-ba49-4c00-b890-7513d0_D2                   NaN
01BR030           1f5a9aad-61a1-4a64-a9b0-38cd2b_D2                   NaN
21BR001           1fb9fca2-cf63-41f2-9381-d9108c                      NaN
09BR001           20506075-36a7-4754-8e5e-628918                  -0.1223
14BR005           2386c36d-8d5d-4fd4-bbfa-39cc8d_D2                   NaN
                  2386c36d-8d5d-4fd4-bbfa-39cc8d_D2                   NaN
11BR017           241c8dec-b317-4794-8cc2-07c14c_D2                   NaN
                  241ecd0e-89bd-4d3a-81b3-55a250                      NaN
06BR005           25db2586-55b0-4456-9bba-c24e06_D2                   NaN
01BR010           26ecef2d-fcf3-4b85-9647-5e5d29_D1                0.8619

### Downloading by PDC ID

The package also has the capability to just get you the dat from a single PDC study ID.

In [8]:
clin, quant = pancan.download_pdc_id("PDC000271")

In [9]:
clin

,age_at_diagnosis,ajcc_clinical_m,ajcc_clinical_n,ajcc_clinical_stage,ajcc_clinical_t,ajcc_pathologic_m,ajcc_pathologic_n,ajcc_pathologic_stage,ajcc_pathologic_t,ann_arbor_b_symptoms,...,synchronous_malignancy,tissue_or_organ_of_origin,tumor_cell_content,tumor_grade,tumor_stage,vascular_invasion_present,vital_status,year_of_birth,year_of_death,year_of_diagnosis
case_submitter_id,,,,,,,,,,,,,,,,,,,,,
C3N-02940,23550,,None,None,None,,,Stage III,,None,...,None,Head of pancreas,None,G2,Stage III,None,Alive,1953,None,None
C3L-03628,25282,,None,None,None,,,Stage IIB,,None,...,None,"Pancreas, NOS",None,G2,Stage IIB,None,Dead,1948,2019,None
C3N-03839,19956,,None,None,None,,,Stage IIB,,None,...,None,Head of pancreas,None,G2,Stage IIB,None,Alive,1963,None,2017
C3L-02890,24050,,None,None,None,,,Stage IIB,,None,...,None,Head of pancreas,None,G3,Stage IIB,None,Alive,1951,None,None
C3N-00198,20306,Unknown,None,None,None,Unknown,N1,Stage IIB,T3,None,...,None,Body of pancreas,None,G2,Stage IIB,None,Alive,1960,None,2017
C3N-01997,23169,,None,None,None,,,Stage IB,,None,...,None,Tail of pancreas,None,G2,Stage IB,None,Dead,1953,2020,None
C3N-01714,23163,,None,None,None,,,Stage IIB,,None,...,None,Head of pancreas,None,G2,Stage IIB,None,Dead,1953,2018,2017
C3N-02010,22742,,None,None,None,,N2,Not Reported,T3,None,...,None,Head of pancreas,None,G3,pT3 N2 M(Not Applicable),None,Alive,1956,None,2017
C3L-04495,13477,,None,None,None,,,Stage III,,None,...,None,"Pancreas, NOS",None,G2,Stage III,None,Dead,1981,2019,2017
C3L-01689,22672,M0,None,None,None,M0,N1,Stage IIB,T3,None,...,None,Head of pancreas,None,G2,Stage IIB,None,Dead,1955,2018,2017
C3L-02897,29507,,None,None,None,,,Stage I,,None,...,None,Head of pancreas,None,G2,Stage I,None,Alive,1937,None,None
C3N-01900,None,,None,None,None,,,Not Reported,,None,...,None,Not Reported,None,Not Reported,Not Reported,None,,None,None,None
C3N-00249,26108,Unknown,None,None,None,Unknown,N1,Stage III,T3,None,...,None,Body of pancreas,None,G2,Stage III,None,Alive,1945,None,2016
C3L-03394,24110,,None,None,None,,,Stage IB,,None,...,None,Body of pancreas,None,G1,Stage IB,None,Dead,1952,2019,None
C3N-00957,27089,Unknown,None,None,None,Unknown,N0,Stage IIA,T3,None,...,None,Tail of pancreas,None,G2,Stage IIA,None,Alive,1942,None,2016
C3N-03039,None,,None,None,None,,,Not Reported,,None,...,None,Head of pancreas,None,G2,Not Reported,None,Not Reported,1944,None,2017
C3L-03632,27050,,None,None,None,,,Stage IB,,None,...,None,"Pancreas, NOS",None,G1,Stage IB,None,Alive,1944,None,2017
C3L-00102,15616,M0,None,None,None,Unknown,N1,Stage IIB,T3,None,...,None,Head of pancreas,None,G3,Stage IIB,None,Dead,1973,2017,2016
C3N-03007,21772,,None,None,None,,,Not Reported,,None,...,None,Head of pancreas,None,G2,pT2N2,None,Dead,1958,2017,None
C3N-04283,24187,,None,None,None,,,Stage III,,None,...,None,Head of pancreas,None,G3,Stage III,None,Dead,1952,2018,None
C3L-04072,20413,,None,None,None,,,Stage III,,None,...,None,Head of pancreas,None,G3,Stage III,None,Dead,1962,2018,None
C3N-03069,18530,,None,None,None,,,Stage III,,None,...,None,Body of pancreas,None,G2,Stage III,None,Dead,1967,2018,2016
C3N-01166,22892,M0,None,None,None,M0,N1,Stage III,T3,None,...,None,Head of pancreas,None,G2,Stage III,None,Alive,1954,None,2016
C3N-03840,21749,,None,None,None,,,Stage IIB,,None,...,None,Body of pancreas,None,G2,Stage IIB,None,Alive,1958,None,None
QC6,None,None,None,None,None,None,None,Not Reported,None,None,...,None,Not Reported,None,Not Reported,Not Reported,None,None,None,None,None
C3L-03388,24887,,None,None,None,,,Stage III,,None,...,None,Head of pancreas,None,G2,Stage III,None,Dead,1950,2018,2016
C3N-01998,25293,,None,None,None,,,Stage IIB,,None,...,None,Head of pancreas,None,G2,Stage IIB,None,Dead,1948,2017,None
C3L-03395,28498,,None,None,None,,,Stage III,,None,...,None,Tail of pancreas,None,G2,Stage III,None,Dead,1941,2019,None
C3N-00709,None,,None,None,None,,,Not Reported,,None,...,None,Head of pancreas,None,G2,Not Reported,None,Not Reported,1935,None,None
C3L-03356,26098,,None,None,None,,,Stage IIB,,None,...,None,Head of pancreas,None,G2,Stage IIB,None,Alive,1946,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C3N-03430,19939,,None,None,None,,,Not Reported,,None,...,None,Head of pancreas,None,G2,no resection,None,Dead,1963,2018,2017
QC2,None,None,None,None,None,None,None,Not Reported,None,None,...,None,Not Reported,None,Not Reported,Not Reported,None,None,None,None,None
C3L-01703,22902,M0,None,None,None,M0,N0,Stage IIA,T3,None,...,None,"Pancreas, NOS",None,G3,Stage IIA,None,Dead,1954,2018,2016
C3L-03639,27761,,None,None,None,,,Stage IB,,None,...,None,Head of pancreas,None,G3,Stage IB,None,Dead,1942,2019,None
C3L-02604,31007,,None,None,None,,,Stage IIB,,None,...,None,Tail of pancreas,None,G1,Stage IIB,None,Dead,1932,2017,None
C3L-03350,None,,None,None,None,,,Not Reported,,None,...,None,Not Reported,None,Not Reported,Not Reported,None,,None,None,None
C3L-04080,25862,,None,None,None,,,Stage IIB,,None,...,None,Head of pancreas,None,G3,Stage IIB,None,Dead,1947,2018,2017
C3L-03630,28674,,None,None,None,,,Stage IIB,,None,...,None,Head of pancreas,None,G2,Stage IIB,None,Alive,1939,None,None
C3L-01054,14036,,None,None,None,,,Stage IV,,None,...,None,Head of pancreas,None,G2,Stage IV,None,Dead,1978,2019,None
C3N-01375,25895,M0,None,None,None,M0,N1,Stage IIB,T3,None,...,None,Head of pancreas,None,G2,Stage IIB,None,Dead,1946,2017,2017
C3N-03754,16266,,None,None,None,,,Not Reported,,None,...,None,Head of pancreas,None,G2,pT2N2,None,Alive,1973,None,None
C3L-07035,None,,None,None,None,,,Not Reported,,None,...,None,Not Reported,None,Not Reported,Not Reported,None,None,None,None,None
C3N-02295,20557,,None,None,None,,,Stage III,,None,...,None,Head of pancreas,None,G1,Stage III,None,Dead,1961,2018,None
QC4,None,None,None,None,None,None,None,Not Reported,None,None,...,None,Not Reported,None,Not Reported,Not Reported,None,None,None,None,None
C3N-02768,17037,,None,None,None,,,Stage IIB,,None,...,None,"Pancreas, NOS",None,G3,Stage IIB,None,Dead,1971,2018,2017
C3N-03665,23168,,None,None,None,,N2,Not Reported,T2,None,...,None,Head of pancreas,None,G2,pT2N2,None,Alive,1954,None,None
C3N-02998,23734,,None,None,None,,,Stage III,,None,...,None,Head of pancreas,None,G2,Stage III,None,Dead,1952,2018,None
C3N-01012,25953,,None,None,None,,N0,Not Reported,T2,None,...,None,Head of pancreas,None,G2,pT2 N0,None,Alive,1947,None,None
C3L-03514,None,,None,None,None,,,Not Reported,,None,...,None,Not Reported,None,Not Reported,Not Reported,None,None,None,None,None
C3N-01379,None,,None,None,None,,,Not Reported,,None,...,None,Not Reported,None,Not Reported,Not Reported,None,,None,None,None
C3L-07034,None,,None,None,None,,,Not Reported,,None,...,None,Not Reported,None,Not Reported,Not Reported,None,None,None,None,None
C3N-03428,23159,,None,None,None,,,Not Reported,,None,...,None,Head of pancreas,None,G2,no resection,None,Dead,1954,2018,2017
C3N-02971,28635,,None,None,None,,,Stage III,,None,...,None,Tail of pancreas,None,G1,Stage III,None,Dead,1939,2018,2016
C3N-03670,22035,,None,None,None,,,Not Reported,,None,...,None,Head of pancreas,None,G2,pT2N2,None,Alive,1957,None,None
WU-pooled sample,None,None,None,None,None,None,None,Not Reported,None,None,...,None,Not Reported,None,Not Reported,Not Reported,None,None,None,None,None
C3N-02579,18922,,None,None,None,,,Stage IA,,None,...,None,Head of pancreas,None,G2,Stage IA,None,Dead,1965,2018,None
C3N-01380,24117,M0,None,None,None,M1,N1,Stage IV,T3,None,...,None,Head of pancreas,None,G2,Stage IV,None,Dead,1951,2018,2017
C3N-04284,29323,,None,None,None,,,Stage III,,None,...,None,Head of pancreas,None,G3,Stage III,None,Dead,1938,2018,None
C3N-01381,15744,M0,None,None,None,M0,N1,Stage III,T3,None,...,None,Head of pancreas,None,G2,Stage III,None,Dead,1974,2018,2017
C3N-00511,16455,M0,None,None,None,M0,N1,Stage IIB,T3,None,...,None,Head of pancreas,None,G2,Stage IIB,None,Dead,1971,2019,2016

In [10]:
quant

                                       NP_000010.1:y170 NP_000011.2:s160  \
case_submitter_id aliquot_submitter_id
C3L-00189         C3L-00189-04                      NaN              NaN
C3L-00401         C3L-00401-04                      NaN              NaN
C3L-03632         C3L-03632-04                      NaN              NaN
C3N-00709         C3N-00709-06                      NaN          -2.2511
C3N-01900         C3N-01900-04                      NaN              NaN
C3N-02573         C3N-02573-03                      NaN          -1.4818
C3L-00017         CPT0000250017                     NaN              NaN
C3L-00102         CPT0001730017                     NaN              NaN
                  CPT0001750003                     NaN              NaN
C3N-00302         CPT0008750003                     NaN              NaN
C3N-00303         CPT0008800003                     NaN              NaN
C3L-00277         CPT0011520003                     NaN              NaN
                  CPT0011540003                     NaN              NaN
C3N-00198         CPT0014040003                     NaN              NaN
C3L-00881         CPT0017040004                     NaN              NaN
                  CPT0017130003                     NaN              NaN
C3L-00401         CPT0019300004                     NaN              NaN
C3L-00598         CPT0019410004                     NaN              NaN
C3N-00249         CPT0025750003                     NaN              NaN
                  CPT0025760003                     NaN              NaN
C3L-00928         CPT0063570003                     NaN              NaN
                  CPT0063580003                     NaN              NaN
C3L-00589         CPT0063970004                     NaN              NaN
C3L-00819         CPT0064090003                     NaN          -0.0737
                  CPT0064110003                     NaN          -0.0786
C3L-00640         CPT0064520004                     NaN              NaN
                  CPT0064570003                     NaN              NaN
C3N-01502         CPT0065570003                     NaN          -0.0658
C3N-01011         CPT0065640003                     NaN              NaN
                  CPT0066020003                     NaN              NaN
...                                                 ...              ...
C3L-04848         CPT0248410004                     NaN              NaN
                  CPT0248440003                     NaN              NaN
C3L-04853         CPT0248590004                     NaN              NaN
                  CPT0248620003                     NaN              NaN
C3L-04027         CPT0254680003                     NaN           1.3436
C3L-03743         CPT0264150003                     NaN              NaN
C3L-03371         CPT0275870003                     NaN              NaN
                  CPT0275880003                     NaN              NaN
C3L-03395         CPT0276010003                     NaN              NaN
                  CPT0276030003                     NaN              NaN
C3L-07032         CPT0347760002                 -0.5795              NaN
C3L-07033         CPT0347790002                 -0.5152              NaN
C3L-07034         CPT0347820002                  1.1857              NaN
C3L-07035         CPT0347850002                  0.1221              NaN
C3L-07036         CPT0347880002                  1.4923              NaN
C3L-03513         CPT0355180003                 -0.7080              NaN
C3L-03515         CPT0355190003                  0.0344              NaN
C3L-03514         CPT0355200003                 -0.4666              NaN
KoreanReference1  KoreanReference1                  NaN              NaN
KoreanReference2  KoreanReference2                  NaN           0.8712
KoreanReference3  KoreanReference3                  NaN              NaN
QC1               QC1                               NaN              NaN
QC2               QC2                               NaN              NaN
QC3               QC3                               NaN              NaN
QC4               QC4                               NaN          -0.0016
QC5               QC5                               NaN              NaN
QC6               QC6                               NaN              NaN
WU-PDA1           WU-PDA1                       -0.5828              NaN
WU-pooled sample  WU-pooled sample              -0.5274              NaN
pooled sample     pooled sample                     NaN              NaN

                                       NP_000011.2:s161 NP_000012.1:s366s367  \
case_submitter_id aliquot_submitter_id
C3L-00189         C3L-00189-04                      NaN                  NaN
C3L-00401         C3L-00401-04                      NaN                  NaN
C3L-03632         C3L-03632-04                      NaN                  NaN
C3N-00709         C3N-00709-06                      NaN                  NaN
C3N-01900         C3N-01900-04                      NaN                  NaN
C3N-02573         C3N-02573-03                      NaN                  NaN
C3L-00017         CPT0000250017                     NaN                  NaN
C3L-00102         CPT0001730017                     NaN                  NaN
                  CPT0001750003                     NaN                  NaN
C3N-00302         CPT0008750003                     NaN                  NaN
C3N-00303         CPT0008800003                     NaN                  NaN
C3L-00277         CPT0011520003                     NaN                  NaN
                  CPT0011540003                     NaN                  NaN
C3N-00198         CPT0014040003                     NaN                  NaN
C3L-00881         CPT0017040004                     NaN                  NaN
                  CPT0017130003                     NaN                  NaN
C3L-00401         CPT0019300004                     NaN                  NaN
C3L-00598         CPT0019410004                 -1.8848                  NaN
C3N-00249         CPT0025750003                     NaN                  NaN
                  CPT0025760003                     NaN                  NaN
C3L-00928         CPT0063570003                  0.5688                  NaN
                  CPT0063580003                 -0.3649                  NaN
C3L-00589         CPT0063970004                     NaN                  NaN
C3L-00819         CPT0064090003                     NaN                  NaN
                  CPT0064110003                     NaN                  NaN
C3L-00640         CPT0064520004                     NaN                  NaN
                  CPT0064570003                     NaN                  NaN
C3N-01502         CPT0065570003                     NaN                  NaN
C3N-01011         CPT0065640003                     NaN                  NaN
                  CPT0066020003                     NaN                  NaN
...                                                 ...                  ...
C3L-04848         CPT0248410004                     NaN                  NaN
                  CPT0248440003                     NaN                  NaN
C3L-04853         CPT0248590004                     NaN                  NaN
                  CPT0248620003                     NaN                  NaN
C3L-04027         CPT0254680003                     NaN                  NaN
C3L-03743         CPT0264150003                     NaN                  NaN
C3L-03371         CPT0275870003                     NaN                  NaN
                  CPT0275880003                     NaN                  NaN
C3L-03395         CPT0276010003                     NaN                  NaN
                  CPT0276030003                     NaN                  NaN
C3L-07032         CPT0347760002                  0.2688                  NaN
C3L-07033         CPT0347790002                  0.5200                  NaN
C3L-07034         CPT0347820002                 -0.1298                  NaN
C3L-07035         CPT0347850002                 -0.3851                  NaN
C3L-07036         CPT0347880002                 -0.1631                  NaN
C3L-03513         CPT0355180003                  0.0355                  NaN
C3L-03515         CPT0355190003                 -0.2462                  NaN
C3L-03514         CPT0355200003                 -0.5635                  NaN
KoreanReference1  KoreanReference1                  NaN                  NaN
KoreanReference2  KoreanReference2                  NaN                  NaN
KoreanReference3  KoreanReference3               1.5009                  NaN
QC1               QC1                               NaN                  NaN
QC2               QC2                               NaN                  NaN
QC3               QC3                               NaN                  NaN
QC4               QC4                               NaN                  NaN
QC5               QC5                           -1.0425                  NaN
QC6               QC6                               NaN                  NaN
WU-PDA1           WU-PDA1                        0.1026                  NaN
WU-pooled sample  WU-pooled sample              -0.0604                  NaN
pooled sample     pooled sample                     NaN                  NaN

                                       NP_000012.1:s367 NP_000012.1:s43  \
case_submitter_id aliquot_submitter_id
C3L-00189         C3L-00189-04                   0.3421         -1.2795
C3L-00401         C3L-00401-04                      NaN         -1.4727
C3L-03632         C3L-03632-04                      NaN         -2.2675
C3N-00709         C3N-00709-06                      NaN         -2.3767
C3N-01900         C3N-01900-04                      NaN             NaN
C3N-02573         C3N-02573-03                      NaN         -2.6331
C3L-00017         CPT0000250017                     NaN         -0.0102
C3L-00102         CPT0001730017                 -1.3066          0.3833
                  CPT0001750003                 -0.7339          0.7875
C3N-00302         CPT0008750003                     NaN          0.2751
C3N-00303         CPT0008800003                  0.1766          0.0871
C3L-00277         CPT0011520003                     NaN         -0.8755
                  CPT0011540003                     NaN         -3.1245
C3N-00198         CPT0014040003                     NaN          0.0357
C3L-00881         CPT0017040004                     NaN         -0.4796
                  CPT0017130003                     NaN         -1.9933
C3L-00401         CPT0019300004                     NaN         -0.7693
C3L-00598         CPT0019410004                     NaN         -0.3323
C3N-00249         CPT0025750003                     NaN          0.6420
                  CPT0025760003                     NaN         -5.1721
C3L-00928         CPT0063570003                     NaN          0.9555
                  CPT0063580003                     NaN         -1.1745
C3L-00589         CPT0063970004                  0.3789          0.5919
C3L-00819         CPT0064090003                     NaN          0.8695
                  CPT0064110003                     NaN          0.0446
C3L-00640         CPT0064520004                     NaN         -0.8175
                  CPT0064570003                     NaN         -1.4904
C3N-01502         CPT0065570003                     NaN          0.0825
C3N-01011         CPT0065640003                     NaN         -0.0810
                  CPT0066020003                     NaN         -1.1417
...                                                 ...             ...
C3L-04848         CPT0248410004                     NaN          0.6016
                  CPT0248440003                     NaN          0.1622
C3L-04853         CPT0248590004                     NaN         -0.0022
                  CPT0248620003                     NaN          0.2280
C3L-04027         CPT0254680003                     NaN          1.1833
C3L-03743         CPT0264150003                 -0.6296          0.7986
C3L-03371         CPT0275870003                  1.1544             NaN
                  CPT0275880003                  0.5670             NaN
C3L-03395         CPT0276010003                 -2.1047          0.1398
                  CPT0276030003                  0.2985         -0.4903
C3L-07032         CPT0347760002                     NaN         -2.5352
C3L-07033         CPT0347790002                     NaN         -3.1456
C3L-07034         CPT0347820002                     NaN         -0.5324
C3L-07035         CPT0347850002                     NaN         -0.0971
C3L-07036         CPT0347880002                     NaN         -0.4147
C3L-03513         CPT0355180003                     NaN         -0.2878
C3L-03515         CPT0355190003                     NaN         -3.0036
C3L-03514         CPT0355200003                     NaN         -4.2834
KoreanReference1  KoreanReference1                  NaN             NaN
KoreanReference2  KoreanReference2                  NaN         -0.5619
KoreanReference3  KoreanReference3                  NaN         -1.0283
QC1               QC1                            0.5084          1.7398
QC2               QC2                               NaN             NaN
QC3               QC3                            0.6883          1.3336
QC4               QC4                               NaN          1.4503
QC5               QC5                               NaN          1.4631
QC6               QC6                               NaN          1.0022
WU-PDA1           WU-PDA1                           NaN          0.0064
WU-pooled sample  WU-pooled sample                  NaN          0.4721
pooled sample     pooled sample                     NaN             NaN

                                       NP_000022.3:s215 NP_000025.1:s132  \
case_submitter_id aliquot_submitter_id
C3L-00189         C3L-00189-04                      NaN          -0.1803
C3L-00401         C3L-00401-04                      NaN              NaN
C3L-03632         C3L-03632-04                      NaN              NaN
C3N-00709         C3N-00709-06                      NaN              NaN
C3N-01900         C3N-01900-04                      NaN          -0.2285
C3N-02573         C3N-02573-03                      NaN              NaN
C3L-00017         CPT0000250017                     NaN              NaN
C3L-00102         CPT0001730017                     NaN              NaN
                  CPT0001750003                     NaN              NaN
C3N-00302         CPT0008750003                     NaN              NaN
C3N-00303         CPT0008800003                     NaN           0.7526
C3L-00277         CPT0011520003                     NaN          -0.0865
                  CPT0011540003                     NaN          -1.0610
C3N-00198         CPT0014040003                  0.2715              NaN
C3L-00881         CPT0017040004                     NaN           0.4705
                  CPT0017130003                     NaN          -0.6039
C3L-00401         CPT0019300004                     NaN              NaN
C3L-00598         CPT0019410004                     NaN              NaN
C3N-00249         CPT0025750003                  1.3863              NaN
                  CPT0025760003                 -3.4469              NaN
C3L-00928         CPT0063570003                     NaN              NaN
                  CPT0063580003                     NaN              NaN
C3L-00589         CPT0063970004                     NaN          -0.0477
C3L-00819         CPT0064090003                     NaN           0.7838
                  CPT0064110003                     NaN          -0.0211
C3L-00640         CPT0064520004                     NaN              NaN
                  CPT0064570003                     NaN              NaN
C3N-01502         CPT0065570003                     NaN              NaN
C3N-01011         CPT0065640003                     NaN              NaN
                  CPT0066020003                     NaN              NaN
...                                                 ...              ...
C3L-04848         CPT0248410004                     NaN           0.5568
                  CPT0248440003                     NaN           0.5728
C3L-04853         CPT0248590004                     NaN              NaN
                  CPT0248620003                     NaN              NaN
C3L-04027         CPT0254680003                     NaN              NaN
C3L-03743         CPT0264150003                     NaN           1.1133
C3L-03371         CPT0275870003                  1.2356           0.6970
                  CPT0275880003                  1.2517           0.1722
C3L-03395         CPT0276010003                     NaN           0.4402
                  CPT0276030003                     NaN          -0.3088
C3L-07032         CPT0347760002                     NaN           0.1671
C3L-07033         CPT0347790002                     NaN           0.0879
C3L-07034         CPT0347820002                     NaN           0.2449
C3L-07035         CPT0347850002                     NaN           0.1558
C3L-07036         CPT0347880002                     NaN           0.4670
C3L-03513         CPT0355180003                     NaN           0.2481
C3L-03515         CPT0355190003                     NaN          -0.5644
C3L-03514         CPT0355200003                     NaN          -0.2734
KoreanReference1  KoreanReference1                  NaN           1.2449
KoreanReference2  KoreanReference2                  NaN           0.5561
KoreanReference3  KoreanReference3                  NaN              NaN
QC1               QC1                               NaN           0.6145
QC2               QC2                               NaN           1.0582
QC3               QC3                               NaN           1.3743
QC4               QC4                               NaN           1.0343
QC5               QC5                               NaN              NaN
QC6               QC6                               NaN              NaN
WU-PDA1           WU-PDA1                           NaN           0.0250
WU-pooled sample  WU-pooled sample                  NaN           0.4884
pooled sample     pooled sample                     NaN              NaN

                                       NP_000025.1:s218y223t227  \
case_submitter_id aliquot_submitter_id
C3L-00189         C3L-00189-04                              NaN
C3L-00401         C3L-00401-04                              NaN
C3L-03632         C3L-03632-04                          -0.8594
C3N-00709         C3N-00709-06                              NaN
C3N-01900         C3N-01900-04                              NaN
C3N-02573         C3N-02573-03                              NaN
C3L-00017         CPT0000250017                             NaN
C3L-00102         CPT0001730017                             NaN
                  CPT0001750003                             NaN
C3N-00302         CPT0008750003                          1.9485
C3N-00303         CPT0008800003                             NaN
C3L-00277         CPT0011520003                             NaN
                  CPT0011540003                             NaN
C3N-00198         CPT0014040003                             NaN
C3L-00881         CPT0017040004                             NaN
                  CPT0017130003                             NaN
C3L-00401         CPT0019300004                             NaN
C3L-00598         CPT0019410004                             NaN
C3N-00249         CPT0025750003                             NaN
                  CPT0025760003                             NaN
C3L-00928         CPT0063570003                             NaN
                  CPT0063580003                             NaN