# Pancancer enrichment analysis step 17: Visualize results from rSEA

## Setup

In [1]:
import os
import datetime
import altair as alt
import numpy as np
import pandas as pd
import operator
import IPython.display
from toolz.curried import pipe

In [13]:
TIME_START = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')

# Step 1 output
STEP01_DIR = "step01_outputs"
STEP01_FILE = "tumor_change_20200529_195104_10000_perm.tsv"
STEP01_FILE_PATH = os.path.join(STEP01_DIR, STEP01_FILE)

# Step 16 output
STEP16_DIR = "step16_outputs"
STEP16_thresh01 = os.path.join(STEP16_DIR, "enrichment_rsea_20200626_114446_thresh_0.1.tsv")

# Reactome .gmt file
REACTOME_GMT = os.path.join("gene_set_libraries", "Reactome_2020.gmt")

MSV = 0.5 # Simplified expression value for marginally significant proteins

In [3]:
# Altair options
alt.data_transformers.disable_max_rows()

def json_dir(data, data_dir):
    os.makedirs(data_dir, exist_ok=True)
    return pipe(data, alt.to_json(filename=os.path.join(data_dir, "{prefix}-{hash}.{extension}")) )

alt.data_transformers.register("json_dir", json_dir)
alt.data_transformers.enable("json_dir", data_dir="step17_altair_data")

DataTransformerRegistry.enable('json_dir')

## Read in data from step 16

In [4]:
enrichment_data = pd.read_csv(STEP16_thresh01, sep="\t", index_col=0)
enrichment_data.columns = enrichment_data.columns.str.replace(".", "_", regex=False)
enrichment_data

,Name,Size,Coverage,TDP_bound,TDP_estimate,SC_adjP,Comp_adjP,Comp_0_5_adjP,cancer_type
ID,,,,,,,,,
1,R-HSA-164843,13,0.69,0.444444,0.444444,0.0,1.000000,1.000000,ccrcc
2,R-HSA-73843,3,0.67,0.500000,0.500000,0.0,1.000000,1.000000,ccrcc
3,R-HSA-1971475,26,0.77,0.500000,0.500000,0.0,1.000000,1.000000,ccrcc
4,R-HSA-5619084,77,0.86,0.803030,0.818182,0.0,0.000000,0.000000,ccrcc
5,R-HSA-1369062,18,0.56,0.400000,0.400000,0.0,1.000000,1.000000,ccrcc
6,R-HSA-382556,103,0.84,0.712644,0.724138,0.0,0.000000,0.000000,ccrcc
7,R-HSA-9033807,3,0.33,0.000000,0.000000,1.0,1.000000,1.000000,ccrcc
8,R-HSA-9660821,134,0.31,0.666667,0.666667,0.0,0.504000,0.000000,ccrcc
9,R-HSA-418592,25,0.84,0.666667,0.666667,0.0,1.000000,0.000000,ccrcc
10,R-HSA-392170,22,0.77,0.705882,0.705882,0.0,0.000000,0.000000,ccrcc
11,R-HSA-198323,14,0.93,0.615385,0.692308,0.0,0.291400,0.000000,ccrcc
12,R-HSA-198693,10,0.80,0.625000,0.625000,0.0,0.922828,0.000000,ccrcc
13,R-HSA-211163,4,1.00,0.500000,0.500000,0.0,0.922828,0.922828,ccrcc
14,R-HSA-112122,1,1.00,1.000000,1.000000,0.0,0.000000,0.000000,ccrcc
15,R-HSA-112126,4,1.00,1.000000,1.000000,0.0,0.000000,0.000000,ccrcc
16,R-HSA-4839748,14,1.21,0.411765,0.411765,0.0,1.000000,1.000000,ccrcc
17,R-HSA-163680,8,1.00,0.500000,0.500000,0.0,1.000000,0.683400,ccrcc
18,R-HSA-5467333,1,2.00,0.000000,0.000000,1.0,1.000000,1.000000,ccrcc
19,R-HSA-5467337,14,1.21,0.411765,0.411765,0.0,1.000000,1.000000,ccrcc
20,R-HSA-179409,26,0.85,0.409091,0.545455,0.0,1.000000,0.401700,ccrcc
21,R-HSA-174143,88,0.91,0.700000,0.750000,0.0,0.000000,0.000000,ccrcc
22,R-HSA-174048,24,0.88,0.476190,0.571429,0.0,1.000000,0.291400,ccrcc
23,R-HSA-174154,68,0.93,0.746032,0.793651,0.0,0.000000,0.000000,ccrcc
24,R-HSA-176409,76,0.91,0.724638,0.782609,0.0,0.000000,0.000000,ccrcc
25,R-HSA-174178,74,0.95,0.700000,0.742857,0.0,0.000000,0.000000,ccrcc
26,R-HSA-179419,74,0.92,0.720588,0.779412,0.0,0.000000,0.000000,ccrcc
27,R-HSA-5649702,7,0.71,0.200000,0.200000,0.0,1.000000,1.000000,ccrcc
28,R-HSA-180689,11,0.55,0.666667,0.666667,0.0,1.000000,0.000000,ccrcc
29,R-HSA-5624958,3,1.00,0.333333,0.333333,0.0,1.000000,1.000000,ccrcc
30,R-HSA-170984,7,0.86,0.666667,0.666667,0.0,1.000000,0.000000,ccrcc
...,...,...,...,...,...,...,...,...,...
2371,R-HSA-372708,15,1.27,0.578947,0.578947,0.0,0.000000,0.000000,ovarian
2372,R-HSA-171007,13,1.08,0.357143,0.357143,0.0,0.000000,1.000000,ovarian
2373,R-HSA-69563,66,0.95,0.253968,0.269841,0.0,0.857000,1.000000,ovarian
2374,R-HSA-69580,66,0.95,0.253968,0.269841,0.0,0.857000,1.000000,ovarian
2375,R-HSA-69610,52,1.02,0.264151,0.283019,0.0,0.657600,1.000000,ovarian
2376,R-HSA-69613,52,1.02,0.264151,0.283019,0.0,0.657600,1.000000,ovarian
2377,R-HSA-193704,97,0.84,0.222222,0.234568,0.0,1.000000,1.000000,ovarian
2378,R-HSA-193670,6,0.67,0.750000,0.750000,0.0,0.000000,0.000000,ovarian
2379,R-HSA-209543,13,0.85,0.181818,0.181818,0.0,1.000000,1.000000,ovarian
2380,R-HSA-193697,9,1.00,0.555556,0.555556,0.0,0.000000,0.000000,ovarian
2381,R-HSA-193639,16,0.88,0.142857,0.142857,0.0,1.000000,1.000000,ovarian
2382,R-HSA-111995,2,1.00,0.000000,0.000000,1.0,1.000000,1.000000,ovarian
2383,R-HSA-4839743,15,1.00,0.133333,0.133333,0.0,1.000000,1.000000,ovarian
2384,R-HSA-6793080,8,0.75,0.000000,0.000000,1.0,1.000000,1.000000,ovarian
2385,R-HSA-6790901,63,0.92,0.293103,0.310345,0.0,0.527300,1.000000,ovarian
2386,R-HSA-72312,237,0.86,0.460784,0.500000,0.0,0.000000,0.527300,ovarian
2387,R-HSA-8868766,38,0.50,0.105263,0.105263,0.0,1.000000,1.000000,ovarian
2388,R-HSA-8868773,199,0.93,0.497297,0.535135,0.0,0.000000,0.133640,ovarian
2389,R-HSA-191859,53,1.02,0.333333,0.407407,0.0,0.000000,1.000000,ovarian
2390,R-HSA-2033515,1,1.00,0.000000,0.000000,1.0,1.000000,1.000000,ovarian
2391,R-HSA-379724,42,0.60,0.240000,0.240000,0.0,1.000000,1.000000,ovarian
2392,R-HSA-6787450,9,0.89,0.125000,0.125000,0.0,1.000000,1.000000,ovarian
2393,R-HSA-6782315,43,0.81,0.085714,0.085714,0.0,1.000000,1.000000,ovarian
2394,R-HSA-72306,146,0.74,0.231481,0.287037,0.0,0.718200,1.000000,ovarian
2395,R-HSA-6785470,42,0.33,0.214286,0.214286,0.0,1.000000,1.000000,ovarian
2396,R-HSA-6784531,59,0.97,0.350877,0.456140,0.0,0.000000,0.768167,ovarian
2397,R-HSA-199992,72,1.14,0.182927,0.231707,0.0,1.000000,1.000000,ovarian
2398,R-HSA-4839744,14,1.00,0.142857,0.142857,0.0,1.000000,1.000000,ovarian
2399,R-HSA-192814,6,0.17,1.000000,1.000000,0.0,0.000000,0.000000,ovarian
2400,R-HSA-192905,7,0.29,0.500000,0.500000,0.0,0.000000,1.000000,ovarian

In [5]:
alt.Chart(enrichment_data).mark_bar().encode(
    x=alt.X("Comp_adjP", bin=alt.Bin(step=0.05)),
    y="count()",
)

alt.Chart(...)

In [6]:
alt.Chart(enrichment_data).mark_bar().encode(
    x=alt.X("SC_adjP", bin=alt.Bin(step=0.05)),
    y="count()",
)

alt.Chart(...)

In [7]:
(enrichment_data["Comp_adjP"] == 0).sum()

7351

In [8]:
(enrichment_data["SC_adjP"] == 0).sum()

16174

## Figure 1: Bubble plot

In [48]:
def plot_top_ten(enrich_file_path, expr_file_path, gmt_file_path, xtitle, min_size, sort_col, sort_asc, cutoff_col, cutoff=0.05):
    
    # Read in the expression data
    all_expression_data = pd.read_csv(expr_file_path, sep="\t", index_col=0)

    # Make a column where all increases are +1 and all decreases 
    # are -1, because these are ratioed abundances, so we can't 
    # compare magnitudes between genes--we can only compare whether 
    # there was a change, and whether it was positive or negative
    all_expression_data = all_expression_data.assign(simplified_change=np.nan)

    # adj p < 0.05 and change > 1 => +1
    all_expression_data.loc[
        (all_expression_data["change"] > 0) & (all_expression_data["adj_p"] < 0.05), 
        "simplified_change"
    ] = 1

    # adj p >= 0.05 and change > 1 => +0.5
    all_expression_data.loc[(all_expression_data["change"] > 0) & (all_expression_data["adj_p"] >= 0.05),
        "simplified_change"
    ] = MSV

    # change == 0 => 0
    all_expression_data.loc[
        all_expression_data["change"] == 0,
        "simplified_change"
    ] = 0

    # adj p >= 0.05 and change < 1 => -0.5
    all_expression_data.loc[(all_expression_data["change"] < 0) & (all_expression_data["adj_p"] >= 0.05), 
        "simplified_change"
    ] = -MSV

    # adj p < 0.05 and change < 1 => -1
    all_expression_data.loc[
        (all_expression_data["change"] < 0) & (all_expression_data["adj_p"] < 0.05),
        "simplified_change"
    ] = -1

    # Select just the proteins where we chose to reject the null hypothesis of no change
    expression_data = all_expression_data[all_expression_data["reject_null"]]
    
    # Read in the GMT file and join in pathway names and gene lists
    with open(gmt_file_path, "r") as fp:
        gene_lists = fp.readlines()

    # Take the newline off the end, and split on the tab character to create a list of lists
    gene_lists = [l.strip().split("\t") for l in gene_lists]

    # Create a dataframe mapping pathway ID to pathway name and genes
    pathway_ids = [l[1] for l in gene_lists]
    pathway_names = [l[0] for l in gene_lists]
    pathway_genes = [l[2:] for l in gene_lists]
    pathway_data = pd.DataFrame({
        "pathway_id": pathway_ids,
        "pathway_name": pathway_names,
        "pathway_genes": pathway_genes
    })

    # Read in the enrichment data
    enrichment_data = pd.read_csv(enrich_file_path, sep="\t", index_col=0)
    enrichment_data.columns = enrichment_data.columns.str.replace(".", "_", regex=False)
    enrichment_data = enrichment_data.rename(columns={"Name": "pathway_id"})
    
    # Merge pathway data into the enrichment data
    enrichment_data = enrichment_data.merge(
        pathway_data,
        how="left",
        left_on="pathway_id",
        right_on="pathway_id",
        validate="many_to_one"
    )
    
    # Select pathways that meet the minimum size
    enrichment_data = enrichment_data[
        enrichment_data["pathway_genes"].apply(len) >= min_size
    ]

    # Select enrichment data below our cutoff
    enrichment_data = enrichment_data.loc[enrichment_data[cutoff_col] <= cutoff, :]
    
    # Assign pathway ranks within each cancer type based on the sort_col. Make a custom one if needed.
    if sort_col != cutoff_col:
        if sort_asc:
            enrichment_data = enrichment_data.assign(
                temp_sort=(enrichment_data[sort_col] + 0.1) * (enrichment_data[cutoff_col] + 0.1)
            )
        else:
            enrichment_data = enrichment_data.assign(
                temp_sort=(enrichment_data[sort_col] + 0.1) / (enrichment_data[cutoff_col] + 0.1)
            )
            
        sort_col = "temp_sort"
    
    enrichment_data = enrichment_data.\
        assign(cancer_rank=enrichment_data.groupby("cancer_type")[sort_col].rank(ascending=sort_asc)).\
        sort_values(by=["cancer_type", "cancer_rank"]).\
        reset_index(drop=True)

    # Make a table with summary info for all pathways
    enrichment_summary = enrichment_data[["pathway_id"]].drop_duplicates(keep="first")

    pathway_times_enriched = enrichment_summary["pathway_id"].apply(
        lambda x: enrichment_data[enrichment_data["pathway_id"] == x].shape[0])

    avg_rank = enrichment_summary["pathway_id"].apply(
        lambda x: enrichment_data.loc[enrichment_data["pathway_id"] == x, "cancer_rank"].mean())

    enrichment_summary = enrichment_summary.\
        assign(
            pathway_times_enriched=pathway_times_enriched,
            pathway_avg_rank=avg_rank).\
        sort_values(
            by=["pathway_times_enriched", "pathway_avg_rank"],
            ascending=[False, True]).\
        reset_index(drop=True)

    # Merge in the original enrichment data
    enrichment_data = enrichment_data.\
        merge(
            enrichment_summary,
            how="outer",
            left_on="pathway_id",
            right_on="pathway_id",
            validate="many_to_one"
        ).\
        sort_values(
            by=["pathway_times_enriched", "pathway_avg_rank", "cancer_type"],
            ascending=[False, True, True]
        )

    # Select top 10 for our plot
    in_all = enrichment_summary.loc[
        enrichment_summary["pathway_times_enriched"] == 8,
        "pathway_id"
    ]
    
    if in_all.size <= 10:
        top_ten = in_all
    else:
        top_ten = in_all[:10]
    
    sel_enrich = enrichment_data[enrichment_data["pathway_id"].isin(top_ten)]

    # Calculate the mean expression for each pathway in each cancer type
    mean_exprs = []

    for idx in sel_enrich.index:
        genes = sel_enrich.loc[idx, "pathway_genes"]
        cancer_type = sel_enrich.loc[idx, "cancer_type"]

        genes_expr = expression_data.loc[
            expression_data["protein_str"].isin(genes),
            "simplified_change"
        ].mean()

        mean_exprs.append(genes_expr)

    sel_enrich = sel_enrich.assign(mean_expr=mean_exprs)

    sel_enrich = sel_enrich.assign(
        rank_size=1 / sel_enrich["cancer_rank"],
        avg_rank_size=1 / sel_enrich["pathway_avg_rank"],
        avg_rank_label=sel_enrich["pathway_avg_rank"].apply(round, 2).astype(str))
    
    # Take care of duplicates for the upper plot
    for i in range(10):
        sel_enrich["avg_rank_label"] = sel_enrich["avg_rank_label"].where(
            cond=~(sel_enrich.duplicated(subset=["cancer_type", "avg_rank_label"], keep="first")),
            other=" " + sel_enrich["avg_rank_label"])

    individual = alt.Chart(sel_enrich).mark_circle().encode(
        x=alt.X(
            "pathway_name:N",
            sort=sel_enrich["pathway_name"].values,
            axis=alt.Axis(
                labelAngle=-30,
                labelFontSize=12,
                labelLimit=500,
                title="",
                titleFontSize=16
            )
        ),
        y=alt.Y(
            "cancer_type:N",
            axis=alt.Axis(
                title="Cancer type",
                titleFontSize=12
            ),
        ),
        size=alt.Size(
            "rank_size:Q",
            legend=None
        ),
        color=alt.Color(
            "mean_expr:Q",
            scale=alt.Scale(
                scheme="blueorange",
                domain=[-1, 1]
            ),
            legend=alt.Legend(
                title="Pathway tumor expression"
            )
        )
    ).properties(
        width=400,
        height=300
    )

    aggregate = alt.Chart(sel_enrich).mark_circle().encode(
        x=alt.X(
            "avg_rank_label:N",
            sort=sel_enrich["avg_rank_label"].values,
            axis=alt.Axis(
                labelAngle=-30,
                labelFontSize=12,
                labelLimit=500,
                title="Overall rank of pathway",
                titleFontSize=12
            )
        ),
        size=alt.Size(
            "avg_rank_size:Q",
            legend=None
        ),
    ).properties(
        width=400
    )

    full_plot = alt.vconcat(
        aggregate, individual
    ).properties(
        title=xtitle
    )
    
    return full_plot, enrichment_data, all_expression_data, enrichment_summary

In [52]:
alt.vconcat(
    plot_top_ten(
        enrich_file_path=STEP16_thresh01, 
        expr_file_path=STEP01_FILE_PATH, 
        gmt_file_path=REACTOME_GMT,
        xtitle="Reactome data - rSEA, threshold = 1, sort by Coverage / Comp_adjP, cutoff Comp_adjP",
        min_size=5,
        sort_col="Coverage",
        sort_asc=False,
        cutoff_col="Comp_adjP",
        cutoff=0.05
    )[0],
    plot_top_ten(
        enrich_file_path=STEP16_thresh01, 
        expr_file_path=STEP01_FILE_PATH, 
        gmt_file_path=REACTOME_GMT,
        xtitle="Reactome data - rSEA, threshold = 1, sort by Coverage / SC_adjP, cutoff SC_adjP",
        min_size=5,
        sort_col="Coverage",
        sort_asc=False,
        cutoff_col="SC_adjP",
        cutoff=0.05
    )[0],
).configure_axis(
    grid=True
).configure_title(
    fontSize=16,
    anchor="end",
    offset=20
).resolve_scale(
    size="independent"
)

alt.VConcatChart(...)

In [55]:
e = plot_top_ten(
    enrich_file_path=STEP16_thresh01, 
    expr_file_path=STEP01_FILE_PATH, 
    gmt_file_path=REACTOME_GMT,
    xtitle="Reactome data - rSEA, threshold = 1, sort by Coverage, cutoff Comp_adjP",
    min_size=5,
    sort_col="Coverage",
    sort_asc=False,
    cutoff_col="SC_adjP",
    cutoff=0.05
)[1]

In [57]:
e

,pathway_id,Size,Coverage,TDP_bound,TDP_estimate,SC_adjP,Comp_adjP,Comp_0_1_adjP,cancer_type,pathway_name,pathway_genes,temp_sort,cancer_rank,pathway_times_enriched,pathway_avg_rank
256,R-HSA-372708,15,1.20,0.500000,0.500000,0.0,1.000000,0.0,ccrcc,p130Cas linkage to MAPK signaling for integrins,"[APBB1IP, BCAR1, CRK, FGA, FGB, FGG, FN1, ITGA...",13.0,27.5,8,51.1875
257,R-HSA-372708,15,1.00,0.466667,0.466667,0.0,1.000000,0.0,colon,p130Cas linkage to MAPK signaling for integrins,"[APBB1IP, BCAR1, CRK, FGA, FGB, FGG, FN1, ITGA...",11.0,29.0,8,51.1875
258,R-HSA-372708,15,1.00,0.800000,0.800000,0.0,0.000000,0.0,endometrial,p130Cas linkage to MAPK signaling for integrins,"[APBB1IP, BCAR1, CRK, FGA, FGB, FGG, FN1, ITGA...",11.0,79.5,8,51.1875
259,R-HSA-372708,15,1.00,0.800000,0.800000,0.0,0.000000,0.0,gbm,p130Cas linkage to MAPK signaling for integrins,"[APBB1IP, BCAR1, CRK, FGA, FGB, FGG, FN1, ITGA...",11.0,84.5,8,51.1875
260,R-HSA-372708,15,1.00,0.533333,0.533333,0.0,0.989873,0.0,hnscc,p130Cas linkage to MAPK signaling for integrins,"[APBB1IP, BCAR1, CRK, FGA, FGB, FGG, FN1, ITGA...",11.0,115.5,8,51.1875
261,R-HSA-372708,15,1.20,0.777778,0.777778,0.0,0.000000,0.0,lscc,p130Cas linkage to MAPK signaling for integrins,"[APBB1IP, BCAR1, CRK, FGA, FGB, FGG, FN1, ITGA...",13.0,21.0,8,51.1875
262,R-HSA-372708,15,1.13,0.823529,0.823529,0.0,0.000000,0.0,luad,p130Cas linkage to MAPK signaling for integrins,"[APBB1IP, BCAR1, CRK, FGA, FGB, FGG, FN1, ITGA...",12.3,26.5,8,51.1875
263,R-HSA-372708,15,1.27,0.578947,0.578947,0.0,0.000000,0.0,ovarian,p130Cas linkage to MAPK signaling for integrins,"[APBB1IP, BCAR1, CRK, FGA, FGB, FGG, FN1, ITGA...",13.7,26.0,8,51.1875
0,R-HSA-264870,12,2.00,0.708333,0.750000,0.0,0.000000,0.0,ccrcc,Caspase-mediated cleavage of cytoskeletal prot...,"[ADD1, CASP3, CASP6, CASP7, CASP8, DBNL, GAS2,...",21.0,1.0,8,51.8125
1,R-HSA-264870,12,0.92,0.545455,0.636364,0.0,0.254300,0.0,colon,Caspase-mediated cleavage of cytoskeletal prot...,"[ADD1, CASP3, CASP6, CASP7, CASP8, DBNL, GAS2,...",10.2,130.0,8,51.8125
2,R-HSA-264870,12,1.00,0.833333,0.833333,0.0,0.000000,0.0,endometrial,Caspase-mediated cleavage of cytoskeletal prot...,"[ADD1, CASP3, CASP6, CASP7, CASP8, DBNL, GAS2,...",11.0,79.5,8,51.8125
3,R-HSA-264870,12,1.00,0.666667,0.666667,0.0,0.000000,0.0,gbm,Caspase-mediated cleavage of cytoskeletal prot...,"[ADD1, CASP3, CASP6, CASP7, CASP8, DBNL, GAS2,...",11.0,84.5,8,51.8125
4,R-HSA-264870,12,1.00,0.916667,0.916667,0.0,0.000000,0.0,hnscc,Caspase-mediated cleavage of cytoskeletal prot...,"[ADD1, CASP3, CASP6, CASP7, CASP8, DBNL, GAS2,...",11.0,115.5,8,51.8125
5,R-HSA-264870,12,2.00,0.708333,0.750000,0.0,0.238000,0.0,lscc,Caspase-mediated cleavage of cytoskeletal prot...,"[ADD1, CASP3, CASP6, CASP7, CASP8, DBNL, GAS2,...",21.0,1.0,8,51.8125
6,R-HSA-264870,12,1.83,0.636364,0.681818,0.0,0.589500,0.0,luad,Caspase-mediated cleavage of cytoskeletal prot...,"[ADD1, CASP3, CASP6, CASP7, CASP8, DBNL, GAS2,...",19.3,1.0,8,51.8125
7,R-HSA-264870,12,1.75,0.571429,0.571429,0.0,0.000000,0.0,ovarian,Caspase-mediated cleavage of cytoskeletal prot...,"[ADD1, CASP3, CASP6, CASP7, CASP8, DBNL, GAS2,...",18.5,2.0,8,51.8125
349,R-HSA-9673770,12,1.17,0.500000,0.571429,0.0,1.000000,0.0,ccrcc,Signaling by PDGFRA extracellular domain mutants,"[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",12.7,44.0,8,60.7500
357,R-HSA-9673767,12,1.17,0.500000,0.571429,0.0,1.000000,0.0,ccrcc,"Signaling by PDGFRA transmembrane, juxtamembra...","[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",12.7,44.0,8,60.7500
350,R-HSA-9673770,12,1.00,0.500000,0.583333,0.0,0.502378,0.0,colon,Signaling by PDGFRA extracellular domain mutants,"[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",11.0,29.0,8,60.7500
358,R-HSA-9673767,12,1.00,0.500000,0.583333,0.0,0.502378,0.0,colon,"Signaling by PDGFRA transmembrane, juxtamembra...","[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",11.0,29.0,8,60.7500
351,R-HSA-9673770,12,1.00,0.500000,0.500000,0.0,1.000000,0.0,endometrial,Signaling by PDGFRA extracellular domain mutants,"[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",11.0,79.5,8,60.7500
359,R-HSA-9673767,12,1.00,0.500000,0.500000,0.0,1.000000,0.0,endometrial,"Signaling by PDGFRA transmembrane, juxtamembra...","[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",11.0,79.5,8,60.7500
352,R-HSA-9673770,12,1.00,0.833333,0.833333,0.0,0.000000,0.0,gbm,Signaling by PDGFRA extracellular domain mutants,"[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",11.0,84.5,8,60.7500
360,R-HSA-9673767,12,1.00,0.833333,0.833333,0.0,0.000000,0.0,gbm,"Signaling by PDGFRA transmembrane, juxtamembra...","[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",11.0,84.5,8,60.7500
353,R-HSA-9673770,12,1.00,0.583333,0.583333,0.0,0.000000,0.0,hnscc,Signaling by PDGFRA extracellular domain mutants,"[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",11.0,115.5,8,60.7500
361,R-HSA-9673767,12,1.00,0.583333,0.583333,0.0,0.000000,0.0,hnscc,"Signaling by PDGFRA transmembrane, juxtamembra...","[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",11.0,115.5,8,60.7500
354,R-HSA-9673770,12,1.08,0.461538,0.461538,0.0,0.999400,0.0,lscc,Signaling by PDGFRA extracellular domain mutants,"[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",11.8,64.5,8,60.7500
362,R-HSA-9673767,12,1.08,0.461538,0.461538,0.0,0.999400,0.0,lscc,"Signaling by PDGFRA transmembrane, juxtamembra...","[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",11.8,64.5,8,60.7500
355,R-HSA-9673770,12,1.17,0.714286,0.714286,0.0,0.000000,0.0,luad,Signaling by PDGFRA extracellular domain mutants,"[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",12.7,20.0,8,60.7500
363,R-HSA-9673767,12,1.17,0.714286,0.714286,0.0,0.000000,0.0,luad,"Signaling by PDGFRA transmembrane, juxtamembra...","[GRB2, HRAS, KRAS, NRAS, PDGFRA, PIK3CA, PIK3C...",12.7,20.0,8,60.7500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11421,R-HSA-433137,5,0.20,1.000000,1.000000,0.0,0.000000,0.0,gbm,"Sodium-coupled sulphate, di- and tri-carboxyla...","[SLC13A1, SLC13A2, SLC13A3, SLC13A4, SLC13A5]",3.0,1721.5,2,1586.0000
12904,R-HSA-209931,5,0.40,0.500000,0.500000,0.0,1.000000,0.0,ccrcc,Serotonin and melatonin biosynthesis,"[AANAT, ASMT, DDC, TPH1, TPH2]",5.0,1653.0,2,1662.0000
12905,R-HSA-209931,5,0.20,1.000000,1.000000,0.0,0.000000,0.0,colon,Serotonin and melatonin biosynthesis,"[AANAT, ASMT, DDC, TPH1, TPH2]",3.0,1671.0,2,1662.0000
14006,R-HSA-2187335,7,0.14,1.000000,1.000000,0.0,0.000000,0.0,endometrial,The retinoid cycle in cones (daylight vision),"[AWAT2, DHRS3, OPN1LW, OPN1MW, OPN1SW, RBP3, R...",2.4,1732.0,2,1706.7500
14007,R-HSA-2187335,7,0.29,0.500000,0.500000,0.0,1.000000,0.0,gbm,The retinoid cycle in cones (daylight vision),"[AWAT2, DHRS3, OPN1LW, OPN1MW, OPN1SW, RBP3, R...",3.9,1681.5,2,1706.7500
13924,R-HSA-375280,43,0.05,0.500000,0.500000,0.0,1.000000,0.0,ccrcc,Amine ligand-binding receptors,"[ADRA1A, ADRA1B, ADRA1D, ADRA2A, ADRA2B, ADRA2...",1.5,1809.0,2,1776.7500
13925,R-HSA-375280,43,0.12,0.800000,0.800000,0.0,0.000000,0.0,gbm,Amine ligand-binding receptors,"[ADRA1A, ADRA1B, ADRA1D, ADRA2A, ADRA2B, ADRA2...",2.2,1744.5,2,1776.7500
1915,R-HSA-561048,5,1.00,1.000000,1.000000,0.0,0.000000,0.0,ccrcc,Organic anion transport,"[SLC22A11, SLC22A12, SLC22A6, SLC22A7, SLC22A8]",11.0,233.0,1,233.0000
14008,R-HSA-5576894,7,0.86,0.833333,0.833333,0.0,0.000000,0.0,gbm,Phase 1 - inactivation of fast Na+ channels,"[KCND1, KCND2, KCND3, KCNIP1, KCNIP2, KCNIP3, ...",9.6,697.5,1,697.5000
14019,R-HSA-9014826,7,0.86,0.500000,0.500000,0.0,1.000000,0.0,hnscc,Interleukin-36 pathway,"[IL1F10, IL1RAP, IL1RL2, IL36A, IL36B, IL36G, ...",9.6,780.0,1,780.0000
14009,R-HSA-390648,5,0.60,1.000000,1.000000,0.0,0.000000,0.0,gbm,Muscarinic acetylcholine receptors,"[CHRM1, CHRM2, CHRM3, CHRM4, CHRM5]",7.0,1376.5,1,1376.5000
14010,R-HSA-187024,5,0.60,0.333333,0.666667,0.0,0.321200,0.0,gbm,NGF-independant TRKA activation,"[ADCYAP1, ADCYAP1R1, ADORA2A, NTRK1, NTRK2]",7.0,1376.5,1,1376.5000
14011,R-HSA-187015,6,0.50,0.333333,0.666667,0.0,0.321200,0.0,gbm,Activation of TRKA receptors,"[ADCYAP1, ADCYAP1R1, ADORA2A, NGF, NTRK1, NTRK2]",6.0,1515.0,1,1515.0000
14012,R-HSA-380095,5,0.40,0.500000,0.500000,0.0,1.000000,0.0,gbm,Tachykinin receptors bind tachykinins,"[TAC1, TAC3, TACR1, TACR2, TACR3]",5.0,1598.0,1,1598.0000
14013,R-HSA-167826,5,0.40,1.000000,1.000000,0.0,0.000000,0.0,gbm,The fatty acid cycling model,"[SLC25A14, SLC25A27, UCP1, UCP2, UCP3]",5.0,1598.0,1,1598.0000
14014,R-HSA-167827,5,0.40,1.000000,1.000000,0.0,0.000000,0.0,gbm,The proton buffering model,"[SLC25A14, SLC25A27, UCP1, UCP2, UCP3]",5.0,1598.0,1,1598.0000
14015,R-HSA-166187,6,0.33,1.000000,1.000000,0.0,0.000000,0.0,gbm,Mitochondrial Uncoupling,"[PM20D1, SLC25A14, SLC25A27, UCP1, UCP2, UCP3]",4.3,1651.5,1,1651.5000
14016,R-HSA-418038,16,0.31,0.200000,0.200000,0.0,1.000000,0.0,gbm,Nucleotide-like (purinergic) receptors,"[ADORA1, ADORA2A, ADORA2B, ADORA3, GPR17, LPAR...",4.1,1665.0,1,1665.0000
14001,R-HSA-5576890,8,0.25,0.500000,0.500000,0.0,1.000000,0.0,endometrial,Phase 3 - rapid repolarisation,"[AKAP9, KCNE1, KCNE2, KCNE3, KCNE4, KCNE5, KCN...",3.5,1683.5,1,1683.5000
13206,R-HSA-211916,6,0.33,1.000000,1.000000,0.0,0.000000,0.0,ccrcc,Vitamins,"[CYP24A1, CYP26A1, CYP26B1, CYP26C1, CYP27B1, ...",4.3,1697.0,1,1697.0000
14027,R-HSA-210746,5,0.20,1.000000,1.000000,0.0,0.000000,0.0,lscc,Regulation of gene expression in endocrine-com...,"[INSM1, NEUROD1, NEUROG3, NKX2-2, PAX4]",3.0,1752.0,1,1752.0000
14017,R-HSA-390666,12,0.08,1.000000,1.000000,0.0,0.000000,0.0,gbm,Serotonin receptors,"[HTR1A, HTR1B, HTR1D, HTR1E, HTR1F, HTR2A, HTR...",1.8,1754.0,1,1754.0000
14018,R-HSA-5576886,19,0.05,1.000000,1.000000,0.0,0.000000,0.0,gbm,Phase 4 - resting membrane potential,"[KCNJ12, KCNJ14, KCNJ2, KCNJ4, KCNK1, KCNK10, ...",1.5,1756.0,1,1756.0000
13607,R-HSA-391908,9,0.22,1.000000,1.000000,0.0,0.000000,0.0,ccrcc,Prostanoid ligand receptors,"[PTGDR, PTGDR2, PTGER1, PTGER2, PTGER3, PTGER4...",3.2,1758.5,1,1758.5000
14028,R-HSA-629587,7,0.14,1.000000,1.000000,0.0,0.000000,0.0,luad,Highly sodium permeable postsynaptic acetylcho...,"[CHRNA3, CHRNA4, CHRNB2, CHRNB4, CHRND, CHRNE,...",2.4,1768.5,1,1768.5000
14029,R-HSA-622323,12,0.08,1.000000,1.000000,0.0,0.000000,0.0,luad,Presynaptic nicotinic acetylcholine receptors,"[CHRNA1, CHRNA2, CHRNA3, CHRNA4, CHRNA5, CHRNA...",1.8,1787.5,1,1787.5000
13819,R-HSA-391903,15,0.13,1.000000,1.000000,0.0,0.000000,0.0,ccrcc,Eicosanoid ligand-binding receptors,"[CYSLTR1, CYSLTR2, GPR17, LTB4R, LTB4R2, OXER1...",2.3,1791.0,1,1791.0000
14030,R-HSA-181431,14,0.07,1.000000,1.000000,0.0,0.000000,0.0,luad,Acetylcholine binding and downstream events,"[CHRNA1, CHRNA2, CHRNA3, CHRNA4, CHRNA5, CHRNA...",1.7,1791.0,1,1791.0000
14031,R-HSA-622327,14,0.07,1.000000,1.000000,0.0,0.000000,0.0,luad,Postsynaptic nicotinic acetylcholine receptors,"[CHRNA1, CHRNA2, CHRNA3, CHRNA4, CHRNA5, CHRNA...",1.7,1791.0,1,1791.0000
13854,R-HSA-390696,9,0.11,1.000000,1.000000,0.0,0.000000,0.0,ccrcc,Adrenoceptors,"[ADRA1A, ADRA1B, ADRA1D, ADRA2A, ADRA2B, ADRA2...",2.1,1799.0,1,1799.0000

In [56]:
e[e["pathway_name"] == "Neutrophil degranulation"]

,pathway_id,Size,Coverage,TDP_bound,TDP_estimate,SC_adjP,Comp_adjP,Comp_0_1_adjP,cancer_type,pathway_name,pathway_genes,temp_sort,cancer_rank,pathway_times_enriched,pathway_avg_rank
3534,R-HSA-6798695,479,0.93,0.720358,0.751678,0.0,0.000000,0.0,ccrcc,Neutrophil degranulation,"[A1BG, ABCA13, ACAA1, ACLY, ACP3, ACTR10, ACTR...",10.3,453.0,8,396.4375
3535,R-HSA-6798695,479,0.85,0.538272,0.617284,0.0,0.448200,0.0,colon,Neutrophil degranulation,"[A1BG, ABCA13, ACAA1, ACLY, ACP3, ACTR10, ACTR...",9.5,301.5,8,396.4375
3536,R-HSA-6798695,479,0.89,0.491803,0.566745,0.0,0.194133,0.0,endometrial,Neutrophil degranulation,"[A1BG, ABCA13, ACAA1, ACLY, ACP3, ACTR10, ACTR...",9.9,525.5,8,396.4375
3537,R-HSA-6798695,479,0.90,0.506944,0.601852,0.0,0.711143,0.0,gbm,Neutrophil degranulation,"[A1BG, ABCA13, ACAA1, ACLY, ACP3, ACTR10, ACTR...",10.0,488.5,8,396.4375
3538,R-HSA-6798695,479,0.94,0.529018,0.589286,0.0,0.074486,0.0,hnscc,Neutrophil degranulation,"[A1BG, ABCA13, ACAA1, ACLY, ACP3, ACTR10, ACTR...",10.4,402.0,8,396.4375
3539,R-HSA-6798695,479,0.94,0.659292,0.725664,0.0,0.747742,0.0,lscc,Neutrophil degranulation,"[A1BG, ABCA13, ACAA1, ACLY, ACP3, ACTR10, ACTR...",10.4,262.0,8,396.4375
3540,R-HSA-6798695,479,0.91,0.635945,0.714286,0.0,0.386400,0.0,luad,Neutrophil degranulation,"[A1BG, ABCA13, ACAA1, ACLY, ACP3, ACTR10, ACTR...",10.1,284.5,8,396.4375
3541,R-HSA-6798695,479,0.94,0.265487,0.362832,0.0,0.229047,0.0,ovarian,Neutrophil degranulation,"[A1BG, ABCA13, ACAA1, ACLY, ACP3, ACTR10, ACTR...",10.4,454.5,8,396.4375