# Pancancer enrichment analysis step 2: Find enriched pathways using Reactome's Analysis Service API for enrichment analysis

## Setup

In [1]:
import cptac
import cptac.utils as ut
import pandas as pd
import numpy as np
import os
import datetime

In [2]:
TIME_START = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')

STEP1_DIR = "step1_outputs"
STEP1_FILE = "tumor_change_20200529_195104_10000_perm.tsv"
STEP1_FILE_PATH = os.path.join(STEP1_DIR, STEP1_FILE)

STEP2_DIR = "step2_outputs"
STEP2_FILE = f"enrichment_reactome_{TIME_START}_from_{STEP1_FILE.rsplit('.', maxsplit=1)[0]}.tsv"
STEP2_FILE_PATH = os.path.join(STEP2_DIR, STEP2_FILE)

if not os.path.isdir(STEP2_DIR):
    os.mkdir(STEP2_DIR)

## Prepare data

In [3]:
# Read in the file from step 1
data = pd.read_csv(STEP1_FILE_PATH, sep='\t', index_col=0)

# The ranked enrichment analysis service wants ranking scores
# where "bigger is better", such as expression values or
# t scores. We are ranking by adjusted p-values, where smaller
# is better. So, we'll create a column of (1 - adj_p) to use
# for ranking.
data = data.assign(one_minus_adj_p=1 - data["adj_p"])

# Make a column where all increases are +1 and all decreases 
# are -1, because these are ratioed abundances, so we can't 
# compare magnitudes between genes--we can only compare whether 
# there was a change, and whether it was positive or negative
data = data.assign(simplified_change=data["change"])

data.loc[data["change"] > 0, "simplified_change"] = 1
data.loc[data["change"] < 0, "simplified_change"] = -1
data.loc[data["change"] == 0, "simplified_change"] = 0

In [4]:
data.head()

,cancer_type,protein,change,P_val,adj_p,reject_null,protein_str,one_minus_adj_p,simplified_change
0,ccrcc,"('A1BG', 'NP_570602.2')",0.282928,0.0000,0.00000,True,A1BG,1.00000,1.0
1,ccrcc,"('A1CF', 'NP_620310.1')",-0.551358,0.0000,0.00000,True,A1CF,1.00000,-1.0
2,ccrcc,"('A2M', 'NP_000005.2')",0.595512,0.0000,0.00000,True,A2M,1.00000,1.0
3,ccrcc,"('A4GALT', 'NP_001304967.1')",0.479410,0.1735,0.21431,False,A4GALT,0.78569,1.0
4,ccrcc,"('AAAS', 'NP_056480.1')",0.173579,0.0000,0.00000,True,AAAS,1.00000,1.0

## Run enrichment analysis

In [5]:
# For each cancer, find enriched pathways based on p value for differential expression   
all_enrichments = pd.DataFrame()

for cancer_type in data["cancer_type"].unique():
    
    ranked_data = data.loc[data["cancer_type"] == cancer_type, ["protein_str", "one_minus_adj_p"]].\
        set_index("protein_str").\
        rename(columns={"one_minus_adj_p": f"{cancer_type}_one_minus_adj_p"})

    unneeded_token, cancer_enriched = ut.reactome_enrichment_analysis(
        analysis_type="ranked", 
        data=ranked_data, 
        sort_by="ENTITIES_FDR", 
        ascending=True,
        include_high_level_diagrams=False, 
        include_interactors=False)
    
    # Record the cancer type and rename the pathway id column
    cancer_enriched = cancer_enriched.\
        assign(cancer_type=cancer_type).\
        rename(columns={"stId": "pathway_id"})
    
    # Append to the overall dataframe
    all_enrichments = all_enrichments.append(cancer_enriched)

In [6]:
# Drop columns we don't need
all_enrichments = all_enrichments.drop(columns=["entities_ratio", "entities_found", "entities_total"])

In [7]:
# Assign pathway ranks within each cancer type based on p value
# We use p value instead of FDR because they will both put the pathways
# in the same order, but the p values are more precise for ranking--some
# pathways that have the same FDR have different p values, so we get
# more specific ranks from the p values.

all_enrichments = all_enrichments.\
    assign(cancer_rank_pval=all_enrichments.groupby("cancer_type")["entities_pValue"].rank()).\
    sort_values(by=["cancer_type", "cancer_rank_pval"]).\
    reset_index(drop=True)

## Summarize enrichment results from all cancers

In [8]:
enrichment_summary = all_enrichments[["pathway_id", "name"]].drop_duplicates(keep="first")

pathway_times_enriched = enrichment_summary["pathway_id"].apply(
    lambda x: all_enrichments[all_enrichments["pathway_id"] == x].shape[0])

avg_rank = enrichment_summary["pathway_id"].apply(
    lambda x: all_enrichments.loc[all_enrichments["pathway_id"] == x, "cancer_rank_pval"].mean())

enrichment_summary = enrichment_summary.\
    assign(
        pathway_times_enriched=pathway_times_enriched,
        pathway_avg_rank=avg_rank).\
    sort_values(
        by=["pathway_times_enriched", "pathway_avg_rank"],
        ascending=[False, True]).\
    reset_index(drop=True)

In [9]:
enrichment_summary

,pathway_id,name,pathway_times_enriched,pathway_avg_rank
0,R-HSA-6798695,Neutrophil degranulation,8,1.000000
1,R-HSA-6791226,Major pathway of rRNA processing in the nucleo...,8,2.875000
2,R-HSA-72163,mRNA Splicing - Major Pathway,8,5.375000
3,R-HSA-72172,mRNA Splicing,8,10.500000
4,R-HSA-72689,Formation of a pool of free 40S subunits,8,12.750000
5,R-HSA-1236977,Endosomal/Vacuolar pathway,8,13.625000
6,R-HSA-927802,Nonsense-Mediated Decay (NMD),8,17.750000
7,R-HSA-975957,Nonsense Mediated Decay (NMD) enhanced by the ...,8,17.750000
8,R-HSA-72203,Processing of Capped Intron-Containing Pre-mRNA,8,18.500000
9,R-HSA-1799339,SRP-dependent cotranslational protein targetin...,8,20.500000
10,R-HSA-72706,GTP hydrolysis and joining of the 60S ribosoma...,8,21.000000
11,R-HSA-975956,Nonsense Mediated Decay (NMD) independent of t...,8,22.250000
12,R-HSA-156827,L13a-mediated translational silencing of Cerul...,8,31.500000
13,R-HSA-5419276,Mitochondrial translation termination,8,32.062500
14,R-HSA-5389840,Mitochondrial translation elongation,8,34.187500
15,R-HSA-114608,Platelet degranulation,8,35.125000
16,R-HSA-983169,Class I MHC mediated antigen processing & pres...,8,36.875000
17,R-HSA-72613,Eukaryotic Translation Initiation,8,45.000000
18,R-HSA-72737,Cap-dependent Translation Initiation,8,45.000000
19,R-HSA-76005,Response to elevated platelet cytosolic Ca2+,8,45.062500
20,R-HSA-5368287,Mitochondrial translation,8,49.500000
21,R-HSA-2132295,MHC class II antigen presentation,8,51.375000
22,R-HSA-156902,Peptide chain elongation,8,57.875000
23,R-HSA-72187,mRNA 3'-end processing,8,58.000000
24,R-HSA-983170,"Antigen Presentation: Folding, assembly and pe...",8,58.312500
25,R-HSA-72649,Translation initiation complex formation,8,60.312500
26,R-HSA-5368286,Mitochondrial translation initiation,8,60.500000
27,R-HSA-156842,Eukaryotic Translation Elongation,8,62.812500
28,R-HSA-72695,"Formation of the ternary complex, and subseque...",8,62.875000
29,R-HSA-68877,Mitotic Prometaphase,8,67.125000
...,...,...,...,...
2188,R-HSA-5619094,Variant SLC6A14 may confer susceptibility towa...,4,2034.625000
2189,R-HSA-5688354,Defective pro-SFTPC causes pulmonary surfactan...,3,451.666667
2190,R-HSA-5467343,Deletions in the AMER1 gene destabilize the de...,3,496.500000
2191,R-HSA-5690338,Defective ABCC6 causes pseudoxanthoma elasticu...,3,1471.333333
2192,R-HSA-5683177,Defective ABCC8 can cause hypoglycemias and hy...,3,1474.666667
2193,R-HSA-5619047,Defective SLC2A9 causes hypouricemia renal 2 (...,3,1490.333333
2194,R-HSA-3296197,Hydroxycarboxylic acid-binding receptors,3,1629.500000
2195,R-HSA-5659898,Intestinal saccharidase deficiencies,3,1808.666667
2196,R-HSA-163316,Mitochondrial transcription termination,2,557.500000
2197,R-HSA-1299344,TWIK-related spinal cord K+ channel (TRESK),2,863.250000
2198,R-HSA-5619110,"Defective SLCO1B1 causes hyperbilirubinemia, R...",2,1021.750000
2199,R-HSA-5660686,Variant SLC6A20 contributes towards hyperglyci...,2,1259.000000
2200,R-HSA-5619101,Variant SLC6A20 contributes towards hyperglyci...,2,1259.000000
2201,R-HSA-5619087,Defective SLC12A3 causes Gitelman syndrome (GS),2,1297.500000
2202,R-HSA-5619097,Defective SLC34A3 causes Hereditary hypophosph...,2,1297.500000
2203,R-HSA-5619114,Defective SLC5A7 causes distal hereditary moto...,2,1509.000000
2204,R-HSA-5658471,Defective SLC5A7 causes distal hereditary moto...,2,1509.000000
2205,R-HSA-210746,Regulation of gene expression in endocrine-com...,2,1567.000000
2206,R-HSA-3359463,Defective CUBN causes hereditary megaloblastic...,1,1062.000000
2207,R-HSA-3359462,Defective AMN causes hereditary megaloblastic ...,1,1062.000000
2208,R-HSA-5619085,Defective SLC26A3 causes congenital secretory ...,1,1233.500000
2209,R-HSA-5619071,Defective SLC22A12 causes renal hypouricemia 1...,1,1292.500000
2210,R-HSA-5619040,Defective SLC34A1 causes hypophosphatemic neph...,1,1292.500000
2211,R-HSA-1839128,FGFR4 mutant receptor activation,1,1507.000000
2212,R-HSA-5619041,Defective SLC36A2 causes iminoglycinuria (IG) ...,1,1507.000000
2213,R-HSA-5619104,Defective SLC12A1 causes Bartter syndrome 1 (BS1),1,1507.000000
2214,R-HSA-5619098,Defective SLC2A2 causes Fanconi-Bickel syndrom...,1,1507.000000
2215,R-HSA-2160456,Phenylketonuria,1,1648.000000
2216,R-HSA-5659735,Defective SLC6A19 causes Hartnup disorder (HND),1,2035.000000
2217,R-HSA-5619044,Defective SLC6A19 causes Hartnup disorder (HND),1,2035.000000

## Visualize pathways with expression change

In [10]:
# Submit the differential expression data for each cancer type to the analysis service, and get the tokens
# The data we'd submitted previously were the p values for the differential expression, but that's not what
# we want to visualize; we want to see whether the expression was up or down.
diff_expr_tokens = {}

for cancer_type in data["cancer_type"].unique():

    # Select data for that cancer type
    # Exclude samples where not reject_null
    omics = data.loc[(data["cancer_type"] == cancer_type) & data["reject_null"], 
                     ["protein_str", "simplified_change"]].\
        set_index("protein_str").\
        rename(columns={"simplified_change": f"{cancer_type}_simp_change"})

    analysis_token, unneeded_df = ut.reactome_enrichment_analysis(
        analysis_type="ranked", 
        data=omics, 
        sort_by="ENTITIES_FDR", 
        ascending=True,
        include_high_level_diagrams=True, 
        include_interactors=False)
    
    diff_expr_tokens[cancer_type] = analysis_token

In [11]:
# Select pathways to get URLs for
to_viz = enrichment_summary.iloc[0:10, :]

# Get URLs
id_list = []
cancer_type_list = []
expr_list = []
url_list = []

for idx in to_viz.index:
    pathway_id = to_viz.loc[idx, "pathway_id"]
    
    for cancer_type in data["cancer_type"].unique():
         
        # Get the URL
        expr_vals, url = ut.reactome_pathway_overlay(
            pathway=pathway_id,
            analysis_token=diff_expr_tokens[cancer_type],
            open_browser=False)
        
        id_list.append(pathway_id)
        cancer_type_list.append(cancer_type)
        expr_list.append(expr_vals[0])
        url_list.append(url)

In [12]:
# Put all the urls in a dataframe
urls_df = pd.DataFrame({
        "pathway_id": id_list,
        "cancer_type": cancer_type_list,
        "mean_expr": expr_list,
        "url": url_list})

# Join in the enrichment summary table
urls_df = urls_df.merge(
    enrichment_summary,
    how="left",
    left_on="pathway_id",
    right_on="pathway_id",
    validate="many_to_one")

# Join in the original enrichment data for each pathway and cancer type
urls_df = urls_df.merge(
    all_enrichments,
    how="left",
    left_on=["pathway_id", "name", "cancer_type"],
    right_on=["pathway_id", "name", "cancer_type"],
    validate="one_to_one")

In [13]:
# Print the dataframe in such a way that the links are clickable
urls_df.style.format('<a href="{0}">{0}</a>', subset="url")

In [14]:
# Save the results
urls_df.to_csv(STEP2_FILE_PATH, sep='\t')