# Pancancer enrichment analysis step 3: Make figures from Reactome data

## Setup

In [1]:
import cptac
import cptac.utils as ut
import os
import datetime
import altair as alt
import numpy as np
import pandas as pd

In [2]:
TIME_START = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')

STEP1_DIR = "step1_outputs"
STEP1_FILE = "tumor_change_20200529_195104_10000_perm.tsv"
STEP1_FILE_PATH = os.path.join(STEP1_DIR, STEP1_FILE)

STEP2_DIR = "step2_outputs"
STEP2_FILE = "enrichment_20200609_171630_from_tumor_change_20200529_195104_10000_perm.tsv"
STEP2_FILE_PATH = os.path.join(STEP2_DIR, STEP2_FILE)

## Read in data from steps 1 and 2

In [3]:
expression_data = pd.read_csv(STEP1_FILE_PATH, sep="\t", index_col=0)

# Select just the proteins where we chose to reject the null hypothesis of no change
expression_data = expression_data[expression_data["reject_null"]]

# Make a column where all increases are +1 and all decreases 
# are -1, because these are ratioed abundances, so we can't 
# compare magnitudes between genes--we can only compare whether 
# there was a change, and whether it was positive or negative
expression_data = expression_data.assign(simplified_change=expression_data["change"])

expression_data.loc[expression_data["change"] > 0, "simplified_change"] = 1
expression_data.loc[expression_data["change"] < 0, "simplified_change"] = -1
expression_data.loc[expression_data["change"] == 0, "simplified_change"] = 0

expression_data

,cancer_type,protein,change,P_val,adj_p,reject_null,protein_str,simplified_change
0,ccrcc,"('A1BG', 'NP_570602.2')",0.282928,0.0000,0.000000,True,A1BG,1.0
1,ccrcc,"('A1CF', 'NP_620310.1')",-0.551358,0.0000,0.000000,True,A1CF,-1.0
2,ccrcc,"('A2M', 'NP_000005.2')",0.595512,0.0000,0.000000,True,A2M,1.0
4,ccrcc,"('AAAS', 'NP_056480.1')",0.173579,0.0000,0.000000,True,AAAS,1.0
5,ccrcc,"('AACS', 'NP_076417.2')",-0.215967,0.0000,0.000000,True,AACS,-1.0
7,ccrcc,"('AADAT', 'NP_001273612.1')",-1.818291,0.0000,0.000000,True,AADAT,-1.0
8,ccrcc,"('AAED1', 'NP_714542.1')",0.426052,0.0000,0.000000,True,AAED1,1.0
9,ccrcc,"('AAGAB', 'NP_078942.3')",-0.070117,0.0009,0.001554,True,AAGAB,-1.0
10,ccrcc,"('AAK1', 'NP_055726.3')",-0.307917,0.0000,0.000000,True,AAK1,-1.0
11,ccrcc,"('AAMP', 'NP_001078.2')",0.328956,0.0000,0.000000,True,AAMP,1.0
12,ccrcc,"('AAR2', 'NP_001258803.1')",0.260477,0.0000,0.000000,True,AAR2,1.0
13,ccrcc,"('AARS', 'NP_001596.2')",0.171212,0.0000,0.000000,True,AARS,1.0
14,ccrcc,"('AARS2', 'NP_065796.1')",-0.084635,0.0102,0.015459,True,AARS2,-1.0
15,ccrcc,"('AARSD1', 'NP_001248363.1')",0.217840,0.0000,0.000000,True,AARSD1,1.0
18,ccrcc,"('AASS', 'NP_005754.2')",-1.614744,0.0000,0.000000,True,AASS,-1.0
19,ccrcc,"('AATF', 'NP_036270.1')",0.388488,0.0000,0.000000,True,AATF,1.0
20,ccrcc,"('ABAT', 'NP_000654.2')",-2.250937,0.0000,0.000000,True,ABAT,-1.0
21,ccrcc,"('ABCA1', 'NP_005493.2')",0.558242,0.0000,0.000000,True,ABCA1,1.0
22,ccrcc,"('ABCA12', 'NP_056472.2')",0.249142,0.0036,0.005803,True,ABCA12,1.0
23,ccrcc,"('ABCA2', 'NP_997698.1')",-0.130617,0.0033,0.005344,True,ABCA2,-1.0
27,ccrcc,"('ABCA8', 'NP_001275914.1')",-0.828206,0.0000,0.000000,True,ABCA8,-1.0
28,ccrcc,"('ABCB1', 'NP_001335874.1')",-1.318350,0.0000,0.000000,True,ABCB1,-1.0
29,ccrcc,"('ABCB10', 'NP_036221.2')",0.159938,0.0009,0.001554,True,ABCB10,1.0
31,ccrcc,"('ABCB6', 'NP_001336757.1')",0.767842,0.0000,0.000000,True,ABCB6,1.0
32,ccrcc,"('ABCB7', 'NP_001258625.1')",0.264838,0.0006,0.001056,True,ABCB7,1.0
33,ccrcc,"('ABCB8', 'NP_001269222.1')",-0.905600,0.0000,0.000000,True,ABCB8,-1.0
35,ccrcc,"('ABCC1', 'NP_004987.2')",0.768937,0.0000,0.000000,True,ABCC1,1.0
37,ccrcc,"('ABCC2', 'NP_000383.2')",-0.844046,0.0000,0.000000,True,ABCC2,-1.0
38,ccrcc,"('ABCC3', 'NP_003777.2')",1.082877,0.0000,0.000000,True,ABCC3,1.0
39,ccrcc,"('ABCC4', 'NP_005836.2')",0.166389,0.0007,0.001223,True,ABCC4,1.0
...,...,...,...,...,...,...,...,...
86206,ovarian,"('ZNF766', 'NP_001010851')",0.376720,0.0000,0.000000,True,ZNF766,1.0
86207,ovarian,"('ZNF768', 'NP_078947')",0.310335,0.0001,0.000188,True,ZNF768,1.0
86213,ovarian,"('ZNF782', 'NP_001001662')",0.446067,0.0001,0.000188,True,ZNF782,1.0
86214,ovarian,"('ZNF787', 'NP_001002836')",-0.384200,0.0007,0.001223,True,ZNF787,-1.0
86215,ovarian,"('ZNF791', 'NP_699189')",0.412204,0.0001,0.000188,True,ZNF791,1.0
86217,ovarian,"('ZNF8', 'NP_066575')",-0.554608,0.0003,0.000544,True,ZNF8,-1.0
86220,ovarian,"('ZNF805', 'NP_001018857')",-0.924069,0.0001,0.000188,True,ZNF805,-1.0
86221,ovarian,"('ZNF808', 'NP_001034975')",0.298169,0.0013,0.002207,True,ZNF808,1.0
86222,ovarian,"('ZNF813', 'NP_001004301')",0.376348,0.0000,0.000000,True,ZNF813,1.0
86223,ovarian,"('ZNF814', 'NP_001138461')",0.324113,0.0059,0.009242,True,ZNF814,1.0
86224,ovarian,"('ZNF816', 'NP_001026835')",0.374539,0.0000,0.000000,True,ZNF816,1.0
86225,ovarian,"('ZNF823', 'NP_001073962')",0.464786,0.0002,0.000368,True,ZNF823,1.0
86226,ovarian,"('ZNF827', 'NP_001293144')",-0.411539,0.0140,0.020818,True,ZNF827,-1.0
86228,ovarian,"('ZNF84', 'NP_001120844')",-0.952783,0.0000,0.000000,True,ZNF84,-1.0
86229,ovarian,"('ZNF865', 'NP_001182534')",-0.400890,0.0064,0.009973,True,ZNF865,-1.0
86230,ovarian,"('ZNF90', 'NP_009069')",0.360028,0.0000,0.000000,True,ZNF90,1.0
86231,ovarian,"('ZNF93', 'NP_112495')",0.352226,0.0000,0.000000,True,ZNF93,1.0
86232,ovarian,"('ZNF98', 'NP_001092096')",0.337325,0.0002,0.000368,True,ZNF98,1.0
86236,ovarian,"('ZNHIT3', 'NP_004764')",-0.382495,0.0183,0.026760,True,ZNHIT3,-1.0
86237,ovarian,"('ZNHIT6', 'NP_060423')",0.345058,0.0008,0.001390,True,ZNHIT6,1.0
86239,ovarian,"('ZNRF2', 'NP_667339')",0.240016,0.0311,0.043897,True,ZNRF2,1.0
86240,ovarian,"('ZPR1', 'NP_003895')",0.229895,0.0048,0.007610,True,ZPR1,1.0
86241,ovarian,"('ZRANB2', 'NP_976225')",0.438710,0.0000,0.000000,True,ZRANB2,1.0
86244,ovarian,"('ZSCAN2', 'NP_870992')",0.414704,0.0001,0.000188,True,ZSCAN2,1.0
86247,ovarian,"('ZSCAN29', 'NP_689668')",0.201903,0.0338,0.047420,True,ZSCAN29,1.0
86248,ovarian,"('ZSCAN30', 'NP_001106205')",-0.883458,0.0004,0.000717,True,ZSCAN30,-1.0
86250,ovarian,"('ZSCAN32', 'NP_001271456')",-0.554950,0.0041,0.006555,True,ZSCAN32,-1.0
86252,ovarian,"('ZW10', 'NP_004715')",0.272076,0.0000,0.000000,True,ZW10,1.0
86256,ovarian,"('ZYX', 'NP_001010972')",-0.551746,0.0000,0.000000,True,ZYX,-1.0
86257,ovarian,"('ZZEF1', 'NP_055928')",-0.256154,0.0001,0.000188,True,ZZEF1,-1.0

In [4]:
enrichment_data = pd.read_csv(STEP2_FILE_PATH, sep="\t", index_col=0)
enrichment_data

,pathway_id,cancer_type,mean_expr,url,name,pathway_times_enriched,pathway_avg_rank,entities_pValue,entities_fdr,cancer_rank_pval
0,R-HSA-6798695,ccrcc,0.233503,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,1.000,3.467008e-03,8.426404e-01,1.0
1,R-HSA-6798695,colon,-0.134831,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,1.000,6.216916e-12,1.500142e-08,1.0
2,R-HSA-6798695,endometrial,0.288515,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,1.000,1.403496e-03,8.219205e-01,1.0
3,R-HSA-6798695,gbm,0.166227,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,1.000,2.129677e-03,8.037977e-01,1.0
4,R-HSA-6798695,hnscc,0.133159,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,1.000,3.649260e-03,8.329209e-01,1.0
5,R-HSA-6798695,lscc,-0.407595,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,1.000,1.637558e-03,8.726502e-01,1.0
6,R-HSA-6798695,luad,-0.410000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,1.000,1.800932e-04,4.412282e-01,1.0
7,R-HSA-6798695,ovarian,-0.303754,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Neutrophil degranulation,8,1.000,3.532076e-05,8.660650e-02,1.0
8,R-HSA-6791226,ccrcc,0.699422,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,2.875,3.132093e-02,8.426404e-01,4.0
9,R-HSA-6791226,colon,0.771429,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,2.875,2.825057e-07,1.376497e-04,2.0
10,R-HSA-6791226,endometrial,0.759494,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,2.875,1.984718e-02,8.219205e-01,5.0
11,R-HSA-6791226,gbm,0.795181,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,2.875,1.421603e-02,8.037977e-01,3.0
12,R-HSA-6791226,hnscc,0.479290,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,2.875,5.698112e-02,8.329209e-01,3.0
13,R-HSA-6791226,lscc,0.680000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,2.875,1.017413e-02,8.726502e-01,2.0
14,R-HSA-6791226,luad,0.680000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,2.875,2.770984e-03,8.489584e-01,2.0
15,R-HSA-6791226,ovarian,0.760000,https://reactome.org/PathwayBrowser/#/R-HSA-67...,Major pathway of rRNA processing in the nucleo...,8,2.875,1.590139e-03,7.803251e-01,2.0
16,R-HSA-72163,ccrcc,0.500000,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,5.375,2.383523e-02,8.426404e-01,3.0
17,R-HSA-72163,colon,0.731707,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,5.375,9.094579e-07,3.656021e-04,4.0
18,R-HSA-72163,endometrial,0.205882,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,5.375,9.902183e-03,8.219205e-01,3.0
19,R-HSA-72163,gbm,0.750000,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,5.375,1.555753e-02,8.037977e-01,4.0
20,R-HSA-72163,hnscc,0.664596,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,5.375,6.057434e-02,8.329209e-01,4.0
21,R-HSA-72163,lscc,0.672727,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,5.375,5.786661e-02,8.726502e-01,3.0
22,R-HSA-72163,luad,0.554054,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,5.375,7.288247e-02,8.489584e-01,18.0
23,R-HSA-72163,ovarian,0.706667,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing - Major Pathway,8,5.375,2.375833e-03,7.803251e-01,4.0
24,R-HSA-72172,ccrcc,0.506173,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing,8,10.500,3.218826e-02,8.426404e-01,5.0
25,R-HSA-72172,colon,0.710843,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing,8,10.500,1.078818e-05,2.891233e-03,5.0
26,R-HSA-72172,endometrial,0.177305,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing,8,10.500,1.694556e-02,8.219205e-01,4.0
27,R-HSA-72172,gbm,0.734104,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing,8,10.500,2.560004e-02,8.037977e-01,5.0
28,R-HSA-72172,hnscc,0.646341,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing,8,10.500,9.142720e-02,8.329209e-01,11.0
29,R-HSA-72172,lscc,0.658824,https://reactome.org/PathwayBrowser/#/R-HSA-72...,mRNA Splicing,8,10.500,8.227427e-02,8.726502e-01,7.0
...,...,...,...,...,...,...,...,...,...,...
50,R-HSA-927802,endometrial,0.626168,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,17.750,8.755204e-02,8.219205e-01,25.5
51,R-HSA-927802,gbm,0.771429,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,17.750,9.008047e-02,8.037977e-01,18.5
52,R-HSA-927802,hnscc,0.233645,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,17.750,1.570822e-01,8.329209e-01,30.5
53,R-HSA-927802,lscc,0.711538,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,17.750,9.466540e-02,8.726502e-01,12.5
54,R-HSA-927802,luad,0.709091,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,17.750,4.687555e-02,8.489584e-01,7.5
55,R-HSA-927802,ovarian,0.877551,https://reactome.org/PathwayBrowser/#/R-HSA-92...,Nonsense-Mediated Decay (NMD),8,17.750,1.904926e-02,7.803251e-01,11.5
56,R-HSA-975957,ccrcc,0.611111,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,17.750,1.036529e-01,8.426404e-01,23.5
57,R-HSA-975957,colon,0.814815,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,17.750,1.856749e-04,2.580882e-02,12.5
58,R-HSA-975957,endometrial,0.626168,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,17.750,8.755204e-02,8.219205e-01,25.5
59,R-HSA-975957,gbm,0.771429,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,17.750,9.008047e-02,8.037977e-01,18.5
60,R-HSA-975957,hnscc,0.233645,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,17.750,1.570822e-01,8.329209e-01,30.5
61,R-HSA-975957,lscc,0.711538,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,17.750,9.466540e-02,8.726502e-01,12.5
62,R-HSA-975957,luad,0.709091,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,17.750,4.687555e-02,8.489584e-01,7.5
63,R-HSA-975957,ovarian,0.877551,https://reactome.org/PathwayBrowser/#/R-HSA-97...,Nonsense Mediated Decay (NMD) enhanced by the ...,8,17.750,1.904926e-02,7.803251e-01,11.5
64,R-HSA-72203,ccrcc,0.549296,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,18.500,1.862319e-02,8.426404e-01,2.0
65,R-HSA-72203,colon,0.741935,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,18.500,2.855803e-07,1.376497e-04,3.0
66,R-HSA-72203,endometrial,0.152542,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,18.500,9.292015e-03,8.219205e-01,2.0
67,R-HSA-72203,gbm,0.742222,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,18.500,1.398083e-02,8.037977e-01,2.0
68,R-HSA-72203,hnscc,0.663551,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,18.500,7.432083e-02,8.329209e-01,8.0
69,R-HSA-72203,lscc,0.686636,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,18.500,8.766714e-02,8.726502e-01,10.0
70,R-HSA-72203,luad,0.547368,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,18.500,2.671711e-01,8.489584e-01,118.0
71,R-HSA-72203,ovarian,0.723077,https://reactome.org/PathwayBrowser/#/R-HSA-72...,Processing of Capped Intron-Containing Pre-mRNA,8,18.500,1.740219e-03,7.803251e-01,3.0
72,R-HSA-1799339,ccrcc,0.705882,https://reactome.org/PathwayBrowser/#/R-HSA-17...,SRP-dependent cotranslational protein targetin...,8,20.500,1.355824e-01,8.426404e-01,43.0
73,R-HSA-1799339,colon,0.866667,https://reactome.org/PathwayBrowser/#/R-HSA-17...,SRP-dependent cotranslational protein targetin...,8,20.500,1.324252e-04,2.580882e-02,8.0
74,R-HSA-1799339,endometrial,0.809524,https://reactome.org/PathwayBrowser/#/R-HSA-17...,SRP-dependent cotranslational protein targetin...,8,20.500,8.240170e-02,8.219205e-01,19.0
75,R-HSA-1799339,gbm,0.920000,https://reactome.org/PathwayBrowser/#/R-HSA-17...,SRP-dependent cotranslational protein targetin...,8,20.500,7.062430e-02,8.037977e-01,10.0
76,R-HSA-1799339,hnscc,0.346939,https://reactome.org/PathwayBrowser/#/R-HSA-17...,SRP-dependent cotranslational protein targetin...,8,20.500,1.959464e-01,8.329209e-01,61.0
77,R-HSA-1799339,lscc,0.766990,https://reactome.org/PathwayBrowser/#/R-HSA-17...,SRP-dependent cotranslational protein targetin...,8,20.500,9.026406e-02,8.726502e-01,11.0
78,R-HSA-1799339,luad,0.754717,https://reactome.org/PathwayBrowser/#/R-HSA-17...,SRP-dependent cotranslational protein targetin...,8,20.500,3.638499e-02,8.489584e-01,3.0
79,R-HSA-1799339,ovarian,0.902913,https://reactome.org/PathwayBrowser/#/R-HSA-17...,SRP-dependent cotranslational protein targetin...,8,20.500,1.818048e-02,7.803251e-01,9.0

## Figure 1: Bubble plot

In [5]:
enrichment_data = enrichment_data.assign(
    rank_size=1 / enrichment_data["cancer_rank_pval"],
    avg_rank_size=1 / enrichment_data["pathway_avg_rank"],
    avg_rank_label=enrichment_data["pathway_avg_rank"].astype(str))

# Take care of duplicates for the upper plot
# If there were more than two values that were the same, we'd 
# need to repeat this multiple times until there was no change.

enrichment_data["avg_rank_label"] = enrichment_data["avg_rank_label"].where(
    cond=~(enrichment_data.duplicated(subset=["cancer_type", "avg_rank_label"], keep="first")),
    other=" " + enrichment_data["avg_rank_label"])

In [6]:
individual = alt.Chart(enrichment_data).mark_circle().encode(
    x=alt.X(
        "name:N",
        sort=enrichment_data["name"].values,
        axis=alt.Axis(
            labelAngle=-30,
            labelFontSize=12,
            labelLimit=500,
            title="",
            titleFontSize=12
        )
    ),
    y=alt.Y(
        "cancer_type:N",
        axis=alt.Axis(
            title="Cancer type",
            titleFontSize=12
        ),
    ),
    size=alt.Size(
        "rank_size:Q",
        legend=alt.Legend(
            title="1 / rank"
        )
    ),
    color=alt.Color(
        "mean_expr:Q",
        scale=alt.Scale(
            scheme="blueorange"
        ),
        legend=alt.Legend(
            title="Pathway tumor expression"
        )
    )
).properties(
    width=400,
    height=300
)

aggregate = alt.Chart(enrichment_data).mark_circle().encode(
    x=alt.X(
        "avg_rank_label:N",
        sort=enrichment_data["avg_rank_label"].values,
        axis=alt.Axis(
            labelAngle=-30,
            labelFontSize=12,
            labelLimit=500,
            title="Overall rank of pathway",
            titleFontSize=12
        )
    ),
    size=alt.Size(
        "avg_rank_size:Q",
        legend=alt.Legend(
            title="1 / rank"
        )
    ),
).properties(
    width=400
)

alt.vconcat(aggregate, individual).configure_axis(
    grid=True
)

alt.VConcatChart(...)

## Figure 2: Expression of neutrophil degranulation pathway proteins

In [7]:
neutro_pathway_id = enrichment_data.\
    loc[enrichment_data["name"] == "Neutrophil degranulation", "pathway_id"].\
    unique()

if len(neutro_pathway_id) != 1:
    raise ValueError("Multiple pathways found.")
    
neutro_pathway_id = neutro_pathway_id[0]

neutro_proteins = ut.search_reactome_proteins_in_pathways(neutro_pathway_id)
prot_expr = expression_data[expression_data["protein_str"].isin(neutro_proteins["member"])]

neutro_tumor_up = enrichment_data.\
    loc[(enrichment_data["pathway_id"] == neutro_pathway_id) & (enrichment_data["mean_expr"] > 0),
       "cancer_type"]

neutro_tumor_down = enrichment_data.\
    loc[(enrichment_data["pathway_id"] == neutro_pathway_id) & (enrichment_data["mean_expr"] < 0),
       "cancer_type"]

def barplot_expr(expr_data, cancer_types):
    cancer_expr = expr_data[expr_data["cancer_type"].isin(cancer_types)].\
        groupby("protein_str")["simplified_change"].agg(np.mean).\
        reset_index(drop=False).\
        sort_values(by=["simplified_change", "protein_str"])
    
    plot = alt.Chart(cancer_expr).mark_bar().encode(
        x=alt.X(
            "protein_str:N",
            sort=cancer_expr["protein_str"].values,
            axis=alt.Axis(
                title="Proteins",
                titleFontSize=14,
                labels=False,
                ticks=False
            )
        ),
        y=alt.Y(
            "simplified_change:Q",
            axis=alt.Axis(
                title="Mean expression across cancers",
                titleFontSize=14
            )
        ),
        color=alt.condition(
            alt.datum.simplified_change > 0,
            alt.value("#e45756"),
            alt.value("#4c78a8")
        )
    ).properties(
        width=600,
        height=500
    )
    
    return plot

In [8]:
alt.vconcat(
    barplot_expr(prot_expr, neutro_tumor_up).properties(
        title="Cancers with pathway overall up in tumor"
    ),
    barplot_expr(prot_expr, neutro_tumor_down).properties(
        title="Cancers with pathway overall down in tumor"
    )
).configure_title(
    fontSize=18
)

alt.VConcatChart(...)

## Figure 3: Distribution of tumor stage in each cancer

In [9]:
cc = cptac.Ccrcc(no_internet=True)
co = cptac.Colon(no_internet=True)
en = cptac.Endometrial(no_internet=True)
gb = cptac.Gbm(no_internet=True)
hn = cptac.Hnscc(no_internet=True)
ls = cptac.Lscc(no_internet=True)
lu = cptac.Luad(no_internet=True)
ov = cptac.Ovarian(no_internet=True)

cptac warning: The GBM dataset is under publication embargo until March 01, 2021. CPTAC is a community resource project and data are made available rapidly after generation for community research use. The embargo allows exploring and utilizing the data, but analysis may not be published until after the embargo date. Please see https://proteomics.cancer.gov/data-portal/about/data-use-agreement or enter cptac.embargo() to open the webpage for more details. (/home/caleb/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py, line 4)

cptac warning: The HNSCC data is currently strictly reserved for CPTAC investigators. Otherwise, you are not authorized to access these data. Additionally, even after these data become publicly available, they will be subject to a publication embargo (see https://proteomics.cancer.gov/data-portal/about/data-use-agreement or enter cptac.embargo() to open the webpage for more details). (/home/caleb/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py, line 5)

cptac warning: The LSCC data is currently strictly reserved for CPTAC investigators. Otherwise, you are not authorized to access these data. Additionally, even after these data become publicly available, they will be subject to a publication embargo (see https://proteomics.cancer.gov/data-portal/about/data-use-agreement or enter cptac.embargo() to open the webpage for more details). (/home/caleb/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py, line 6)

cptac warning: The LUAD dataset is under publication embargo until July 01, 2020. CPTAC is a community resource project and data are made available rapidly after generation for community research use. The embargo allows exploring and utilizing the data, but analysis may not be published until after the embargo date. Please see https://proteomics.cancer.gov/data-portal/about/data-use-agreement or enter cptac.embargo() to open the webpage for more details. (/home/caleb/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py, line 7)

In [10]:
stage_df = pd.DataFrame()

In [11]:
cc_stage = cc.get_clinical()["tumor_stage_pathological"].\
    dropna().\
    str.rsplit(" ", n=1, expand=True)[1].\
    rename("tumor_stage").\
    reset_index(drop=False).\
    assign(cancer_type="ccrcc")

stage_df = stage_df.append(cc_stage)

In [12]:
co_stage = co.get_clinical()["Stage"].\
    dropna().\
    str.rsplit(" ", n=1, expand=True)[1].\
    rename("tumor_stage").\
    reset_index(drop=False).\
    assign(cancer_type="colon")

stage_df = stage_df.append(co_stage)

In [13]:
en_stage = en.get_clinical()["tumor_Stage-Pathological"].\
    dropna().\
    str.rsplit(" ", n=1, expand=True)[1].\
    rename("tumor_stage").\
    reset_index(drop=False).\
    assign(cancer_type="endometrial")

stage_df = stage_df.append(en_stage)

In [14]:
# GBM?

In [15]:
hn_stage = hn.get_clinical()["patho_staging_curated"].\
    dropna().\
    str.rsplit(" ", n=1, expand=True)[1].\
    rename("tumor_stage").\
    reset_index(drop=False).\
    assign(cancer_type="hnscc")

stage_df = stage_df.append(hn_stage)

In [16]:
ls_stage = ls.get_clinical()["Stage"]
ls_stage = ls_stage.\
    rename("tumor_stage").\
    where(
        cond=~(ls_stage.dropna().str.endswith("A") | ls_stage.dropna().str.endswith("B")),
        other=ls_stage.str[:-1]).\
    where(
        cond=~(ls_stage.dropna().str.endswith("A 3")),
        other=ls_stage.dropna().str[:-3]
    ).\
    reset_index(drop=False).\
    assign(cancer_type="lscc")

stage_df = stage_df.append(ls_stage)

In [17]:
lu_stage = lu.get_clinical()["Stage"]
lu_stage = lu_stage.\
    rename("tumor_stage").\
    where(
        cond=~(lu_stage.dropna().str.endswith("A") | lu_stage.dropna().str.endswith("B")),
        other=lu_stage.str[:-1]).\
    replace({
        "1": "I",
        "2": "II",
        "3": "III"}).\
    reset_index(drop=False).\
    assign(cancer_type="luad")

stage_df = stage_df.append(lu_stage)

In [18]:
ov_stage = ov.get_clinical()["Tumor_Stage_Ovary_FIGO"]
ov_stage = ov_stage.\
    rename("tumor_stage").\
    where(
        cond=~(ov_stage.dropna().str.endswith("A") | 
               ov_stage.dropna().str.endswith("B") | 
               ov_stage.dropna().str.endswith("C")),
        other=ov_stage.str[:-1]).\
    drop(ov_stage[ov_stage == "Not Reported/ Unknown"].index).\
    reset_index(drop=False).\
    assign(cancer_type="ovarian")

stage_df = stage_df.append(ov_stage)

In [19]:
stage_df = stage_df.dropna()

In [20]:
# Join in whether neutrophil expression is up or down in tumor
neutro_expr = enrichment_data.loc[
    enrichment_data["pathway_id"] == neutro_pathway_id, 
    ["cancer_type", "name", "pathway_id", "mean_expr"]]

neutro_expr = neutro_expr.assign(
    neutro_expr_tumor=np.where(neutro_expr["mean_expr"] > 0, "Up", "Down"))


neutro_expr

,cancer_type,name,pathway_id,mean_expr,neutro_expr_tumor
0,ccrcc,Neutrophil degranulation,R-HSA-6798695,0.233503,Up
1,colon,Neutrophil degranulation,R-HSA-6798695,-0.134831,Down
2,endometrial,Neutrophil degranulation,R-HSA-6798695,0.288515,Up
3,gbm,Neutrophil degranulation,R-HSA-6798695,0.166227,Up
4,hnscc,Neutrophil degranulation,R-HSA-6798695,0.133159,Up
5,lscc,Neutrophil degranulation,R-HSA-6798695,-0.407595,Down
6,luad,Neutrophil degranulation,R-HSA-6798695,-0.410000,Down
7,ovarian,Neutrophil degranulation,R-HSA-6798695,-0.303754,Down

In [21]:
stage_df = stage_df.merge(
    right=neutro_expr,
    how="left",
    left_on="cancer_type",
    right_on="cancer_type",
    validate="many_to_one")

In [22]:
# Make plots
alt.Chart(stage_df).mark_bar().encode(
    x=alt.X(
        "tumor_stage:N",
        axis=alt.Axis(
            labelAngle=0,
            labelFontSize=14,
            title=""
        )
    ),
    y=alt.Y(
        "count():Q",
        axis=alt.Axis(
            title="Count",
            titleFontSize=14
        )
    ),
    color=alt.Color(
        "neutro_expr_tumor",
        legend=alt.Legend(
            title=["Neutrophil degradation:", "Mean pathway expression", "in tumor"]
        ),
        scale=alt.Scale(
            domain=["Up", "Down"],
            range=["#e45756", "#4c78a8"]
        )
    ),
    column=alt.Column(
        "cancer_type:N",
        title="Tumor stage distribution"
    )
).configure_title(
    fontSize=16
)

alt.Chart(...)

In [23]:
# Ask Sam: Is this idea of "mean pathway expression" 
# really valid? What if in reality, though we can't
# measure it, some proteins' magnitude of expression 
# change is a lot greater, so they should actually
# have greater weight in the mean calculation, and
# thus might alter the overall statistic for the
# pathway?