# Pancancer enrichment analysis step 7: Make figures from GSEApy data with weighted score type = 0

## Setup

In [1]:
import os
import datetime
import altair as alt
import numpy as np
import pandas as pd
import operator
import IPython.display

In [2]:
TIME_START = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')

# Step 1 output
STEP1_DIR = "step1_outputs"
STEP1_FILE = "tumor_change_20200529_195104_10000_perm.tsv"
STEP1_FILE_PATH = os.path.join(STEP1_DIR, STEP1_FILE)

# Step 5 outputs
STEP5_DIR = "step5_outputs"

STEP5_abs_signal_to_noise = os.path.join(STEP5_DIR, "enrichment_gseapy_reactome_20200618_104458_10000_perms_wst0_abs_signal_to_noise.tsv")
STEP5_diff_of_classes = os.path.join(STEP5_DIR, "enrichment_gseapy_reactome_20200618_104458_10000_perms_wst0_diff_of_classes.tsv")
STEP5_log2_ratio_of_classes = os.path.join(STEP5_DIR, "enrichment_gseapy_reactome_20200618_104458_10000_perms_wst0_log2_ratio_of_classes.tsv")
STEP5_ratio_of_classes = os.path.join(STEP5_DIR, "enrichment_gseapy_reactome_20200618_104458_10000_perms_wst0_ratio_of_classes.tsv")
STEP5_signal_to_noise = os.path.join(STEP5_DIR, "enrichment_gseapy_reactome_20200618_104458_10000_perms_wst0_signal_to_noise.tsv")
STEP5_t_test = os.path.join(STEP5_DIR, "enrichment_gseapy_reactome_20200618_104458_10000_perms_wst0_t_test.tsv")

# Step 6 output
STEP6_DIR = "step6_outputs"

STEP6_S2N = "enrichment_gseapy_kegg_signal_to_noise_10000_perms_20200617_072701.tsv"
STEP6_S2N_PATH = os.path.join(STEP6_DIR, STEP6_S2N)

STEP6_ABS_S2N = "enrichment_gseapy_kegg_abs_signal_to_noise_10000_perms_20200617_103905.tsv"
STEP6_ABS_S2N_PATH = os.path.join(STEP6_DIR, STEP6_ABS_S2N)

MSV = 0.5 # Simplified expression value for marginally significant proteins

In [3]:
# Altair options
# alt.data_transformers.disable_max_rows()
# alt.data_transformers.enable('json')

## Function to plot top pathways across cancer types

In [4]:
def plot_top_ten(enrich_file_path, expr_file_path, xtitle, fdr=0.3):
    
    # Read in the expression data
    all_expression_data = pd.read_csv(expr_file_path, sep="\t", index_col=0)

    # Make a column where all increases are +1 and all decreases 
    # are -1, because these are ratioed abundances, so we can't 
    # compare magnitudes between genes--we can only compare whether 
    # there was a change, and whether it was positive or negative
    all_expression_data = all_expression_data.assign(simplified_change=np.nan)

    # adj p < 0.05 and change > 1 => +1
    all_expression_data.loc[
        (all_expression_data["change"] > 0) & (all_expression_data["adj_p"] < 0.05), 
        "simplified_change"
    ] = 1

    # adj p >= 0.05 and change > 1 => +0.5
    all_expression_data.loc[(all_expression_data["change"] > 0) & (all_expression_data["adj_p"] >= 0.05),
        "simplified_change"
    ] = MSV

    # change == 0 => 0
    all_expression_data.loc[
        all_expression_data["change"] == 0,
        "simplified_change"
    ] = 0

    # adj p >= 0.05 and change < 1 => -0.5
    all_expression_data.loc[(all_expression_data["change"] < 0) & (all_expression_data["adj_p"] >= 0.05), 
        "simplified_change"
    ] = -MSV

    # adj p < 0.05 and change < 1 => -1
    all_expression_data.loc[
        (all_expression_data["change"] < 0) & (all_expression_data["adj_p"] < 0.05),
        "simplified_change"
    ] = -1

    # Select just the proteins where we chose to reject the null hypothesis of no change
    expression_data = all_expression_data[all_expression_data["reject_null"]]

    # Read in the enrichment data
    enrichment_data = pd.read_csv(enrich_file_path, sep="\t")
    
    # Select enrichment data below our FDR
    enrichment_data = enrichment_data.loc[enrichment_data["fdr"] <= fdr, :]
    
    # Make a column for abs_nes
    enrichment_data = enrichment_data.assign(abs_nes=enrichment_data["nes"].abs())

    # Assign pathway ranks within each cancer type based on absolute value of NES
    enrichment_data = enrichment_data.\
        assign(cancer_rank_abs_nes=enrichment_data.groupby("cancer_type")["abs_nes"].rank(ascending=False)).\
        sort_values(by=["cancer_type", "cancer_rank_abs_nes"]).\
        reset_index(drop=True)

    # Make a table with summary info for all pathways
    enrichment_summary = enrichment_data[["Term"]].drop_duplicates(keep="first")

    pathway_times_enriched = enrichment_summary["Term"].apply(
        lambda x: enrichment_data[enrichment_data["Term"] == x].shape[0])

    avg_rank = enrichment_summary["Term"].apply(
        lambda x: enrichment_data.loc[enrichment_data["Term"] == x, "cancer_rank_abs_nes"].mean())

    enrichment_summary = enrichment_summary.\
        assign(
            pathway_times_enriched=pathway_times_enriched,
            pathway_avg_rank=avg_rank).\
        sort_values(
            by=["pathway_times_enriched", "pathway_avg_rank"],
            ascending=[False, True]).\
        reset_index(drop=True)

    # Merge in the original enrichment data
    enrichment_data = enrichment_data.\
        merge(
            enrichment_summary,
            how="outer",
            left_on="Term",
            right_on="Term",
            validate="many_to_one"
        ).\
        sort_values(
            by=["pathway_times_enriched", "pathway_avg_rank", "cancer_type"],
            ascending=[False, True, True]
        )

    # Select top 10 for our plot
    top_ten = enrichment_data["Term"].unique()[:10]
    sel_enrich = enrichment_data[enrichment_data["Term"].isin(top_ten)]

    # Calculate the mean expression for each pathway in each cancer type
    mean_exprs = []

    for idx in sel_enrich.index:
        genes = sel_enrich.loc[idx, "genes"].split(";")
        cancer_type = sel_enrich.loc[idx, "cancer_type"]

        genes_expr = expression_data.loc[
            expression_data["protein_str"].isin(genes),
            "simplified_change"
        ].mean()

        mean_exprs.append(genes_expr)

    sel_enrich = sel_enrich.assign(mean_expr=mean_exprs)

    sel_enrich = sel_enrich.assign(
        rank_size=1 / sel_enrich["cancer_rank_abs_nes"],
        avg_rank_size=1 / sel_enrich["pathway_avg_rank"])

    individual = alt.Chart(sel_enrich).mark_circle().encode(
        x=alt.X(
            "Term:N",
            sort=sel_enrich["Term"].values,
            axis=alt.Axis(
                labelAngle=-30,
                labelFontSize=12,
                labelLimit=500,
                title="",
                titleFontSize=16
            )
        ),
        y=alt.Y(
            "cancer_type:N",
            axis=alt.Axis(
                title="Cancer type",
                titleFontSize=12
            ),
        ),
        size=alt.Size(
            "rank_size:Q",
            legend=None
        ),
        color=alt.Color(
            "mean_expr:Q",
            scale=alt.Scale(
                scheme="blueorange",
                domain=[-1, 1]
            ),
            legend=alt.Legend(
                title="Pathway tumor expression"
            )
        )
    ).properties(
        width=400,
        height=300
    )

    aggregate = alt.Chart(sel_enrich).mark_circle().encode(
        x=alt.X(
            "pathway_avg_rank:N",
            sort=sel_enrich["pathway_avg_rank"].values,
            axis=alt.Axis(
                labelAngle=-30,
                labelFontSize=12,
                labelLimit=500,
                title="Overall rank of pathway",
                titleFontSize=12
            )
        ),
        size=alt.Size(
            "avg_rank_size:Q",
            legend=None
        ),
    ).properties(
        width=400
    )

    full_plot = alt.vconcat(
        aggregate, individual
    ).properties(
        title=xtitle
    )
    
    return full_plot, enrichment_data, all_expression_data, enrichment_summary

In [5]:
plot_top_ten(STEP5_abs_signal_to_noise, STEP1_FILE_PATH, "Reactome data - proteins ranked by abs_signal_to_noise")[3]

,Term,pathway_times_enriched,pathway_avg_rank
0,Nervous system development,6,17.833333
1,mRNA 3'-end processing,6,24.500000
2,Hemostasis,6,26.500000
3,Transport of Mature mRNA derived from an Intro...,6,33.833333
4,Cellular response to heat stress,6,40.500000
5,Translation,6,48.000000
6,Regulation of HSF1-mediated heat shock response,6,53.000000
7,Response to elevated platelet cytosolic Ca2+,6,90.333333
8,Binding and Uptake of Ligands by Scavenger Rec...,6,92.500000
9,Influenza Infection,6,93.666667
10,Platelet degranulation,6,100.500000
11,SRP-dependent cotranslational protein targetin...,6,114.000000
12,Opioid Signalling,6,115.000000
13,Thrombin signalling through proteinase activat...,6,121.166667
14,Translation initiation complex formation,6,122.666667
15,Activation of the mRNA upon binding of the cap...,6,133.333333
16,"Formation of the ternary complex, and subseque...",6,137.833333
17,Regulation of insulin secretion,6,142.000000
18,Processing of Capped Intron-Containing Pre-mRNA,5,9.800000
19,Cellular responses to external stimuli,5,15.600000
20,Axon guidance,5,17.400000
21,RNA Polymerase II Transcription Termination,5,19.000000
22,mRNA Splicing,5,19.400000
23,Transport of Mature mRNA Derived from an Intro...,5,26.600000
24,Transport of Mature mRNAs Derived from Intronl...,5,30.000000
25,ISG15 antiviral mechanism,5,51.800000
26,Signaling by ROBO receptors,5,56.200000
27,Transport of the SLBP independent Mature mRNA,5,61.000000
28,Transport of the SLBP Dependant Mature mRNA,5,62.400000
29,Antiviral mechanism by IFN-stimulated genes,5,63.400000
...,...,...,...
939,Cyclin A/B1/B2 associated events during G2/M t...,1,464.000000
940,Beta oxidation of butanoyl-CoA to acetyl-CoA,1,465.000000
941,Peroxisomal protein import,1,467.000000
942,Negative regulation of NMDA receptor-mediated ...,1,468.000000
943,DDX58/IFIH1-mediated induction of interferon-a...,1,469.000000
944,Ficolins bind to repetitive carbohydrate struc...,1,470.000000
945,Glycogen breakdown (glycogenolysis),1,472.000000
946,Biosynthesis of E-series 18(S)-resolvins,1,474.000000
947,InlB-mediated entry of Listeria monocytogenes ...,1,475.000000
948,Defective factor VIII causes hemophilia A,1,479.000000
949,RUNX3 Regulates Immune Response and Cell Migra...,1,480.000000
950,Nef mediated downregulation of MHC class I com...,1,481.000000
951,Sema4D mediated inhibition of cell attachment ...,1,482.000000
952,Telomere Maintenance,1,484.000000
953,PERK regulates gene expression,1,489.000000
954,Aspartate and asparagine metabolism,1,495.000000
955,Mitochondrial translation initiation,1,505.000000
956,Gastrin-CREB signalling pathway via PKC and MAPK,1,506.000000
957,Phosphorylation of the APC/C,1,507.000000
958,Activation of Matrix Metalloproteinases,1,508.000000
959,Prefoldin mediated transfer of substrate to C...,1,511.000000
960,Defective NEU1 causes sialidosis,1,512.000000
961,Heme biosynthesis,1,513.000000
962,Cargo recognition for clathrin-mediated endocy...,1,514.000000
963,Phospholipase C-mediated cascade; FGFR4,1,515.000000
964,Synthesis of PIPs at the early endosome membrane,1,516.000000
965,Signaling by cytosolic PDGFRA and PDGFRB fusio...,1,519.000000
966,Cristae formation,1,521.000000
967,Killing mechanisms,1,522.500000
968,WNT5:FZD7-mediated leishmania damping,1,522.500000

In [6]:
plot_top_ten(STEP5_diff_of_classes, STEP1_FILE_PATH, "Reactome data - proteins ranked by diff_of_classes")[3]

,Term,pathway_times_enriched,pathway_avg_rank
0,"Platelet activation, signaling and aggregation",5,93.000
1,NCAM signaling for neurite out-growth,5,93.200
2,G alpha (z) signalling events,5,108.200
3,GPCR downstream signalling,4,12.500
4,Signaling by GPCR,4,16.000
5,Ca2+ pathway,4,35.250
6,Integration of energy metabolism,4,39.750
7,Platelet homeostasis,4,45.500
8,Glucagon signaling in metabolic regulation,4,47.000
9,Activation of GABAB receptors,4,50.500
10,GABA B receptor activation,4,50.500
11,Thrombin signalling through proteinase activat...,4,53.250
12,GABA receptor activation,4,60.500
13,Post NMDA receptor activation events,4,73.250
14,Ca-dependent events,4,74.750
15,PI3K/AKT Signaling in Cancer,4,75.250
16,"Adrenaline,noradrenaline inhibits insulin secr...",4,79.750
17,G-protein mediated events,4,83.000
18,PLC beta mediated events,4,84.750
19,Leishmania infection,4,85.250
20,Activation of NMDA receptors and postsynaptic ...,4,87.750
21,Glucagon-type ligand receptors,4,88.625
22,G-protein activation,4,94.750
23,Anti-inflammatory response favouring Leishmani...,4,96.250
24,Leishmania parasite growth and survival,4,96.250
25,G alpha (q) signalling events,4,97.250
26,Inwardly rectifying K+ channels,4,98.375
27,PKA activation in glucagon signalling,4,104.000
28,ADP signalling through P2Y purinoceptor 12,4,111.250
29,Prostacyclin signalling through prostacyclin r...,4,111.625
...,...,...,...
794,ATF6 (ATF6-alpha) activates chaperone genes,1,408.000
795,Apoptotic execution phase,1,409.000
796,Regulation of TP53 Activity,1,410.000
797,Synthesis of active ubiquitin: roles of E1 and...,1,410.000
798,Synthesis of diphthamide-EEF2,1,411.000
799,PCP/CE pathway,1,412.000
800,Formation of Senescence-Associated Heterochrom...,1,413.000
801,TCF dependent signaling in response to WNT,1,415.000
802,Signaling by FGFR,1,416.000
803,Maturation of protein E,1,417.000
804,DNA replication initiation,1,420.000
805,Regulation of TP53 Activity through Acetylation,1,420.000
806,Global Genome Nucleotide Excision Repair (GG-NER),1,422.000
807,Mitotic Telophase/Cytokinesis,1,423.000
808,Manipulation of host energy metabolism,1,423.000
809,Regulation of RAS by GAPs,1,424.000
810,Pyrimidine salvage,1,425.000
811,Regulation of TP53 Activity through Methylation,1,426.000
812,Programmed Cell Death,1,426.000
813,Activation of gene expression by SREBF (SREBP),1,427.000
814,Transcriptional regulation by the AP-2 (TFAP2)...,1,428.000
815,Androgen biosynthesis,1,429.000
816,Reactions specific to the complex N-glycan syn...,1,431.000
817,Regulation of PTEN stability and activity,1,432.000
818,Cyclin A/B1/B2 associated events during G2/M t...,1,432.000
819,Pexophagy,1,433.000
820,Transcriptional regulation of granulopoiesis,1,434.000
821,Meiosis,1,435.000
822,MET interacts with TNS proteins,1,437.000
823,"Activation, translocation and oligomerization ...",1,438.000

In [7]:
plot_top_ten(STEP5_log2_ratio_of_classes, STEP1_FILE_PATH, "Reactome data - proteins ranked by log2_ratio_of_classes")[3]

,Term,pathway_times_enriched,pathway_avg_rank
0,RAB geranylgeranylation,6,169.666667
1,Viral Messenger RNA Synthesis,5,110.400000
2,RNA Polymerase III Chain Elongation,5,117.200000
3,SUMOylation of ubiquitinylation proteins,5,136.000000
4,RNA Polymerase III Transcription Termination,5,136.800000
5,Rev-mediated nuclear export of HIV RNA,5,144.000000
6,Nuclear Receptor transcription pathway,5,147.200000
7,Interactions of Rev with host cellular proteins,5,152.800000
8,Degradation of AXIN,5,154.400000
9,Regulation of RUNX3 expression and activity,5,162.200000
10,Transcriptional regulation by small RNAs,5,164.000000
11,NIK-->noncanonical NF-kB signaling,5,168.000000
12,Dectin-1 mediated noncanonical NF-kB signaling,5,170.400000
13,Defective TPR may confer susceptibility toward...,5,171.300000
14,Regulation of Glucokinase by Glucokinase Regul...,5,171.300000
15,Glycolysis,5,171.400000
16,RNA Polymerase III Transcription Initiation Fr...,5,172.400000
17,NEP/NS2 Interacts with the Cellular Export Mac...,5,174.400000
18,Regulation of activated PAK-2p34 by proteasome...,5,176.400000
19,tRNA processing in the nucleus,5,177.400000
20,Cross-presentation of soluble exogenous antige...,5,179.800000
21,CDT1 association with the CDC6:ORC:origin complex,5,180.400000
22,Nuclear import of Rev protein,5,188.400000
23,SCF-beta-TrCP mediated degradation of Emi1,5,189.000000
24,Interactions of Vpr with host cellular proteins,5,191.000000
25,Transport of Ribonucleoproteins into the Host ...,5,193.800000
26,Ubiquitin-dependent degradation of Cyclin D,5,194.200000
27,Metabolism of polyamines,5,196.600000
28,Regulation of ornithine decarboxylase (ODC),5,201.600000
29,Vpr-mediated nuclear import of PICs,5,203.200000
...,...,...,...
1686,Axonal growth stimulation,1,1008.000000
1687,Creatine metabolism,1,1012.000000
1688,Deactivation of the beta-catenin transactivati...,1,1014.000000
1689,PKA activation,1,1019.000000
1690,mRNA 3'-end processing,1,1023.000000
1691,Termination of O-glycan biosynthesis,1,1027.000000
1692,Lipid particle organization,1,1029.000000
1693,AURKA Activation by TPX2,1,1031.000000
1694,Cytochrome P450 - arranged by substrate type,1,1033.000000
1695,Resolution of AP sites via the single-nucleoti...,1,1034.000000
1696,Defective SLC16A1 causes symptomatic deficienc...,1,1035.000000
1697,Class A/1 (Rhodopsin-like receptors),1,1039.000000
1698,Interleukin-38 signaling,1,1041.000000
1699,Interleukin-2 signaling,1,1044.000000
1700,Activated point mutants of FGFR2,1,1045.000000
1701,Regulation of FZD by ubiquitination,1,1048.000000
1702,Mitochondrial transcription termination,1,1054.000000
1703,Chylomicron assembly,1,1057.000000
1704,APC-Cdc20 mediated degradation of Nek2A,1,1058.000000
1705,Erythropoietin activates RAS,1,1059.000000
1706,Initiation of Nuclear Envelope (NE) Reformation,1,1062.000000
1707,Intrinsic Pathway of Fibrin Clot Formation,1,1065.000000
1708,HDL clearance,1,1070.000000
1709,Phospholipase C-mediated cascade; FGFR3,1,1072.000000
1710,Phospholipase C-mediated cascade; FGFR4,1,1073.000000
1711,Death Receptor Signalling,1,1076.000000
1712,FGFR3 mutant receptor activation,1,1082.500000
1713,Signaling by activated point mutants of FGFR3,1,1082.500000
1714,TNF receptor superfamily (TNFSF) members media...,1,1084.000000
1715,Defective ALG14 causes congenital myasthenic s...,1,1086.000000

In [8]:
plot_top_ten(STEP5_ratio_of_classes, STEP1_FILE_PATH, "Reactome data - proteins ranked by ratio_of_classes")[3]

,Term,pathway_times_enriched,pathway_avg_rank
0,Translation,2,4.0
1,Advanced glycosylation endproduct receptor sig...,2,27.5
2,Activated PKN1 stimulates transcription of AR ...,2,39.5
3,Metabolism of non-coding RNA,2,55.0
4,snRNP Assembly,2,55.0
5,Interactions of Vpr with host cellular proteins,2,62.0
6,Vpr-mediated nuclear import of PICs,2,72.0
7,SUMOylation of RNA binding proteins,2,79.0
8,Transport of the SLBP independent Mature mRNA,2,96.0
9,AMPK inhibits chREBP transcriptional activatio...,2,112.0
10,Viral Messenger RNA Synthesis,2,120.0
11,FGFRL1 modulation of FGFR1 signaling,2,120.5
12,Transport of the SLBP Dependant Mature mRNA,2,139.0
13,mRNA decay by 5' to 3' exoribonuclease,2,157.0
14,SUMOylation of DNA replication proteins,2,174.5
15,Transcriptional regulation by small RNAs,2,210.5
16,Loss of MECP2 binding ability to 5mC-DNA,2,234.0
17,Regulation of HSF1-mediated heat shock response,2,243.0
18,mRNA Splicing - Minor Pathway,2,301.5
19,Influenza Viral RNA Transcription and Replication,2,314.0
20,Regulation of MECP2 expression and activity,2,325.0
21,VEGF binds to VEGFR leading to receptor dimeri...,2,328.5
22,VEGF ligand-receptor interactions,2,328.5
23,Regulation of Insulin-like Growth Factor (IGF)...,1,1.0
24,Defective MMAB causes methylmalonic aciduria t...,1,1.0
25,SUMOylation of immune response proteins,1,1.0
26,Cellular responses to stress,1,1.0
27,Defective FMO3 causes Trimethylaminuria (TMAU),1,2.0
28,Reversal of alkylation damage by DNA dioxygenases,1,2.0
29,Influenza Infection,1,2.0
...,...,...,...
683,Signaling by Type 1 Insulin-like Growth Factor...,1,593.0
684,Intra-Golgi traffic,1,594.0
685,TBC/RABGAPs,1,595.0
686,Glycogen storage disease type 0 (liver GYS2),1,596.0
687,Defective TCN2 causes hereditary megaloblastic...,1,597.0
688,Interleukin-33 signaling,1,598.0
689,Competing endogenous RNAs (ceRNAs) regulate PT...,1,599.0
690,Disorders of developmental biology,1,601.0
691,Loss of function of MECP2 in Rett syndrome,1,601.0
692,Pervasive developmental disorders,1,601.0
693,SOS-mediated signalling,1,603.0
694,TP53 regulates transcription of additional cel...,1,604.0
695,Biosynthesis of aspirin-triggered D-series res...,1,605.0
696,G-protein beta:gamma signalling,1,606.0
697,Interleukin-12 signaling,1,607.0
698,MAP2K and MAPK activation,1,608.0
699,Signal attenuation,1,609.0
700,Sodium/Calcium exchangers,1,610.0
701,Dopamine Neurotransmitter Release Cycle,1,611.0
702,DEx/H-box helicases activate type I IFN and in...,1,612.0
703,CD22 mediated BCR regulation,1,615.0
704,Ca2+ pathway,1,616.0
705,Chondroitin sulfate biosynthesis,1,617.0
706,ATF6 (ATF6-alpha) activates chaperone genes,1,618.0
707,FOXO-mediated transcription of oxidative stres...,1,619.0
708,Signal regulatory protein family interactions,1,620.0
709,Collagen chain trimerization,1,621.0
710,Post-transcriptional silencing by small RNAs,1,622.0
711,Olfactory Signaling Pathway,1,623.0
712,Activation of RAC1,1,624.0

In [9]:
plot_top_ten(STEP5_signal_to_noise, STEP1_FILE_PATH, "Reactome data - proteins ranked by signal_to_noise")[3]

,Term,pathway_times_enriched,pathway_avg_rank
0,Major pathway of rRNA processing in the nucleo...,6,34.500000
1,rRNA processing,6,38.833333
2,Influenza Infection,6,64.833333
3,Influenza Viral RNA Transcription and Replication,6,94.833333
4,mRNA 3'-end processing,5,19.600000
5,mRNA Splicing - Major Pathway,5,22.000000
6,mRNA Splicing,5,31.000000
7,HIV Infection,5,40.400000
8,rRNA processing in the nucleus and cytosol,5,45.400000
9,HIV Life Cycle,5,46.000000
10,Interactions of Rev with host cellular proteins,5,51.200000
11,Nuclear import of Rev protein,5,53.400000
12,Positive epigenetic regulation of rRNA expression,5,54.400000
13,Late Phase of HIV Life Cycle,5,57.600000
14,Nuclear Pore Complex (NPC) Disassembly,5,59.200000
15,NS1 Mediated Effects on Host Pathways,5,59.400000
16,Negative epigenetic regulation of rRNA expression,5,61.200000
17,Translation initiation complex formation,5,63.000000
18,RNA Polymerase I Transcription,5,63.600000
19,RNA Polymerase I Promoter Clearance,5,63.800000
20,RNA Polymerase II Pre-transcription Events,5,64.800000
21,NoRC negatively regulates rRNA expression,5,66.400000
22,Ribosomal scanning and start codon recognition,5,67.000000
23,Processing of Intronless Pre-mRNAs,5,68.800000
24,Activation of the mRNA upon binding of the cap...,5,69.800000
25,Transcription of the HIV genome,5,74.000000
26,"Formation of the ternary complex, and subseque...",5,74.600000
27,Formation of RNA Pol II elongation complex,5,75.300000
28,RNA Polymerase II Transcription Elongation,5,75.300000
29,RNA Polymerase I Transcription Initiation,5,76.000000
...,...,...,...
873,Pyrimidine biosynthesis,1,396.000000
874,Regulation of TP53 Activity through Methylation,1,398.000000
875,Prefoldin mediated transfer of substrate to C...,1,399.000000
876,Unwinding of DNA,1,400.000000
877,FMO oxidises nucleophiles,1,400.000000
878,Activation of RAC1 downstream of NMDARs,1,402.000000
879,InlA-mediated entry of Listeria monocytogenes ...,1,403.000000
880,Synthesis of very long-chain fatty acyl-CoAs,1,404.000000
881,Phase 2 - plateau phase,1,405.000000
882,Fatty acyl-CoA biosynthesis,1,407.000000
883,tRNA processing in the mitochondrion,1,409.000000
884,Cooperation of Prefoldin and TriC/CCT in acti...,1,412.000000
885,Apoptotic execution phase,1,425.000000
886,Interleukin-12 signaling,1,437.000000
887,Assembly of Viral Components at the Budding Site,1,442.500000
888,Virus Assembly and Release,1,442.500000
889,Synthesis of wybutosine at G37 of tRNA(Phe),1,459.000000
890,Cargo concentration in the ER,1,460.000000
891,Gene and protein expression by JAK-STAT signal...,1,461.000000
892,SMAD2/SMAD3:SMAD4 heterotrimer regulates trans...,1,462.000000
893,Noncanonical activation of NOTCH3,1,470.000000
894,Synthesis of diphthamide-EEF2,1,476.000000
895,SUMOylation of transcription factors,1,481.000000
896,Inhibition of nitric oxide production,1,487.000000
897,tRNA Aminoacylation,1,490.000000
898,RORA activates gene expression,1,498.000000
899,Interconversion of nucleotide di- and triphosp...,1,505.000000
900,COPII-mediated vesicle transport,1,512.000000
901,Metabolism of folate and pterines,1,518.000000
902,LRR FLII-interacting protein 1 (LRRFIP1) activ...,1,529.000000

In [10]:
plot_top_ten(STEP5_t_test, STEP1_FILE_PATH, "Reactome data - proteins ranked by t_test")[3]

,Term,pathway_times_enriched,pathway_avg_rank
0,Major pathway of rRNA processing in the nucleo...,6,32.000000
1,rRNA processing,6,36.166667
2,Influenza Infection,6,67.833333
3,Influenza Viral RNA Transcription and Replication,6,97.500000
4,G2/M Checkpoints,6,134.000000
5,mRNA 3'-end processing,5,19.800000
6,mRNA Splicing,5,31.600000
7,Transport of the SLBP independent Mature mRNA,5,40.200000
8,rRNA processing in the nucleus and cytosol,5,42.400000
9,HIV Life Cycle,5,45.400000
10,Late Phase of HIV Life Cycle,5,56.000000
11,Positive epigenetic regulation of rRNA expression,5,57.600000
12,Translation initiation complex formation,5,61.200000
13,Nuclear Pore Complex (NPC) Disassembly,5,61.400000
14,Interactions of Rev with host cellular proteins,5,63.600000
15,Negative epigenetic regulation of rRNA expression,5,64.000000
16,RNA Polymerase II Pre-transcription Events,5,64.400000
17,Ribosomal scanning and start codon recognition,5,64.400000
18,NoRC negatively regulates rRNA expression,5,66.600000
19,Nuclear import of Rev protein,5,67.000000
20,RNA Polymerase I Transcription,5,67.600000
21,RNA Polymerase I Promoter Clearance,5,67.800000
22,Activation of the mRNA upon binding of the cap...,5,68.800000
23,NS1 Mediated Effects on Host Pathways,5,69.200000
24,Processing of Intronless Pre-mRNAs,5,70.400000
25,"Formation of the ternary complex, and subseque...",5,70.800000
26,Transcription of the HIV genome,5,73.600000
27,Formation of RNA Pol II elongation complex,5,76.500000
28,RNA Polymerase II Transcription Elongation,5,76.500000
29,Cellular responses to stress,5,80.400000
...,...,...,...
870,Activation of the AP-1 family of transcription...,1,407.000000
871,Creatine metabolism,1,409.000000
872,Phase 2 - plateau phase,1,410.000000
873,Negative feedback regulation of MAPK pathway,1,414.000000
874,Cooperation of Prefoldin and TriC/CCT in acti...,1,421.000000
875,Apoptotic execution phase,1,435.000000
876,Interleukin-12 signaling,1,438.000000
877,Assembly of Viral Components at the Budding Site,1,448.500000
878,Virus Assembly and Release,1,448.500000
879,Uptake and function of diphtheria toxin,1,450.000000
880,SMAD2/SMAD3:SMAD4 heterotrimer regulates trans...,1,451.000000
881,Gene and protein expression by JAK-STAT signal...,1,462.000000
882,Cargo concentration in the ER,1,463.000000
883,Synthesis of wybutosine at G37 of tRNA(Phe),1,464.000000
884,Noncanonical activation of NOTCH3,1,469.000000
885,Stimulation of the cell death response by PAK-...,1,470.000000
886,Synthesis of diphthamide-EEF2,1,474.000000
887,RORA activates gene expression,1,486.000000
888,Inhibition of nitric oxide production,1,489.000000
889,SUMOylation of transcription factors,1,490.000000
890,tRNA Aminoacylation,1,498.000000
891,Interconversion of nucleotide di- and triphosp...,1,504.000000
892,COPII-mediated vesicle transport,1,506.000000
893,Metabolism of folate and pterines,1,519.000000
894,Suppression of phagosomal maturation,1,528.000000
895,LRR FLII-interacting protein 1 (LRRFIP1) activ...,1,531.000000
896,Metal ion SLC transporters,1,532.000000
897,Sensing of DNA Double Strand Breaks,1,534.000000
898,Reactions specific to the complex N-glycan syn...,1,536.000000
899,Manipulation of host energy metabolism,1,537.000000

In [11]:
df = pd.read_csv(STEP5_log2_ratio_of_classes, sep="\t", index_col=0)

In [12]:
df["fdr"].min()

0.0

In [13]:
alt.vconcat(
    plot_top_ten(STEP5_abs_signal_to_noise, STEP1_FILE_PATH, "Reactome data - proteins ranked by abs_signal_to_noise")[0],
    plot_top_ten(STEP5_diff_of_classes, STEP1_FILE_PATH, "Reactome data - proteins ranked by diff_of_classes")[0],
    plot_top_ten(STEP5_log2_ratio_of_classes, STEP1_FILE_PATH, "Reactome data - proteins ranked by log2_ratio_of_classes")[0],
    plot_top_ten(STEP5_ratio_of_classes, STEP1_FILE_PATH, "Reactome data - proteins ranked by ratio_of_classes")[0],
    plot_top_ten(STEP5_signal_to_noise, STEP1_FILE_PATH, "Reactome data - proteins ranked by signal_to_noise")[0],
    plot_top_ten(STEP5_t_test, STEP1_FILE_PATH, "Reactome data - proteins ranked by t_test")[0],
    
    plot_top_ten(STEP6_ABS_S2N_PATH, STEP1_FILE_PATH, "KEGG data - proteins ranked by |S2N|")[0],
    plot_top_ten(STEP6_S2N_PATH, STEP1_FILE_PATH, "KEGG data - proteins ranked by S2N")[0],
).configure_axis(
    grid=True
).configure_title(
    fontSize=16,
    anchor="end",
    offset=20
).resolve_scale(
    size="independent"
)

alt.VConcatChart(...)

In [14]:
def find_neutrophil_degranulation(fp):
    enrich = plot_top_ten(fp, STEP1_FILE_PATH, "Reactome data - proteins ranked by |S2N|", fdr=1)[1]

    # enrich = enrich[enrich["pathway_times_enriched"] == 8]
    ranks = enrich[["Term", "pathway_avg_rank"]].\
        set_index("Term").\
        drop_duplicates(keep="first").\
        rank()["pathway_avg_rank"].\
        rename("pathway_overall_rank")

    enrich = enrich.merge(
        right=ranks,
        left_on="Term",
        right_on="Term",
        validate="many_to_one")

    return enrich[enrich["Term"] == "Neutrophil degranulation"]

In [15]:
find_neutrophil_degranulation(STEP5_abs_signal_to_noise)

,Term,es,nes,pval,fdr,geneset_size,matched_size,genes,ledge_genes,cancer_type,abs_nes,cancer_rank_abs_nes,pathway_times_enriched,pathway_avg_rank,pathway_overall_rank
6008,Neutrophil degranulation,0.004765,4.506603,0.021297,0.379019,479,427,PYGL;GGH;NDUFC2;TYROBP;FCER1G;ITGAX;RAP2B;LPCA...,PYGL;GGH;NDUFC2;TYROBP;FCER1G;ITGAX;RAP2B;LPCA...,ccrcc,4.506603,26.0,8,1070.125,810.0
6009,Neutrophil degranulation,0.001705,1.288740,0.868132,0.932818,479,405,METTL7A;S100A11;HSP90AB1;AGL;CNN2;RAB5B;CFD;XR...,METTL7A;S100A11;HSP90AB1;AGL;CNN2;RAB5B;CFD;XR...,colon,1.288740,2044.0,8,1070.125,810.0
6010,Neutrophil degranulation,0.002989,2.680652,0.278468,0.422340,479,427,AHSG;EEF2;SERPINA1;TIMP2;COPB1;A1BG;PSMD2;DYNL...,AHSG;EEF2;SERPINA1;TIMP2;COPB1;A1BG;PSMD2;DYNL...,endometrial,2.680652,670.0,8,1070.125,810.0
6011,Neutrophil degranulation,0.002578,1.896457,0.591257,0.756377,479,432,AP2A2;HSPA8;TOLLIP;ATP6V1D;LRRC7;NDUFC2;KCNAB2...,AP2A2;HSPA8;TOLLIP;ATP6V1D;LRRC7;NDUFC2;KCNAB2...,gbm,1.896457,1382.0,8,1070.125,810.0
6012,Neutrophil degranulation,0.007681,6.302835,0.000000,0.117560,479,448,SPTAN1;AHSG;TTR;CFD;ORM2;A1BG;SERPINA1;CNN2;RA...,SPTAN1;AHSG;TTR;CFD;ORM2;A1BG;SERPINA1;CNN2;RA...,hnscc,6.302835,3.0,8,1070.125,810.0
6013,Neutrophil degranulation,-0.001616,-1.097103,0.833989,0.991152,479,423,SPTAN1;EEF2;VAT1;CD93;CD55;CAT;SERPINB6;PECAM1...,HVCN1;MME;MAGT1;ERP44;CREG1;OSCAR;CTSB;TBC1D10...,lscc,1.097103,2168.0,8,1070.125,810.0
6014,Neutrophil degranulation,0.001567,1.201670,0.827846,0.978272,479,409,SPTAN1;CAT;PECAM1;VCL;ANXA2;CD36;HBB;CD93;RAP1...,SPTAN1;CAT;PECAM1;VCL;ANXA2;CD36;HBB;CD93;RAP1...,luad,1.201670,2111.0,8,1070.125,810.0
6015,Neutrophil degranulation,0.004403,3.879352,0.060136,0.146381,479,418,HSP90AB1;STOM;PRSS3;HSP90AA1;ILF2;COPB1;PECAM1...,HSP90AB1;STOM;PRSS3;HSP90AA1;ILF2;COPB1;PECAM1...,ovarian,3.879352,157.0,8,1070.125,810.0

In [16]:
find_neutrophil_degranulation(STEP5_diff_of_classes)

,Term,es,nes,pval,fdr,geneset_size,matched_size,genes,ledge_genes,cancer_type,abs_nes,cancer_rank_abs_nes,pathway_times_enriched,pathway_avg_rank,pathway_overall_rank
4648,Neutrophil degranulation,0.007110,2.916172,0.110717,0.432739,479,427,FCER1G;TYROBP;FTL;PYGL;FTH1;ITGAX;SLC2A3;CYBB;...,FCER1G;TYROBP;FTL;PYGL;FTH1;ITGAX;SLC2A3;CYBB;...,ccrcc,2.916172,290.0,8,905.75,589.0
4649,Neutrophil degranulation,0.003611,1.361710,0.687558,0.877918,479,405,S100P;S100A9;S100A8;S100A11;S100A12;CAMP;LCN2;...,S100P;S100A9;S100A8;S100A11;S100A12;CAMP;LCN2;...,colon,1.361710,2038.0,8,905.75,589.0
4650,Neutrophil degranulation,0.007459,3.010094,0.150508,0.472200,479,427,S100A8;S100A9;FCER1G;LTF;S100A12;DSP;LCN2;CAMP...,S100A8;S100A9;FCER1G;LTF;S100A12;DSP;LCN2;CAMP...,endometrial,3.010094,416.0,8,905.75,589.0
4651,Neutrophil degranulation,0.007662,2.595841,0.263342,0.463252,479,432,SERPINA1;HBB;S100A11;ANXA2;FCER1G;CD44;SERPINA...,SERPINA1;HBB;S100A11;ANXA2;FCER1G;CD44;SERPINA...,gbm,2.595841,873.0,8,905.75,589.0
4652,Neutrophil degranulation,0.003426,1.396537,0.981333,0.982389,479,448,MGAM;AOC1;CEP290;CR1;FCER1G;CAMP;PLAU;EPX;MCEM...,MGAM;AOC1;CEP290;CR1;FCER1G;CAMP;PLAU;EPX;MCEM...,hnscc,1.396537,2032.0,8,905.75,589.0
4653,Neutrophil degranulation,-0.007284,-2.930507,0.227658,0.353054,479,423,DSP;PKP1;PLAU;SERPINB3;CKAP4;JUP;TNFAIP6;S100A...,TNFRSF1B;PFKL;HSPA1A;ADGRG3;HSPA6;DYNLL1;DEFA4...,lscc,2.930507,518.0,8,905.75,589.0
4654,Neutrophil degranulation,-0.006764,-2.964457,0.179889,0.338823,479,409,DSP;PLAU;TXNDC5;CKAP4;MLEC;NEU1;DNAJC3;FUCA1;H...,GOLGA7;TRAPPC1;RAB7A;YPEL5;ACLY;PDXK;IST1;TNFR...,luad,2.964457,425.0,8,905.75,589.0
4655,Neutrophil degranulation,-0.005635,-2.796377,0.210771,0.413294,479,418,NPC2;PKM;HSP90AB1;ILF2;MIF;SRP14;HSP90AA1;CD47...,PLEKHO2;HEBP2;ROCK1;CTSH;ARHGAP9;SDCBP;CR1;CPP...,ovarian,2.796377,654.0,8,905.75,589.0

In [17]:
find_neutrophil_degranulation(STEP5_log2_ratio_of_classes)

,Term,es,nes,pval,fdr,geneset_size,matched_size,genes,ledge_genes,cancer_type,abs_nes,cancer_rank_abs_nes,pathway_times_enriched,pathway_avg_rank,pathway_overall_rank
3200,Neutrophil degranulation,0.003483,2.695486,0.202147,0.628476,479,427,ERCC6L;ZNF121;TERF2IP;POLR3D;BAAT;SMG7;IL6ST;C...,ERCC6L;ZNF121;TERF2IP;POLR3D;BAAT;SMG7;IL6ST;C...,ccrcc,2.695486,609.0,8,826.5,412.0
3201,Neutrophil degranulation,-0.005050,-2.572777,0.042137,0.337050,479,405,FBXO22;CHUK;ABAT;HSPA4;LFNG;PLXNA1;GIT1;CDS1;U...,PDXDC1;PDZD11;PFN1;PGAM1;PGM1;PGM3;PGM5;PGP;PH...,colon,2.572777,1052.0,8,826.5,412.0
3202,Neutrophil degranulation,0.002896,10.182593,0.239544,0.054197,479,427,PRPF31;ABCC10;AKR1D1;CPNE9;C9orf40;PPM1J;ALG11...,PRPF31;ABCC10;AKR1D1;CPNE9;C9orf40;PPM1J;ALG11...,endometrial,10.182593,195.0,8,826.5,412.0
3203,Neutrophil degranulation,0.001957,1.328865,0.861328,0.868842,479,432,CASTOR1;ELN;CC2D2A;SHC4;AMACR;C16orf87;PSAT1;T...,CASTOR1;ELN;CC2D2A;SHC4;AMACR;C16orf87;PSAT1;T...,gbm,1.328865,1982.0,8,826.5,412.0
3204,Neutrophil degranulation,0.004906,1.833549,0.602496,0.828161,479,448,PTPRN2;P2RX1;AOC1;MMP25;NFASC;MCEMP1;MGAM;CEP2...,PTPRN2;P2RX1;AOC1;MMP25;NFASC;MCEMP1;MGAM;CEP2...,hnscc,1.833549,1624.0,8,826.5,412.0
3205,Neutrophil degranulation,-0.002328,-8.343168,0.305369,0.091072,479,423,REXO1;FBLL1;LSM3;HCLS1;FARSA;PLEKHB2;STIM2;ISC...,PYGL;PZP;RAB27B;RAB2B;RAB44;RAB4A;RALGPS2;RAP1...,lscc,8.343168,113.0,8,826.5,412.0
3206,Neutrophil degranulation,0.003349,5.331940,0.054545,0.225238,479,409,HNRNPD;TNFAIP8;NUP210L;KIF1A;EIF4ENIF1;UMAD1;T...,HNRNPD;TNFAIP8;NUP210L;KIF1A;EIF4ENIF1;UMAD1;T...,luad,5.331940,313.0,8,826.5,412.0
3207,Neutrophil degranulation,0.001989,2.358804,0.816527,0.744629,479,418,UGDH;MED6;DIEXF;MED17;ERMP1;KRT33A;UROD;TMEM21...,UGDH;MED6;DIEXF;MED17;ERMP1;KRT33A;UROD;TMEM21...,ovarian,2.358804,724.0,8,826.5,412.0

In [18]:
find_neutrophil_degranulation(STEP5_ratio_of_classes)

Empty DataFrame
Columns: [Term, es, nes, pval, fdr, geneset_size, matched_size, genes, ledge_genes, cancer_type, abs_nes, cancer_rank_abs_nes, pathway_times_enriched, pathway_avg_rank, pathway_overall_rank]
Index: []

In [19]:
find_neutrophil_degranulation(STEP5_signal_to_noise)

Empty DataFrame
Columns: [Term, es, nes, pval, fdr, geneset_size, matched_size, genes, ledge_genes, cancer_type, abs_nes, cancer_rank_abs_nes, pathway_times_enriched, pathway_avg_rank, pathway_overall_rank]
Index: []

In [20]:
find_neutrophil_degranulation(STEP5_t_test)

,Term,es,nes,pval,fdr,geneset_size,matched_size,genes,ledge_genes,cancer_type,abs_nes,cancer_rank_abs_nes,pathway_times_enriched,pathway_avg_rank,pathway_overall_rank
4696,Neutrophil degranulation,0.005522,2.955199,0.136962,0.334243,479,427,PYGL;TYROBP;FCER1G;ITGAX;RAP2B;CYBB;LPCAT1;ALD...,PYGL;TYROBP;FCER1G;ITGAX;RAP2B;CYBB;LPCAT1;ALD...,ccrcc,2.955199,456.0,8,885.5,599.0
4697,Neutrophil degranulation,0.002632,1.086810,0.811286,0.949159,479,405,S100A11;HSP90AB1;CNN2;XRCC6;S100P;ILF2;PA2G4;P...,S100A11;HSP90AB1;CNN2;XRCC6;S100P;ILF2;PA2G4;P...,colon,1.086810,2124.0,8,885.5,599.0
4698,Neutrophil degranulation,0.005960,2.717769,0.237179,0.508867,479,427,EEF2;COPB1;PSMD2;DYNLT1;DSP;JUP;PKM;PSMD1;NBEA...,EEF2;COPB1;PSMD2;DYNLT1;DSP;JUP;PKM;PSMD1;NBEA...,endometrial,2.717769,700.0,8,885.5,599.0
4699,Neutrophil degranulation,0.006129,2.254714,0.335683,0.563805,479,432,IDH1;PGM2;EEF1A1;IQGAP2;APAF1;STK10;CPNE3;TYRO...,IDH1;PGM2;EEF1A1;IQGAP2;APAF1;STK10;CPNE3;TYRO...,gbm,2.254714,1338.0,8,885.5,599.0
4700,Neutrophil degranulation,0.005945,3.208612,0.115044,0.272058,479,448,CNN2;PLAU;LPCAT1;IGF2R;FCER1G;HSP90AB1;MNDA;IT...,CNN2;PLAU;LPCAT1;IGF2R;FCER1G;HSP90AB1;MNDA;IT...,hnscc,3.208612,392.0,8,885.5,599.0
4701,Neutrophil degranulation,-0.007284,-2.939425,0.204864,0.376328,479,423,EEF2;CKAP4;DDX3X;DSP;HSP90AB1;ILF2;PLAU;PA2G4;...,TNFRSF1B;PFKL;ADGRG3;HSPA1A;HSPA6;DEFA4;CAMP;H...,lscc,2.939425,602.0,8,885.5,599.0
4702,Neutrophil degranulation,-0.006826,-3.187648,0.122283,0.303843,479,409,COPB1;SRP14;EEF2;PSMD3;HSP90AB1;PSMD6;PDAP1;DN...,GSDMD;GM2A;HLA-B;QSOX1;RHOA;TUBB4B;TCN1;SERPIN...,luad,3.187648,384.0,8,885.5,599.0
4703,Neutrophil degranulation,-0.004695,-2.395540,0.324248,0.570197,479,418,HSP90AB1;HSP90AA1;ILF2;COPB1;EEF1A1;EEF2;PKM;X...,LAIR1;LILRB2;DBNL;ARSB;CEP290;GUSB;DYNC1H1;TMC...,ovarian,2.395540,1088.0,8,885.5,599.0

## Figure 2: Expression of proteins in the neutrophil degranulation pathway

In [ ]:
# Get the ID the top expessed pathway
neutro_pathway_ids = enrichment_data.\
    loc[enrichment_data["name"] == "Neutrophil degranulation", "pathway_id"].\
    unique()

if len(neutro_pathway_ids) != 1:
    raise ValueError("Multiple pathways found.")
    
neutro_pathway_id = neutro_pathway_ids[0]

### A: With proteins in different orders for the up and down categories

In [ ]:
def expr_heatmap(expr_data, enrich_data, pathway_id, up_or_down, max_p, x_title=True):
    """Make a heatmap with proteins on the X axis, cancer types on the Y 
    axis, and the color reflecting the expression of that protein in that
    cancer type.
    
    Parameters:
    expr_data (pandas.DataFrame): A dataframe with columns "cancer_type", "protein_str", "adj_p", and "simplified_change".
    enrich_data (pandas.DataFrame): A dataframe with columns "cancer_type" and "mean_expr" (i.e. mean expression for the pathway of interest).
    pathway_id (str): The Reactome pathway id for the pathway you want the heatmap for.
    up_or_down (str): Either "up" or "down"; whether to plot cancers where the pathway is up, or where it's down.
    max_p (float): The minimum p value for a protein to be included on the plot. If max_p > 0.05, then proteins with 0.05 <= p < max_p will be marked as marginally significant.
    x_title (bool): Whether to include an x axis title.
    
    Returns:
    altair.Chart: The heatmap.
    """
    # Filter expression data by p value
    expr_data = expr_data[expr_data["adj_p"] < max_p]
    
    # Get expression data for proteins in the pathway
    pathway_proteins = ut.search_reactome_proteins_in_pathways(pathway_id)
    pathway_expr = expr_data[expr_data["protein_str"].isin(pathway_proteins["member"])]
    
    # Categorize the cancer types as the neutrophil degranulation pathway's mean expression being up or down
    if up_or_down == "up":
        comparison = operator.gt
    elif up_or_down == "down":
        comparison = operator.lt
    else:
        raise ValueError(f"Invalid value for up_or_down parameter: '{up_or_down}'")
    
    sel_cancers = enrich_data.\
        loc[(enrich_data["pathway_id"] == neutro_pathway_id) & (comparison(enrich_data["mean_expr"], 0)),
           ["cancer_type", "mean_expr"]]

    # Select data for the specified cancer types
    selected_expr_data = pathway_expr[pathway_expr["cancer_type"].isin(sel_cancers["cancer_type"])]

    # Sort proteins by mean expression across selected cancer types
    prot_order = selected_expr_data.groupby("protein_str")[["simplified_change", "cancer_type"]].\
        agg({
            "simplified_change": np.mean,
            "cancer_type": "count"
        })

    prot_order = prot_order.assign(
            cancer_type=np.copysign(prot_order["cancer_type"], prot_order["simplified_change"])
        ).\
        sort_values(by=["simplified_change", "cancer_type"])

    # Sort cancer types by mean pathway expression
    cancer_order = sel_cancers.\
        sort_values(by="mean_expr", ascending=False).\
        loc[:, "cancer_type"]
    
    # Map simplified_change to legend values
    selected_expr_data = selected_expr_data.assign(
        tumor_up_down=selected_expr_data["simplified_change"].replace({
            1: "Up (adj p < 0.05)",
            MSV: f"Up (0.05 <= adj p < {max_p})",
            0: "No change",
            -MSV: f"Down (0.05 <= adj p < {max_p})",
            -1: "Down (adj p < 0.05)"
        })
    )
    
    # Plot
    plot = alt.Chart(selected_expr_data).mark_rect().encode(
        x=alt.X(
            "protein_str:N",
            sort=prot_order.index.values,
            axis=alt.Axis(
                labels=False,
                ticks=False,
                title=f"Proteins for {pathway_id} (different order in each facet)" if x_title else ""
            )
        ),
        y=alt.Y(
            "cancer_type:N",
            sort=cancer_order.values,
            axis=alt.Axis(
                title=f"Pathway {up_or_down} in tumor"
            )
        ),
        color=alt.Color(
            "tumor_up_down:N",
            scale=alt.Scale(
                domain=[
                    "Up (adj p < 0.05)",
                    f"Up (0.05 <= adj p < {max_p})",
                    "No change",
                    f"Down (0.05 <= adj p < {max_p})",
                    "Down (adj p < 0.05)"
                ],
                range=["#bf363a",
                       "#f6bda4",
                       "#f2efee",
                       "#afd3e6",
                       "#1e588a"
                ]
            ),
            legend=alt.Legend(
                title="Expression in tumor"
            )
        ),
    ).properties(
        width=700,
        height=175
    )
    
    return plot

In [ ]:
# Plot
alt.vconcat(
    expr_heatmap(all_expression_data, enrichment_data, neutro_pathway_id, "up", max_p=0.2, x_title=False),
    expr_heatmap(all_expression_data, enrichment_data, neutro_pathway_id, "down", max_p=0.2)
)

### B: With same sorting for both

In [ ]:
def expr_heatmap_alt_sort(expr_data, enrich_data, pathway_id, max_p):
    """Make a heatmap with proteins on the X axis, cancer types on the Y 
    axis, and the color reflecting the expression of that protein in that
    cancer type.
    
    Parameters:
    expr_data (pandas.DataFrame): A dataframe with columns "cancer_type", "protein_str", "adj_p", and "simplified_change".
    enrich_data (pandas.DataFrame): A dataframe with columns "cancer_type" and "mean_expr" (i.e. mean expression for the pathway of interest).
    pathway_id (str): The Reactome pathway id for the pathway you want the heatmap for.
    up_or_down (str): Either "up" or "down"; whether to plot cancers where the pathway is up, or where it's down.
    max_p (float): The minimum p value for a protein to be included on the plot. If max_p > 0.05, then proteins with 0.05 <= p < max_p will be marked as marginally significant.
    
    Returns:
    altair.Chart: The heatmap.
    """
    # Filter expression data by p value
    expr_data = expr_data[expr_data["adj_p"] < max_p]
    
    # Get expression data for proteins in the pathway
    pathway_proteins = ut.search_reactome_proteins_in_pathways(pathway_id)
    pathway_expr = expr_data[expr_data["protein_str"].isin(pathway_proteins["member"])]
    
    # Sort proteins by mean expression across all cancer types
    prot_order = pathway_expr.groupby("protein_str")[["simplified_change", "cancer_type"]].\
        agg({
            "simplified_change": np.mean,
            "cancer_type": "count"
        })

    prot_order = prot_order.assign(
            cancer_type=np.copysign(prot_order["cancer_type"], prot_order["simplified_change"])
        ).\
        sort_values(by=["simplified_change", "cancer_type"])

    # Sort cancer types by mean pathway expression
    sel_cancers = enrich_data.\
        loc[enrich_data["pathway_id"] == neutro_pathway_id, ["cancer_type", "mean_expr"]]
        
    sel_cancers = sel_cancers.\
        assign(up_or_down=np.where(sel_cancers["mean_expr"] > 0, "Pathway up in tumor", "Pathway down in tumor")).\
        sort_values(by="mean_expr", ascending=False).\
        loc[:, ["cancer_type", "up_or_down"]]
    
    cancer_order = sel_cancers["cancer_type"].values
    
    pathway_expr = pathway_expr.merge(
        right=sel_cancers,
        how="inner",
        left_on="cancer_type",
        right_on="cancer_type",
        validate="many_to_one"
    )
    
    # Map simplified_change to legend values
    pathway_expr = pathway_expr.assign(
        tumor_up_down=pathway_expr["simplified_change"].replace({
            1: "Up (adj p < 0.05)",
            MSV: f"Up (0.05 <= adj p < {max_p})",
            0: "No change",
            -MSV: f"Down (0.05 <= adj p < {max_p})",
            -1: "Down (adj p < 0.05)"
        })
    )
    
    # Plot
    plot = alt.Chart(pathway_expr).mark_rect().encode(
        x=alt.X(
            "protein_str:N",
            sort=prot_order.index.values,
            axis=alt.Axis(
                labels=False,
                ticks=False,
                title=f"Proteins for {pathway_id} (same order in both facets)"
            )
        ),
        y=alt.Y(
            "cancer_type:N",
            sort=cancer_order,
            axis=alt.Axis(
                title=""
            )
        ),
        color=alt.Color(
            "tumor_up_down:N",
            scale=alt.Scale(
                domain=[
                    "Up (adj p < 0.05)",
                    f"Up (0.05 <= adj p < {max_p})",
                    "No change",
                    f"Down (0.05 <= adj p < {max_p})",
                    "Down (adj p < 0.05)"
                ],
                range=["#bf363a",
                       "#f6bda4",
                       "#f2efee",
                       "#afd3e6",
                       "#1e588a"
                ]
            ),
            legend=alt.Legend(
                title="Expression in tumor"
            )
        ),
        row=alt.Row(
            "up_or_down:N",
            sort="descending",
            title="",
            header=alt.Header(
                labelFontStyle="bold"
            )
        )
    ).properties(
        width=600,
        height=150
    ).resolve_scale(
        y="independent" # This makes it so each facet (up or down) only has the cancers that are in that category
    )
    
    return plot

In [ ]:
# Plot
expr_heatmap_alt_sort(all_expression_data, enrichment_data, neutro_pathway_id, max_p=0.2)

## Figure 3: Pathway overlay for neutrophil degranulation

In [ ]:
def pathway_overlay_wrapper(pathway_id, exp_data, enrich_data, up_or_down):
    
    prots = ut.search_reactome_proteins_in_pathways(pathway_id)
    
    # Categorize the cancer types as the neutrophil degranulation pathway's mean expression being up or down
    if up_or_down == "up":
        comparison = operator.gt
    elif up_or_down == "down":
        comparison = operator.lt
    else:
        raise ValueError(f"Invalid value for up_or_down parameter: '{up_or_down}'")
    
    sel_cancers = enrich_data.\
        loc[(enrich_data["pathway_id"] == neutro_pathway_id) & (comparison(enrich_data["mean_expr"], 0)),
            "cancer_type"]
    
    # Select the desired expression data and average the simplified change across cancer types
    sel_exp = exp_data.\
        loc[
            exp_data["protein_str"].isin(prots["member"]) & 
            exp_data["cancer_type"].isin(sel_cancers),
            ["protein_str", "simplified_change"]
        ].\
        groupby("protein_str").\
        agg(np.mean).\
        rename(columns={"simplified_change": f"{up_or_down}_simp_change"})
    
    img_name = f"{TIME_START}_{pathway_id}_{up_or_down}.png"
    img_path = os.path.join(STEP7_DIR, img_name)
    
    token, _ = ut.reactome_enrichment_analysis(
        analysis_type="ranked", 
        data=sel_exp, 
        sort_by="ENTITIES_FDR", 
        ascending=True,
        include_high_level_diagrams=True, 
        include_interactors=False)
    
    _, img_path = ut.reactome_pathway_overlay(
        analysis_token=token,
        pathway=pathway_id,
        open_browser=False,
        export_path=img_path,
        image_format="png",
        display_col_idx=None,
        diagram_colors="Modern",
        overlay_colors="Standard",
        quality=10
    )

    _, url = ut.reactome_pathway_overlay(
        analysis_token=token,
        pathway=pathway_id,
        open_browser=False,
    )

    return img_path, url

In [ ]:
# Note that we're using expression_data, not all_expression_data; the former has
# only proteins where reject_null

up_image_path, up_url = pathway_overlay_wrapper(neutro_pathway_id, expression_data, enrichment_data, "up")

In [ ]:
IPython.display.HTML(f'<a href={up_url}>{up_url}</a>')

In [ ]:
IPython.display.Image(up_image_path)

In [ ]:
# Note that we're using expression_data, not all_expression_data; the former has
# only proteins where reject_null

down_image_path, down_url = pathway_overlay_wrapper(neutro_pathway_id, expression_data, enrichment_data, "down")

In [ ]:
IPython.display.HTML(f'<a href={down_url}>{down_url}</a>')

In [ ]:
IPython.display.Image(down_image_path)