# Experiments

In [1]:
import cptac
import cptac.utils as ut
import pandas as pd
import numpy as np
import gseapy as gp
import os
import datetime

In [2]:
TIME_START = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
STEP1_FILE = "tumor_change_20200529_195104_10000_perm.tsv"
STEP1_FILE_PATH = "step1_outputs/" + STEP1_FILE

In [3]:
# Read in the file from step 1
data = pd.read_csv(STEP1_FILE_PATH, sep='\t', index_col=0)

# Only keep genes with P values below the cutoff
data = data[data["reject_null"]]

In [4]:
# In the omics data, make all increases +1 and decreases -1
# Because these are ratioed abundances, we can't compare magnitudes between
# genes--we can only compare positive or negative
data = data.assign(simplified_change=data["change"])

data.loc[data["change"] > 0, "simplified_change"] = 1
data.loc[data["change"] < 0, "simplified_change"] = -1
data.loc[data["change"] == 0, "simplified_change"] = 0

In [18]:
import requests

def get_resp(pathway_ids, quiet=False):
    """Query the Reactome REST API to get a list of proteins contained in a particular pathway.

    Parameters:
    pathway_id (str): The pathway to get the contained proteins for.

    Returns:
    list: The proteins contained in the pathway.
    """
    # Process string input
    if isinstance(pathway_ids, str):
        pathway_ids = [pathway_ids]

    # Set headers and url
    headers = {"accept": "application/json"}

    # Loop over ids and get the interacting pathways
    all_pathway_df = pd.DataFrame()
    for pathway_id in pathway_ids:

        # Send the request
        url = f"https://reactome.org/ContentService/data/participants/{pathway_id}"
        resp = requests.get(url, headers=headers)

        if resp.status_code == 404 or (resp.status_code == requests.codes.ok and (len(resp.content.decode("utf-8")) == 0 or len(resp.json()) == 0)):
            if not quiet:
                warnings.warn(f"The query for '{pathway_id}' found no results. You may have mistyped the pathway ID.", ParameterWarning, stacklevel=2)
            continue
        elif resp.status_code != requests.codes.ok:
            raise HttpResponseError(f"Your query returned an HTTP status {resp.status_code}. The content returned from the request may be helpful:\n{resp.content.decode('utf-8')}")
        
        return resp

In [19]:
resp = get_resp("R-HSA-9006934")
# resp = search_reactome_proteins_in_pathways("R-HSA-2404192")

In [20]:
resp.json()

[{'peDbId': 9031773,
  'displayName': 'PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]',
  'schemaClass': 'DefinedSet',
  'refEntities': [{'identifier': 'P06241',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06241 FYN',
    'dbId': 55160,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06241'},
   {'identifier': 'P06239',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06239 LCK',
    'dbId': 58457,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06239'},
   {'identifier': 'P12931-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P12931-1 SRC',
    'dbId': 65044,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P12931-1'},
   {'identifier': 'P07947',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07947 YES1',
    'dbId': 67748,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07947'},
   {'identifier': 'P07948',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07948 LYN',
    'dbId': 58853,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07948'},
   {'identifier': 'P10721',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P10721 KIT',
    'dbId': 58103,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P10721'},
   {'identifier': 'P21583-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P21583-1 KITLG',
    'dbId': 403295,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P21583-1'},
   {'identifier': 'Q06124',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q06124 PTPN11',
    'dbId': 62439,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q06124'},
   {'identifier': 'P62993-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P62993-1 GRB2',
    'dbId': 55928,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P62993-1'},
   {'identifier': 'P42336',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P42336 PIK3CA',
    'dbId': 61074,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P42336'},
   {'identifier': 'Q92569',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q92569 PIK3R3',
    'dbId': 61182,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q92569'},
   {'identifier': 'O00459',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:O00459 PIK3R2',
    'dbId': 61194,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/O00459'},
   {'identifier': 'P27986',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P27986 PIK3R1',
    'dbId': 61192,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P27986'},
   {'identifier': 'Q9UQC2',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q9UQC2 GAB2',
    'dbId': 147728,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q9UQC2'}]},
 {'peDbId': 179856,
  'displayName': 'PI(4,5)P2 [plasma membrane]',
  'schemaClass': 'SimpleEntity',
  'refEntities': [{'identifier': '18348',
    'schemaClass': 'ReferenceMolecule',
    'displayName': '1-phosphatidyl-1D-myo-inositol 4,5-bisphosphate [ChEBI:18348]',
    'dbId': 188413,
    'icon': 'SimpleEntity',
    'url': 'http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18348'}]},
 {'peDbId': 113592,
  'displayName': 'ATP [cytosol]',
  'schemaClass': 'SimpleEntity',
  'refEntities': [{'identifier': '30616',
    'schemaClass': 'ReferenceMolecule',
    'displayName': 'ATP(4-) [ChEBI:30616]',
    'dbId': 8869364,
    'icon': 'SimpleEntity',
    'url': 'http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:30616'}]},
 {'peDbId': 29370,
  'displayName': 'ADP [cytosol]',
  'schemaClass': 'SimpleEntity',
  'refEntities': [{'identifier': '456216',
    'schemaClass': 'ReferenceMolecule',
    'displayName': 'ADP(3-) [ChEBI:456216]',
    'dbId': 8869367,
    'icon': 'SimpleEntity',
    'url': 'http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:456216'}]},
 {'peDbId': 179838,
  'displayName': 'PI(3,4,5)P3 [plasma membrane]',
  'schemaClass': 'SimpleEntity',
  'refEntities': [{'identifier': '16618',
    'schemaClass': 'ReferenceMolecule',
    'displayName': '1-phosphatidyl-1D-myo-inositol 3,4,5-trisphosphate [ChEBI:16618]',
    'dbId': 188411,
    'icon': 'SimpleEntity',
    'url': 'http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16618'}]},
 {'peDbId': 205271,
  'displayName': 'SFKs:p-KIT complex [plasma membrane]',
  'schemaClass': 'Complex',
  'refEntities': [{'identifier': 'P06241',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06241 FYN',
    'dbId': 55160,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06241'},
   {'identifier': 'P06239',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06239 LCK',
    'dbId': 58457,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06239'},
   {'identifier': 'P12931-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P12931-1 SRC',
    'dbId': 65044,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P12931-1'},
   {'identifier': 'P07947',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07947 YES1',
    'dbId': 67748,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07947'},
   {'identifier': 'P07948',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07948 LYN',
    'dbId': 58853,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07948'},
   {'identifier': 'P10721',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P10721 KIT',
    'dbId': 58103,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P10721'},
   {'identifier': 'P21583-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P21583-1 KITLG',
    'dbId': 403295,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P21583-1'}]},
 {'peDbId': 210620,
  'displayName': 'JAK2 [cytosol]',
  'schemaClass': 'EntityWithAccessionedSequence',
  'refEntities': [{'identifier': 'O60674',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:O60674 JAK2',
    'dbId': 57647,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/O60674'}]},
 {'peDbId': 1433493,
  'displayName': 'JAK2:SFKS:p-KIT complex [plasma membrane]',
  'schemaClass': 'Complex',
  'refEntities': [{'identifier': 'P06241',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06241 FYN',
    'dbId': 55160,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06241'},
   {'identifier': 'P06239',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06239 LCK',
    'dbId': 58457,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06239'},
   {'identifier': 'P12931-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P12931-1 SRC',
    'dbId': 65044,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P12931-1'},
   {'identifier': 'P07947',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07947 YES1',
    'dbId': 67748,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07947'},
   {'identifier': 'P07948',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07948 LYN',
    'dbId': 58853,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07948'},
   {'identifier': 'P10721',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P10721 KIT',
    'dbId': 58103,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P10721'},
   {'identifier': 'P21583-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P21583-1 KITLG',
    'dbId': 403295,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P21583-1'},
   {'identifier': 'O60674',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:O60674 JAK2',
    'dbId': 57647,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/O60674'}]},
 {'peDbId': 1433545,
  'displayName': 'GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]',
  'schemaClass': 'Complex',
  'refEntities': [{'identifier': 'Q9UQC2',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q9UQC2 GAB2',
    'dbId': 147728,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q9UQC2'},
   {'identifier': 'P06241',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06241 FYN',
    'dbId': 55160,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06241'},
   {'identifier': 'P06239',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06239 LCK',
    'dbId': 58457,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06239'},
   {'identifier': 'P12931-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P12931-1 SRC',
    'dbId': 65044,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P12931-1'},
   {'identifier': 'P07947',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07947 YES1',
    'dbId': 67748,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07947'},
   {'identifier': 'P07948',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07948 LYN',
    'dbId': 58853,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07948'},
   {'identifier': 'P10721',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P10721 KIT',
    'dbId': 58103,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P10721'},
   {'identifier': 'P21583-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P21583-1 KITLG',
    'dbId': 403295,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P21583-1'},
   {'identifier': 'Q06124',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q06124 PTPN11',
    'dbId': 62439,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q06124'},
   {'identifier': 'P62993-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P62993-1 GRB2',
    'dbId': 55928,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P62993-1'}]},
 {'peDbId': 1562560,
  'displayName': 'p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]',
  'schemaClass': 'Complex',
  'refEntities': [{'identifier': 'P06241',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06241 FYN',
    'dbId': 55160,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06241'},
   {'identifier': 'P06239',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06239 LCK',
    'dbId': 58457,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06239'},
   {'identifier': 'P12931-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P12931-1 SRC',
    'dbId': 65044,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P12931-1'},
   {'identifier': 'P07947',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07947 YES1',
    'dbId': 67748,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07947'},
   {'identifier': 'P07948',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07948 LYN',
    'dbId': 58853,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07948'},
   {'identifier': 'P10721',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P10721 KIT',
    'dbId': 58103,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P10721'},
   {'identifier': 'P21583-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P21583-1 KITLG',
    'dbId': 403295,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P21583-1'},
   {'identifier': 'Q06124',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q06124 PTPN11',
    'dbId': 62439,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q06124'},
   {'identifier': 'P62993-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P62993-1 GRB2',
    'dbId': 55928,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P62993-1'},
   {'identifier': 'Q9UQC2',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q9UQC2 GAB2',
    'dbId': 147728,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q9UQC2'}]},
 {'peDbId': 162563,
  'displayName': 'PTPN11 [cytosol]',
  'schemaClass': 'EntityWithAccessionedSequence',
  'refEntities': [{'identifier': 'Q06124',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q06124 PTPN11',
    'dbId': 62439,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q06124'}]},
 {'peDbId': 205267,
  'displayName': 'SHP2:SFKs:p-KIT:sSCF dimer:p-KIT [plasma membrane]',
  'schemaClass': 'Complex',
  'refEntities': [{'identifier': 'Q06124',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q06124 PTPN11',
    'dbId': 62439,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q06124'},
   {'identifier': 'P06241',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06241 FYN',
    'dbId': 55160,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06241'},
   {'identifier': 'P06239',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06239 LCK',
    'dbId': 58457,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06239'},
   {'identifier': 'P12931-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P12931-1 SRC',
    'dbId': 65044,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P12931-1'},
   {'identifier': 'P07947',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07947 YES1',
    'dbId': 67748,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07947'},
   {'identifier': 'P07948',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07948 LYN',
    'dbId': 58853,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07948'},
   {'identifier': 'P10721',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P10721 KIT',
    'dbId': 58103,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P10721'},
   {'identifier': 'P21583-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P21583-1 KITLG',
    'dbId': 403295,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P21583-1'}]},
 {'peDbId': 1433549,
  'displayName': 'GRB2:p-SHP2:p-KIT complex [plasma membrane]',
  'schemaClass': 'Complex',
  'refEntities': [{'identifier': 'P06241',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06241 FYN',
    'dbId': 55160,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06241'},
   {'identifier': 'P06239',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06239 LCK',
    'dbId': 58457,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06239'},
   {'identifier': 'P12931-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P12931-1 SRC',
    'dbId': 65044,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P12931-1'},
   {'identifier': 'P07947',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07947 YES1',
    'dbId': 67748,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07947'},
   {'identifier': 'P07948',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07948 LYN',
    'dbId': 58853,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07948'},
   {'identifier': 'P10721',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P10721 KIT',
    'dbId': 58103,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P10721'},
   {'identifier': 'P21583-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P21583-1 KITLG',
    'dbId': 403295,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P21583-1'},
   {'identifier': 'Q06124',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q06124 PTPN11',
    'dbId': 62439,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q06124'},
   {'identifier': 'P62993-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P62993-1 GRB2',
    'dbId': 55928,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P62993-1'}]},
 {'peDbId': 508239,
  'displayName': 'GAB2 [cytosol]',
  'schemaClass': 'EntityWithAccessionedSequence',
  'refEntities': [{'identifier': 'Q9UQC2',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:Q9UQC2 GAB2',
    'dbId': 147728,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/Q9UQC2'}]},
 {'peDbId': 1433527,
  'displayName': 'p-JAK2:SFKs:p-KIT complex:STATs [plasma membrane]',
  'schemaClass': 'Complex',
  'refEntities': [{'identifier': 'P06241',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06241 FYN',
    'dbId': 55160,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06241'},
   {'identifier': 'P06239',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P06239 LCK',
    'dbId': 58457,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P06239'},
   {'identifier': 'P12931-1',
    'schemaClass': 'ReferenceIsoform',
    'displayName': 'UniProt:P12931-1 SRC',
    'dbId': 65044,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P12931-1'},
   {'identifier': 'P07947',
    'schemaClass': 'ReferenceGeneProduct',
    'displayName': 'UniProt:P07947 YES1',
    'dbId': 67748,
    'icon': 'EntityWithAccessionedSequence',
    'url': 'https://purl.uniprot.org/uniprot/P07947'},
   {'identifier': 'P07948',
    'schemaClass': 'ReferenceGeneProduct',

In [21]:
upper = pd.json_normalize(resp.json())

In [22]:
upper

,peDbId,displayName,schemaClass,refEntities
0,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB...",DefinedSet,"[{'identifier': 'P06241', 'schemaClass': 'Refe..."
1,179856,"PI(4,5)P2 [plasma membrane]",SimpleEntity,"[{'identifier': '18348', 'schemaClass': 'Refer..."
2,113592,ATP [cytosol],SimpleEntity,"[{'identifier': '30616', 'schemaClass': 'Refer..."
3,29370,ADP [cytosol],SimpleEntity,"[{'identifier': '456216', 'schemaClass': 'Refe..."
4,179838,"PI(3,4,5)P3 [plasma membrane]",SimpleEntity,"[{'identifier': '16618', 'schemaClass': 'Refer..."
5,205271,SFKs:p-KIT complex [plasma membrane],Complex,"[{'identifier': 'P06241', 'schemaClass': 'Refe..."
6,210620,JAK2 [cytosol],EntityWithAccessionedSequence,"[{'identifier': 'O60674', 'schemaClass': 'Refe..."
7,1433493,JAK2:SFKS:p-KIT complex [plasma membrane],Complex,"[{'identifier': 'P06241', 'schemaClass': 'Refe..."
8,1433545,GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane],Complex,"[{'identifier': 'Q9UQC2', 'schemaClass': 'Refe..."
9,1562560,p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma me...,Complex,"[{'identifier': 'P06241', 'schemaClass': 'Refe..."
10,162563,PTPN11 [cytosol],EntityWithAccessionedSequence,"[{'identifier': 'Q06124', 'schemaClass': 'Refe..."
11,205267,SHP2:SFKs:p-KIT:sSCF dimer:p-KIT [plasma membr...,Complex,"[{'identifier': 'Q06124', 'schemaClass': 'Refe..."
12,1433549,GRB2:p-SHP2:p-KIT complex [plasma membrane],Complex,"[{'identifier': 'P06241', 'schemaClass': 'Refe..."
13,508239,GAB2 [cytosol],EntityWithAccessionedSequence,"[{'identifier': 'Q9UQC2', 'schemaClass': 'Refe..."
14,1433527,p-JAK2:SFKs:p-KIT complex:STATs [plasma membrane],Complex,"[{'identifier': 'P06241', 'schemaClass': 'Refe..."
15,1470000,p-JAK2:SFKs:p-KIT complex:p-STATs [plasma memb...,Complex,"[{'identifier': 'P42224-1', 'schemaClass': 'Re..."
16,1472120,SFKs:p-8Y-KIT:sSCF dimer:p-8Y-KIT [plasma memb...,Complex,"[{'identifier': 'P10721', 'schemaClass': 'Refe..."
17,1469999,p-JAK2:SFKs:p-KIT complex:p-STAT dimers [plasm...,Complex,"[{'identifier': 'P42224-1', 'schemaClass': 'Re..."
18,197662,KIT [plasma membrane],EntityWithAccessionedSequence,"[{'identifier': 'P10721', 'schemaClass': 'Refe..."
19,205166,KIT:sSCF dimer [plasma membrane],Complex,"[{'identifier': 'P10721', 'schemaClass': 'Refe..."
20,205208,KIT:sSCF dimer:KIT [plasma membrane],Complex,"[{'identifier': 'P10721', 'schemaClass': 'Refe..."
21,1433552,p-JAK2:SFKs:p-KIT complex [plasma membrane],Complex,"[{'identifier': 'P06241', 'schemaClass': 'Refe..."
22,1566924,p-STAT dimers [nucleoplasm],Complex,"[{'identifier': 'P51692', 'schemaClass': 'Refe..."
23,205202,GRB2:SOS1:p-KIT complex [plasma membrane],Complex,"[{'identifier': 'Q07889', 'schemaClass': 'Refe..."
24,109796,p21 RAS:GDP [plasma membrane],Complex,"[{'identifier': '17552', 'schemaClass': 'Refer..."
25,29438,GTP [cytosol],SimpleEntity,"[{'identifier': '15996', 'schemaClass': 'Refer..."
26,109783,p21 RAS:GTP [plasma membrane],Complex,"[{'identifier': '15996', 'schemaClass': 'Refer..."
27,29420,GDP [cytosol],SimpleEntity,"[{'identifier': '17552', 'schemaClass': 'Refer..."
28,205310,p-7Y-KIT:sSCF dimer:p-7Y-KIT [plasma membrane],Complex,"[{'identifier': 'P10721', 'schemaClass': 'Refe..."
29,1433473,"p-KIT (S741,746):PKC alpha [plasma membrane]",Complex,"[{'identifier': 'P10721', 'schemaClass': 'Refe..."
...,...,...,...,...
1021,186811,PDGF:Phospho-PDGF receptor dimer [plasma membr...,Complex,"[{'identifier': 'P16234', 'schemaClass': 'Refe..."
1022,186831,PDGF:Phospho-PDGF receptor dimer:MyrG-SRC [pla...,Complex,"[{'identifier': 'P16234', 'schemaClass': 'Refe..."
1023,381955,PDGF:Phospho-PDGF receptor dimer:Crk [plasma m...,Complex,"[{'identifier': 'P16234', 'schemaClass': 'Refe..."
1024,3008672,RAPGEF1 [cytosol],EntityWithAccessionedSequence,"[{'identifier': 'Q13905', 'schemaClass': 'Refe..."
1025,381957,PDGF:Phospho-PDGF receptor dimer:Crk:p130Cas:C...,Complex,"[{'identifier': 'P16234', 'schemaClass': 'Refe..."
1026,381956,PDGF:Phospho-PDGF receptor dimer:Grb7 [plasma ...,Complex,"[{'identifier': 'Q14451', 'schemaClass': 'Refe..."
1027,186827,PDGF:Phospho-PDGF receptor dimer:Grb2:Sos1 [pl...,Complex,"[{'identifier': 'Q07889', 'schemaClass': 'Refe..."
1028,380768,PDGF:Phospho-PDGF receptor dimer:MyrG-p-Y419-S...,Complex,"[{'identifier': 'P12931', 'schemaClass': 'Refe..."
1029,380756,STAT family members [cytosol],DefinedSet,"[{'identifier': 'P42226', 'schemaClass': 'Refe..."
1030,380766,PDGF:phospho-PDGF receptor dimer:STAT [plasma ...,Complex,"[{'identifier': 'P42226', 'schemaClass': 'Refe..."
1031,389074,Phospho PDGF beta receptor: PDGF chain B homod...,Complex,"[{'identifier': 'P09619', 'schemaClass': 'Refe..."
1032,186830,Phospho-beta receptor homodimer:GAP [plasma me...,Complex,"[{'identifier': 'P20936', 'schemaClass': 'Refe..."
1033,186795,PDGF:Phospho-PDGF receptor dimer:PLC-gamma [pl...,Complex,"[{'identifier': 'P19174', 'schemaClass': 'Refe..."
1034,381954,PDGF:Phospho-PDGFR receptor dimer:Nck [plasma ...,Complex,"[{'identifier': 'P16333', 'schemaClass': 'Refe..."
1035,186789,PDGF:Phospho-PDGF receptor dimer:PI3K [plasma ...,Complex,"[{'identifier': 'P27986', 'schemaClass': 'Refe..."
1036,186839,PDGF:Phospho-PDGF receptor dimer:SHP2 [plasma ...,Complex,"[{'identifier': 'Q06124', 'schemaClass': 'Refe..."
1037,381937,serine-type endopeptidases involved in novel P...,DefinedSet,"[{'identifier': 'P00750', 'schemaClass': 'Refe..."
1038,381939,"Active PDGF dimers (CC, DD) [extracellular reg...",DefinedSet,"[{'identifier': 'Q9NRA1-1', 'schemaClass': 'Re..."
1039,389070,Cleaved novel PDGF fragments [extracellular re...,DefinedSet,"[{'identifier': 'Q9NRA1-1', 'schemaClass': 'Re..."
1040,8864037,p-PDGFRB homo and heterodimers [plasma membrane],DefinedSet,"[{'identifier': 'P09619', 'schemaClass': 'Refe..."
1041,8864045,p-PDGFRB homo and heterodimers dephosphorylate...,DefinedSet,"[{'identifier': 'P09619', 'schemaClass': 'Refe..."
1042,381934,PDGF A and B chains with retention motif [extr...,DefinedSet,"[{'identifier': 'P01127', 'schemaClass': 'Refe..."
1043,381946,Extracellular matrix ligands [extracellular re...,DefinedSet,"[{'identifier': 'Q14050', 'schemaClass': 'Refe..."
1044,381952,PDGF A and B chains:ECM complex [extracellular...,Complex,"[{'identifier': 'P01127', 'schemaClass': 'Refe..."
1045,380749,proPDGF-AA dimer [Golgi membrane],Complex,"[{'identifier': 'P04085-1', 'schemaClass': 'Re..."
1046,8865271,N-ter PDGF-A fragment [Golgi lumen],DefinedSet,"[{'identifier': 'P04085-2', 'schemaClass': 'Re..."
1047,380761,active PDGF-AA dimer [extracellular region],Complex,"[{'identifier': 'P04085-1', 'schemaClass': 'Re..."
1048,389078,PDGF beta receptor:PDGF chain B homodimer [pla...,Complex,"[{'identifier': 'P01127', 'schemaClass': 'Refe..."
1049,381936,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [...",DefinedSet,"[{'identifier': 'Q9GZP0', 'schemaClass': 'Refe..."
1050,381926,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [G...",DefinedSet,"[{'identifier': 'P04085-1', 'schemaClass': 'Re..."

In [24]:
pd.options.display.max_colwidth = None

In [25]:
# For a get_members_info function?
out = pd.json_normalize(
    resp.json(),
    record_path=["refEntities"],
    meta=["peDbId", "displayName", "schemaClass"],
    meta_prefix="parent_",
)
out

,identifier,schemaClass,displayName,dbId,icon,url,parent_peDbId,parent_displayName,parent_schemaClass
0,P06241,ReferenceGeneProduct,UniProt:P06241 FYN,55160,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P06241,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
1,P06239,ReferenceGeneProduct,UniProt:P06239 LCK,58457,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P06239,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
2,P12931-1,ReferenceIsoform,UniProt:P12931-1 SRC,65044,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P12931-1,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
3,P07947,ReferenceGeneProduct,UniProt:P07947 YES1,67748,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P07947,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
4,P07948,ReferenceGeneProduct,UniProt:P07948 LYN,58853,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P07948,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
5,P10721,ReferenceGeneProduct,UniProt:P10721 KIT,58103,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P10721,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
6,P21583-1,ReferenceIsoform,UniProt:P21583-1 KITLG,403295,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P21583-1,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
7,Q06124,ReferenceGeneProduct,UniProt:Q06124 PTPN11,62439,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/Q06124,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
8,P62993-1,ReferenceIsoform,UniProt:P62993-1 GRB2,55928,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P62993-1,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
9,P42336,ReferenceGeneProduct,UniProt:P42336 PIK3CA,61074,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P42336,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
10,Q92569,ReferenceGeneProduct,UniProt:Q92569 PIK3R3,61182,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/Q92569,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
11,O00459,ReferenceGeneProduct,UniProt:O00459 PIK3R2,61194,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/O00459,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
12,P27986,ReferenceGeneProduct,UniProt:P27986 PIK3R1,61192,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P27986,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
13,Q9UQC2,ReferenceGeneProduct,UniProt:Q9UQC2 GAB2,147728,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/Q9UQC2,9031773,"PI3K:p-KIT:sSCF dimer:p-KIT,PI3K:p(Y)-GAB2:GRB2:p-SHP2:p-KIT complex [plasma membrane]",DefinedSet
14,18348,ReferenceMolecule,"1-phosphatidyl-1D-myo-inositol 4,5-bisphosphate [ChEBI:18348]",188413,SimpleEntity,http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18348,179856,"PI(4,5)P2 [plasma membrane]",SimpleEntity
15,30616,ReferenceMolecule,ATP(4-) [ChEBI:30616],8869364,SimpleEntity,http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:30616,113592,ATP [cytosol],SimpleEntity
16,456216,ReferenceMolecule,ADP(3-) [ChEBI:456216],8869367,SimpleEntity,http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:456216,29370,ADP [cytosol],SimpleEntity
17,16618,ReferenceMolecule,"1-phosphatidyl-1D-myo-inositol 3,4,5-trisphosphate [ChEBI:16618]",188411,SimpleEntity,http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16618,179838,"PI(3,4,5)P3 [plasma membrane]",SimpleEntity
18,P06241,ReferenceGeneProduct,UniProt:P06241 FYN,55160,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P06241,205271,SFKs:p-KIT complex [plasma membrane],Complex
19,P06239,ReferenceGeneProduct,UniProt:P06239 LCK,58457,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P06239,205271,SFKs:p-KIT complex [plasma membrane],Complex
20,P12931-1,ReferenceIsoform,UniProt:P12931-1 SRC,65044,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P12931-1,205271,SFKs:p-KIT complex [plasma membrane],Complex
21,P07947,ReferenceGeneProduct,UniProt:P07947 YES1,67748,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P07947,205271,SFKs:p-KIT complex [plasma membrane],Complex
22,P07948,ReferenceGeneProduct,UniProt:P07948 LYN,58853,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P07948,205271,SFKs:p-KIT complex [plasma membrane],Complex
23,P10721,ReferenceGeneProduct,UniProt:P10721 KIT,58103,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P10721,205271,SFKs:p-KIT complex [plasma membrane],Complex
24,P21583-1,ReferenceIsoform,UniProt:P21583-1 KITLG,403295,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P21583-1,205271,SFKs:p-KIT complex [plasma membrane],Complex
25,O60674,ReferenceGeneProduct,UniProt:O60674 JAK2,57647,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/O60674,210620,JAK2 [cytosol],EntityWithAccessionedSequence
26,P06241,ReferenceGeneProduct,UniProt:P06241 FYN,55160,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P06241,1433493,JAK2:SFKS:p-KIT complex [plasma membrane],Complex
27,P06239,ReferenceGeneProduct,UniProt:P06239 LCK,58457,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P06239,1433493,JAK2:SFKS:p-KIT complex [plasma membrane],Complex
28,P12931-1,ReferenceIsoform,UniProt:P12931-1 SRC,65044,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P12931-1,1433493,JAK2:SFKS:p-KIT complex [plasma membrane],Complex
29,P07947,ReferenceGeneProduct,UniProt:P07947 YES1,67748,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P07947,1433493,JAK2:SFKS:p-KIT complex [plasma membrane],Complex
...,...,...,...,...,...,...,...,...,...
5685,P02462,ReferenceGeneProduct,UniProt:P02462 COL4A1,51132,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P02462,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5686,P08572,ReferenceGeneProduct,UniProt:P08572 COL4A2,51162,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P08572,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5687,P25940,ReferenceGeneProduct,UniProt:P25940 COL5A3,51176,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P25940,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5688,P05997,ReferenceGeneProduct,UniProt:P05997 COL5A2,51164,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P05997,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5689,P20908,ReferenceGeneProduct,UniProt:P20908 COL5A1,51134,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P20908,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5690,18137,ReferenceMolecule,heparan sulfate alpha-D-glucosaminide [ChEBI:18137],36001,SimpleEntity,http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:18137,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5691,17421,ReferenceMolecule,heparan sulfate N-acetyl-alpha-D-glucosaminide [ChEBI:17421],36401,SimpleEntity,http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17421,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5692,P10451,ReferenceGeneProduct,UniProt:P10451 SPP1,61022,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P10451,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5693,P07996,ReferenceGeneProduct,UniProt:P07996 THBS1,66519,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P07996,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5694,P35442,ReferenceGeneProduct,UniProt:P35442 THBS2,66521,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P35442,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5695,P49746,ReferenceGeneProduct,UniProt:P49746 THBS3,66523,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P49746,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5696,P35443,ReferenceGeneProduct,UniProt:P35443 THBS4,66525,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P35443,381952,PDGF A and B chains:ECM complex [extracellular region],Complex
5697,P04085-1,ReferenceIsoform,UniProt:P04085-1 PDGFA,61432,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P04085-1,380749,proPDGF-AA dimer [Golgi membrane],Complex
5698,P04085-2,ReferenceIsoform,UniProt:P04085-2 PDGFA,151910,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P04085-2,380749,proPDGF-AA dimer [Golgi membrane],Complex
5699,P04085-2,ReferenceIsoform,UniProt:P04085-2 PDGFA,151910,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P04085-2,8865271,N-ter PDGF-A fragment [Golgi lumen],DefinedSet
5700,P04085-1,ReferenceIsoform,UniProt:P04085-1 PDGFA,61432,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P04085-1,8865271,N-ter PDGF-A fragment [Golgi lumen],DefinedSet
5701,P04085-1,ReferenceIsoform,UniProt:P04085-1 PDGFA,61432,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P04085-1,380761,active PDGF-AA dimer [extracellular region],Complex
5702,P04085-2,ReferenceIsoform,UniProt:P04085-2 PDGFA,151910,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P04085-2,380761,active PDGF-AA dimer [extracellular region],Complex
5703,P01127,ReferenceGeneProduct,UniProt:P01127 PDGFB,61434,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P01127,389078,PDGF beta receptor:PDGF chain B homodimer [plasma membrane],Complex
5704,P09619,ReferenceGeneProduct,UniProt:P09619 PDGFRB,61600,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P09619,389078,PDGF beta receptor:PDGF chain B homodimer [plasma membrane],Complex
5705,Q9GZP0,ReferenceGeneProduct,UniProt:Q9GZP0 PDGFD,242243,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/Q9GZP0,381936,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [endoplasmic reticulum lumen]",DefinedSet
5706,P04085-1,ReferenceIsoform,UniProt:P04085-1 PDGFA,61432,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P04085-1,381936,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [endoplasmic reticulum lumen]",DefinedSet
5707,P04085-2,ReferenceIsoform,UniProt:P04085-2 PDGFA,151910,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P04085-2,381936,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [endoplasmic reticulum lumen]",DefinedSet
5708,P01127,ReferenceGeneProduct,UniProt:P01127 PDGFB,61434,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P01127,381936,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [endoplasmic reticulum lumen]",DefinedSet
5709,Q9NRA1-1,ReferenceIsoform,UniProt:Q9NRA1-1 PDGFC,381893,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/Q9NRA1-1,381936,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [endoplasmic reticulum lumen]",DefinedSet
5710,P04085-1,ReferenceIsoform,UniProt:P04085-1 PDGFA,61432,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P04085-1,381926,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [Golgi membrane]",DefinedSet
5711,P04085-2,ReferenceIsoform,UniProt:P04085-2 PDGFA,151910,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P04085-2,381926,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [Golgi membrane]",DefinedSet
5712,P01127,ReferenceGeneProduct,UniProt:P01127 PDGFB,61434,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/P01127,381926,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [Golgi membrane]",DefinedSet
5713,Q9GZP0,ReferenceGeneProduct,UniProt:Q9GZP0 PDGFD,242243,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/Q9GZP0,381926,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [Golgi membrane]",DefinedSet
5714,Q9NRA1-1,ReferenceIsoform,UniProt:Q9NRA1-1 PDGFC,381893,EntityWithAccessionedSequence,https://purl.uniprot.org/uniprot/Q9NRA1-1,381926,"PDGF precursor dimers (AA, BB, A/B, CC, DD) [Golgi membrane]",DefinedSet